ti.cpp:4:21: warning: AQK01: Need #include <utility> for 'std::pair<int, int>'
    4 | std::pair<int, int> p;
      |                     ^
ti.cpp:6:17: warning: AQK01: Need #include <ti5.h> for 'n'
    6 | using namespace n;
      |                 ^
ti.cpp:7:1: warning: AQK01: Need #include <ti4.h> for 't'
    7 | t i;
      | ^
ti.cpp:8:16: warning: AQK01: Need #include <ti3.h> for 'f'
    8 | void (*pf)() = f;
      |                ^
4 warnings generated.
