In file included from csatr_usingdirectiveinheader.t.cpp:3:
./csatr_usingdirectiveinheader.t.hpp:14:17: warning: TR16: Namespace level using directive for 'bde_verify' in header file
   14 | using namespace bde_verify;
      |                 ^
./csatr_usingdirectiveinheader.t.hpp:18:21: warning: TR16: Namespace level using directive for 'bde_verify' in header file
   18 |     using namespace bde_verify;
      |                     ^
csatr_usingdirectiveinheader.t.cpp:6:17: warning: AQJ02: Using directive precedes header inclusion
    6 | using namespace bde_verify;
      |                 ^
csatr_usingdirectiveinheader.t.cpp:18:11: note: AQJ02: Header included here
   18 | #include <bsl_cstddef.h>
      |           ^
3 warnings generated.
