a.cpp:27:14: warning: AE01: Assignment appears as top-level macro condition
   27 |     BSLS_A(c = 1);
      |            ~~^~~
a.cpp:3:28: note: expanded from macro 'BSLS_A'
    3 | #define BSLS_A(X) BSLS_A_A(X)
      |                            ^
a.cpp:5:13: note: expanded from macro 'BSLS_A_A'
    5 | do { if ((!(X))) { invoke(#X, __FILE__, __LINE__); } } while (false)
      |             ^
a.cpp:28:15: warning: AE01: Assignment appears as top-level macro condition
   28 |     BBTU_AV(c = 1);
      |             ~~^~~
a.cpp:7:57: note: expanded from macro 'BBTU_AV'
    7 | #define BBTU_AV(...) BBTU_LOOPN_A(BBTU_NA(__VA_ARGS__), __VA_ARGS__)
      |                                                         ^~~~~~~~~~~
a.cpp:11:51: note: expanded from macro 'BBTU_LOOPN_A'
   11 | #define BBTU_LOOPN_A(N, ...) BBTU_LOOPN_A_IMPL(N, __VA_ARGS__)
      |                                                   ^~~~~~~~~~~
a.cpp:12:60: note: expanded from macro 'BBTU_LOOPN_A_IMPL'
   12 | #define BBTU_LOOPN_A_IMPL(N, ...) BBTU_EX(BBTU_LOOP##N##_A(__VA_ARGS__))
      |                                                            ^~~~~~~~~~~
a.cpp:6:30: note: expanded from macro 'BBTU_A'
    6 | #define BBTU_A(X) { aSsErT(!(X), #X, __LINE__); }
      |                              ^
a.cpp:8:20: note: expanded from macro 'BBTU_EX'
    8 | #define BBTU_EX(X) X
      |                    ^
a.cpp:29:24: warning: AE01: Assignment appears as top-level macro condition
   29 |     BBTU_AV(1, 2, 3, c = 1);
      |                      ~~^~~
a.cpp:7:57: note: expanded from macro 'BBTU_AV'
    7 | #define BBTU_AV(...) BBTU_LOOPN_A(BBTU_NA(__VA_ARGS__), __VA_ARGS__)
      |                                                         ^~~~~~~~~~~
a.cpp:11:51: note: expanded from macro 'BBTU_LOOPN_A'
   11 | #define BBTU_LOOPN_A(N, ...) BBTU_LOOPN_A_IMPL(N, __VA_ARGS__)
      |                                                   ^~~~~~~~~~~
a.cpp:12:60: note: expanded from macro 'BBTU_LOOPN_A_IMPL'
   12 | #define BBTU_LOOPN_A_IMPL(N, ...) BBTU_EX(BBTU_LOOP##N##_A(__VA_ARGS__))
      |                                                            ^~~~~~~~~~~
a.cpp:10:42: note: expanded from macro 'BBTU_LOOP3_A'
   10 | #define BBTU_LOOP3_A(I,J,K,X) { aSsErT(!(X), #X, __LINE__); }
      |                                          ^
a.cpp:8:20: note: expanded from macro 'BBTU_EX'
    8 | #define BBTU_EX(X) X
      |                    ^
a.cpp:30:10: warning: AE01: Assignment appears as top-level macro condition
   30 |     AV(c = 1);
      |        ~~^~~
a.cpp:2:42: note: expanded from macro 'AV'
    2 | #define AV(...) LOOPN_A(NA(__VA_ARGS__), __VA_ARGS__)
      |                                          ^~~~~~~~~~~
a.cpp:16:41: note: expanded from macro 'LOOPN_A'
   16 | #define LOOPN_A(N, ...) LOOPN_A_IMPL(N, __VA_ARGS__)
      |                                         ^~~~~~~~~~~
a.cpp:17:46: note: expanded from macro 'LOOPN_A_IMPL'
   17 | #define LOOPN_A_IMPL(N, ...) LOOP ## N ## _A(__VA_ARGS__)
      |                                              ^~~~~~~~~~~
a.cpp:14:28: note: expanded from macro 'LOOP0_A'
   14 | #define LOOP0_A(X) { if (!(X)) { aSsErT(1, #X, __LINE__); } }
      |                            ^
a.cpp:31:19: warning: AE01: Assignment appears as top-level macro condition
   31 |     AV(1, 2, 3, c = 1);
      |                 ~~^~~
a.cpp:2:42: note: expanded from macro 'AV'
    2 | #define AV(...) LOOPN_A(NA(__VA_ARGS__), __VA_ARGS__)
      |                                          ^~~~~~~~~~~
a.cpp:16:41: note: expanded from macro 'LOOPN_A'
   16 | #define LOOPN_A(N, ...) LOOPN_A_IMPL(N, __VA_ARGS__)
      |                                         ^~~~~~~~~~~
a.cpp:17:46: note: expanded from macro 'LOOPN_A_IMPL'
   17 | #define LOOPN_A_IMPL(N, ...) LOOP ## N ## _A(__VA_ARGS__)
      |                                              ^~~~~~~~~~~
a.cpp:15:34: note: expanded from macro 'LOOP3_A'
   15 | #define LOOP3_A(I,J,K,X) { if (!(X)) { aSsErT(1, #X, __LINE__); } }
      |                                  ^
5 warnings generated.
