In file included from csatr_entityrestrictions.t.cpp:3:
./csatr_entityrestrictions.t.h:29:14: warning: TR17: Function 'swap' declared at global scope
   29 |         void swap(EntityRestrictions&);
      |              ^~~~
./csatr_entityrestrictions.t.h:30:14: warning: TR17: Function 'swap' declared at global scope
   30 |         void swap(EntityRestrictions&, EntityRestrictions&, EntityRestrictions&);
      |              ^~~~
./csatr_entityrestrictions.t.h:31:14: warning: TR17: Function 'swap' declared at global scope
   31 |         void swap(EntityRestrictions&, EntityRestrictionsAux&);
      |              ^~~~
./csatr_entityrestrictions.t.h:32:14: warning: TR17: Function 'swap' declared at global scope
   32 |         void swap(EntityRestrictions, EntityRestrictions);
      |              ^~~~
./csatr_entityrestrictions.t.h:33:14: warning: TR17: Function 'swap' declared at global scope
   33 |         void swap(EntityRestrictions const&, EntityRestrictions const&);
      |              ^~~~
./csatr_entityrestrictions.t.h:38:20: warning: TR17: Variable 'entityRestrictionsVar' declared at global scope
   38 |         extern int entityRestrictionsVar;
      |                    ^
./csatr_entityrestrictions.t.h:39:14: warning: TR17: Function 'entityRestrictionsFunction' declared at global scope
   39 |         void entityRestrictionsFunction();
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_entityrestrictions.t.h:41:36: warning: TR17: Typedef 'EntityRestrictionsTypedef' declared at global scope
   41 |         typedef EntityRestrictions EntityRestrictionsTypedef;
      |                                    ^
./csatr_entityrestrictions.t.h:42:14: warning: TR17: Enum 'EntityRestrictionsEnum' declared at global scope
   42 |         enum EntityRestrictionsEnum {};
      |              ^
9 warnings generated.
