data.cpp:1:5: warning: AQb01: Data variable with global visibilty
    1 | int a;
      |     ^
data.cpp:3:12: warning: AQb01: Data variable with global visibilty
    3 | extern int c;
      |            ^
data.cpp:5:5: warning: AQb01: Data variable with global visibilty
    5 | int d = 1;
      |     ^
data.cpp:34:5: warning: AQb01: Data variable with global visibilty
   34 | int a;
      |     ^
data.cpp:36:12: warning: AQb01: Data variable with global visibilty
   36 | extern int c;
      |            ^
data.cpp:38:5: warning: AQb01: Data variable with global visibilty
   38 | int d = 1;
      |     ^
6 warnings generated.
