csamisc_unnamed_temporary.t.cpp:11:5: warning: expression result unused [-Wunused-value]
   11 |     int(5);
      |     ^   ~
csamisc_unnamed_temporary.t.cpp:19:5: warning: expression result unused [-Wunused-value]
   19 |     std::string(std::string("5"));
      |     ^           ~~~~~~~~~~~~~~~~
csamisc_unnamed_temporary.t.cpp:16:5: warning: UT01: Unnamed object will be immediately destroyed
   16 |     std::string("5");
      |     ^
csamisc_unnamed_temporary.t.cpp:19:5: warning: UT01: Unnamed object will be immediately destroyed
   19 |     std::string(std::string("5"));
      |     ^
csamisc_unnamed_temporary.t.cpp:22:5: warning: UT01: Unnamed object will be immediately destroyed
   22 |     std::string(5, ' ');
      |     ^
csamisc_unnamed_temporary.t.cpp:25:5: warning: UT01: Unnamed object will be immediately destroyed
   25 |     std::string(std::string(5, ' '));
      |     ^
csamisc_unnamed_temporary.t.cpp:32:10: warning: UT01: Unnamed object will be immediately destroyed
   32 |     for (std::string(); i; std::string()) {
      |          ^
csamisc_unnamed_temporary.t.cpp:32:28: warning: UT01: Unnamed object will be immediately destroyed
   32 |     for (std::string(); i; std::string()) {
      |                            ^
8 warnings generated.
