csafmt_whitespace.t.cpp:3:6: warning: ESP01: Space at end of line
    3 | #if 0 
      |      ^
csafmt_whitespace.t.cpp:4:18: warning: TAB01: Tab character in source
    4 | const char *a = "       ";
      |                  ^
csafmt_whitespace.t.cpp:5:18: warning: TAB01: Tab characters in source
    5 | const char *b = "                       ";
      |                  ^
csafmt_whitespace.t.cpp:6:18: warning: TAB01: Tab characters in source
    6 | const char *c = "                       x       ";
      |                  ^
csafmt_whitespace.t.cpp:6:22: warning: TAB01: Tab character in source
    6 | const char *c = "                       x       ";
      |                                          ^
csafmt_whitespace.t.cpp:8:21: warning: TAB01: Tab character in source
    8 | // const char *a = "    ";
      |                     ^
csafmt_whitespace.t.cpp:9:21: warning: TAB01: Tab characters in source
    9 | // const char *b = "                    ";
      |                     ^
csafmt_whitespace.t.cpp:10:21: warning: TAB01: Tab characters in source
   10 | // const char *c = "                    x       ";
      |                     ^
csafmt_whitespace.t.cpp:10:25: warning: TAB01: Tab character in source
   10 | // const char *c = "                    x       ";
      |                                          ^
csafmt_whitespace.t.cpp:11:7: warning: ESP01: Space at end of line
   11 | #endif 
      |       ^
csafmt_whitespace.t.cpp:13:11: warning: ESP01: Space at end of line
   13 | int x = 7; 
      |           ^
csafmt_whitespace.t.cpp:14:11: warning: ESP01: Spaces at end of line
   14 | int y = 7;  
      |           ^
csafmt_whitespace.t.cpp:15:6: warning: ESP01: Space at end of line
   15 | #else 
      |      ^
csafmt_whitespace.t.cpp:16:14: warning: ESP01: Space at end of line
   16 | // int x = 7; 
      |              ^
csafmt_whitespace.t.cpp:17:14: warning: ESP01: Spaces at end of line
   17 | // int y = 7;  
      |              ^
15 warnings generated.
