csamisc_hashptr.t.cpp:11:5: warning: HC01: Hash will depend only on the pointer value, not the contents, of the argument
   11 |     std::hash<                        char    *>()( "abc");
      |     ^
csamisc_hashptr.t.cpp:12:5: warning: HC01: Hash will depend only on the pointer value, not the contents, of the argument
   12 |     std::hash<const                   char    *>()( "abc");
      |     ^
csamisc_hashptr.t.cpp:13:5: warning: HC01: Hash will depend only on the pointer value, not the contents, of the argument
   13 |     std::hash<                        wchar_t *>()(L"abc");
      |     ^
csamisc_hashptr.t.cpp:14:5: warning: HC01: Hash will depend only on the pointer value, not the contents, of the argument
   14 |     std::hash<const                   wchar_t *>()(L"abc");
      |     ^
csamisc_hashptr.t.cpp:17:5: warning: HC01: Hash will depend only on the pointer value, not the contents, of the argument
   17 |     std::hash<double *>()(&d);
      |     ^
5 warnings generated.
