enums.cpp:20:12: warning: IND01: Possibly mis-indented line
   20 |            ABC = 1,
      |            ^
enums.cpp:20:12: note: IND01: Correct version may be
        ABC = 1,
enums.cpp:22:12: warning: IND01: Possibly mis-indented line
   22 |            IJ = 3
      |            ^
enums.cpp:22:12: note: IND01: Correct version may be
        IJ = 3
enums.cpp:29:9: warning: IND01: Possibly mis-indented line
   29 |         DEFGH = 2,
      |         ^
enums.cpp:29:9: note: IND01: Correct version may be
           DEFGH = 2,
enums.cpp:30:13: warning: IND01: Possibly mis-indented line
   30 |             IJ = 3
      |             ^
enums.cpp:30:13: note: IND01: Correct version may be
           IJ = 3
4 warnings generated.
