csamisc_namespacetags.t.cpp:6:1: warning: NT01: End of bde_verify namespace should be marked with "}  // close enterprise namespace"
    6 | } // end bde_verify
      | ^
csamisc_namespacetags.t.cpp:5:1: warning: NT01: End of csamisc namespace should be marked with "}  // close package namespace"
    5 | } // end csamisc
      | ^
csamisc_namespacetags.t.cpp:4:1: warning: NT01: End of anonymous namespace should be marked with "}  // close unnamed namespace"
    4 | } // end anonymous
      | ^
csamisc_namespacetags.t.cpp:9:1: warning: NT01: End of joe namespace should be marked with "}  // close namespace joe"
    9 | } // end joe
      | ^
4 warnings generated.
