deprecated.cpp:33:5: warning: DP01: Call to deprecated function
   33 |     f();
      |     ^
In file included from deprecated.cpp:2:
./dep2.h:3:5: note: DP01: Deprecated here
    3 |     // !DEPRECATED!:
      |     ^
deprecated.cpp:34:5: warning: DP01: Call to deprecated function
   34 |     h();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:1:1: note: DP01: Deprecated here
    1 | //@DEPRECATED://
      | ^
deprecated.cpp:35:5: warning: DP01: Call to deprecated function
   35 |     i();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:1:1: note: DP01: Deprecated here
    1 | //@DEPRECATED://
      | ^
deprecated.cpp:36:5: warning: DP01: Call to deprecated function
   36 |     C::j();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:1:1: note: DP01: Deprecated here
    1 | //@DEPRECATED://
      | ^
deprecated.cpp:37:5: warning: DP01: Call to deprecated function
   37 |     C::k();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:7:9: note: DP01: Deprecated here
    7 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:38:5: warning: DP01: Call to deprecated function
   38 |     C::l();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:1:1: note: DP01: Deprecated here
    1 | //@DEPRECATED://
      | ^
deprecated.cpp:39:5: warning: DP01: Call to deprecated function
   39 |     D<int>::j();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:1:1: note: DP01: Deprecated here
    1 | //@DEPRECATED://
      | ^
deprecated.cpp:40:5: warning: DP01: Call to deprecated function
   40 |     D<void>::k();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:14:9: note: DP01: Deprecated here
   14 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:41:5: warning: DP01: Call to deprecated function
   41 |     D<C>::l();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:1:1: note: DP01: Deprecated here
    1 | //@DEPRECATED://
      | ^
deprecated.cpp:43:5: warning: DP01: Call to deprecated function
   43 |     E::k();
      |     ^
In file included from deprecated.cpp:2:
./dep2.h:7:9: note: DP01: Deprecated here
    7 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:46:5: warning: DP01: Call to deprecated function
   46 |     F<void>::k();
      |     ^
In file included from deprecated.cpp:2:
./dep2.h:14:9: note: DP01: Deprecated here
   14 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:48:5: warning: DP01: Call to deprecated function
   48 |     CC::j();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:18:5: note: DP01: Deprecated here
   18 |     // !DEPRECATED!:
      |     ^
deprecated.cpp:49:5: warning: DP01: Call to deprecated function
   49 |     CC::k();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:21:9: note: DP01: Deprecated here
   21 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:50:5: warning: DP01: Call to deprecated function
   50 |     CC::l();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:18:5: note: DP01: Deprecated here
   18 |     // !DEPRECATED!:
      |     ^
deprecated.cpp:51:5: warning: DP01: Call to deprecated function
   51 |     DD<int>::j();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:26:5: note: DP01: Deprecated here
   26 |     // !DEPRECATED!:
      |     ^
deprecated.cpp:52:5: warning: DP01: Call to deprecated function
   52 |     DD<void>::k();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:29:9: note: DP01: Deprecated here
   29 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:53:5: warning: DP01: Call to deprecated function
   53 |     DD<C>::l();
      |     ^
In file included from deprecated.cpp:1:
./dep1.h:26:5: note: DP01: Deprecated here
   26 |     // !DEPRECATED!:
      |     ^
deprecated.cpp:54:5: warning: DP01: Call to deprecated function
   54 |     EE::j();
      |     ^
In file included from deprecated.cpp:2:
./dep2.h:18:9: note: DP01: Deprecated here
   18 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:55:5: warning: DP01: Call to deprecated function
   55 |     EE::k();
      |     ^
In file included from deprecated.cpp:2:
./dep2.h:21:9: note: DP01: Deprecated here
   21 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:56:5: warning: DP01: Call to deprecated function
   56 |     EE::l();
      |     ^
In file included from deprecated.cpp:2:
./dep2.h:18:9: note: DP01: Deprecated here
   18 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:57:5: warning: DP01: Call to deprecated function
   57 |     FF<int>::j();
      |     ^
In file included from deprecated.cpp:2:
./dep2.h:26:9: note: DP01: Deprecated here
   26 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:58:5: warning: DP01: Call to deprecated function
   58 |     FF<void>::k();
      |     ^
In file included from deprecated.cpp:2:
./dep2.h:29:9: note: DP01: Deprecated here
   29 |         // !DEPRECATED!:
      |         ^
deprecated.cpp:59:5: warning: DP01: Call to deprecated function
   59 |     FF<C>::l();
      |     ^
In file included from deprecated.cpp:2:
./dep2.h:26:9: note: DP01: Deprecated here
   26 |         // !DEPRECATED!:
      |         ^
23 warnings generated.
