csabbg_testdriver.t.cpp:33:24: warning: TP19: Missing or malformed standard test driver section
   33 | //                       STANDARD BDE ASSERT TEST MACRO
      |                        ^
csabbg_testdriver.t.cpp:33:24: note: TP19: One correct form (of several possible) is

// ============================================================================
//                     STANDARD BDE ASSERT TEST FUNCTION
// ----------------------------------------------------------------------------

namespace {

int testStatus = 0;

void aSsErT(bool condition, const char *message, int line)
{
    if (condition) {
        cout << "Error " __FILE__ "(" << line << "): " << message
             << "    (failed)" << endl;

        if (0 <= testStatus && testStatus <= 100) {
            ++testStatus;
        }
    }
}

}  // close unnamed namespace

csabbg_testdriver.t.cpp:49:18: warning: TP19: Missing or malformed standard test driver section
   49 | //                       STANDARD BDE TEST DRIVER MACROS
      |                  ^
csabbg_testdriver.t.cpp:49:18: note: TP19: One correct form (of several possible) is

// ============================================================================
//               STANDARD BDE TEST DRIVER MACRO ABBREVIATIONS
// ----------------------------------------------------------------------------

#define ASSERT       BSLIM_TESTUTIL_ASSERT
#define ASSERTV      BSLIM_TESTUTIL_ASSERTV

#define LOOP_ASSERT  BSLIM_TESTUTIL_LOOP_ASSERT
#define LOOP0_ASSERT BSLIM_TESTUTIL_LOOP0_ASSERT
#define LOOP1_ASSERT BSLIM_TESTUTIL_LOOP1_ASSERT
#define LOOP2_ASSERT BSLIM_TESTUTIL_LOOP2_ASSERT
#define LOOP3_ASSERT BSLIM_TESTUTIL_LOOP3_ASSERT
#define LOOP4_ASSERT BSLIM_TESTUTIL_LOOP4_ASSERT
#define LOOP5_ASSERT BSLIM_TESTUTIL_LOOP5_ASSERT
#define LOOP6_ASSERT BSLIM_TESTUTIL_LOOP6_ASSERT

#define Q            BSLIM_TESTUTIL_Q   // Quote identifier literally.
#define P            BSLIM_TESTUTIL_P   // Print identifier and value.
#define P_           BSLIM_TESTUTIL_P_  // P(X) without '\n'.
#define T_           BSLIM_TESTUTIL_T_  // Print a tab (w/o newline).
#define L_           BSLIM_TESTUTIL_L_  // current Line number

csabbg_testdriver.t.cpp:283:1: warning: TP25: Cannot find definition of class 'bsl::basic_nonesuch' from @CLASSES section.
  283 | //    bsl::basic_nonesuch : not there::more stuff
      | ^
csabbg_testdriver.t.cpp:289:14: warning: TP27: Method not called in test driver
  289 |         void setF();
      |              ^
csabbg_testdriver.t.cpp:290:14: warning: TP27: Method not called in test driver
  290 |         void setG();
      |              ^
csabbg_testdriver.t.cpp:291:13: warning: TP27: Method not called in test driver
  291 |         int F() const;
      |             ^
csabbg_testdriver.t.cpp:292:13: warning: TP27: Method not called in test driver
  292 |         int F();
      |             ^
csabbg_testdriver.t.cpp:293:13: warning: TP27: Method not called in test driver
  293 |         int G() const;
      |             ^
csabbg_testdriver.t.cpp:294:9: warning: TP27: Method not called in test driver
  294 |         joe();
      |         ^
csabbg_testdriver.t.cpp:295:9: warning: TP27: Method not called in test driver
  295 |         joe(int);
      |         ^
csabbg_testdriver.t.cpp:296:9: warning: TP27: Method not called in test driver
  296 |         ~joe();
      |         ^
csabbg_testdriver.t.cpp:298:31: warning: TP27: Method not called in test driver
  298 |         template <int N> void H();
      |                               ^
csabbg_testdriver.t.cpp:24:4: warning: TP03: Missing test number
   24 | // [  ] void setF();
      |    ^~~~
csabbg_testdriver.t.cpp:29:4: warning: TP03: Missing test number
   29 | // [  ] BREATHING TEST
      |    ^~~~
csabbg_testdriver.t.cpp:30:4: warning: TP03: Missing test number
   30 | // [  ] USAGE EXAMPLE
      |    ^~~~
csabbg_testdriver.t.cpp:24:1: warning: TP26: Tested classes have 2 functions named 'F' but the test plan has 1
   24 | // [  ] void setF();
      | ^
csabbg_testdriver.t.cpp:24:1: warning: TP26: Tested classes have a function named 'G' but the test plan has none
csabbg_testdriver.t.cpp:24:1: warning: TP26: Tested classes have a function named 'H' but the test plan has none
csabbg_testdriver.t.cpp:24:1: warning: TP26: Tested classes have 2 functions named 'joe' but the test plan has none
csabbg_testdriver.t.cpp:24:1: warning: TP26: Tested classes have a function named '~joe' but the test plan has none
csabbg_testdriver.t.cpp:272:7: warning: TP24: `default:` case should set `testStatus = -1;`
  272 |       }
      |       ^
csabbg_testdriver.t.cpp:267:7: warning: TP17: Test case does not contain 'if (verbose) print test banner'
  267 |       case -1: {
      |       ^
csabbg_testdriver.t.cpp:267:7: warning: TP05: Test case has no comment
csabbg_testdriver.t.cpp:190:27: warning: TP20: Within loops, act on very verbose
  190 |         for (; b; ) { if (verbose) { cout << endl; } F(); }
      |                           ^
csabbg_testdriver.t.cpp:191:27: warning: TP20: Within loops, act on very verbose
  191 |         while (b)   { if (verbose) { cout << endl; } F(); }
      |                           ^
csabbg_testdriver.t.cpp:192:27: warning: TP20: Within loops, act on very verbose
  192 |         do          { if (verbose) { cout << endl; } F(); } while (b);
      |                           ^
csabbg_testdriver.t.cpp:212:31: warning: TP20: Within loops, act on very verbose
  212 |             for (; b; ) { if (verbose) { cout << endl; } F(); }
      |                               ^
csabbg_testdriver.t.cpp:213:31: warning: TP20: Within loops, act on very verbose
  213 |             while (b)   { if (verbose) { cout << endl; } F(); }
      |                               ^
csabbg_testdriver.t.cpp:214:31: warning: TP20: Within loops, act on very verbose
  214 |             do          { if (verbose) { cout << endl; } F(); } while (b);
      |                               ^
csabbg_testdriver.t.cpp:231:31: warning: TP20: Within loops, act on very verbose
  231 |             for (; b; ) { if (verbose) { cout << endl; } F(); }
      |                               ^
csabbg_testdriver.t.cpp:232:31: warning: TP20: Within loops, act on very verbose
  232 |             while (b)   { if (verbose) { cout << endl; } F(); }
      |                               ^
csabbg_testdriver.t.cpp:233:31: warning: TP20: Within loops, act on very verbose
  233 |             do          { if (verbose) { cout << endl; } F(); } while (b);
      |                               ^
csabbg_testdriver.t.cpp:257:31: warning: TP20: Within loops, act on very verbose
  257 |             for (; b; ) { if (verbose) { cout << endl; } F(); }
      |                               ^
csabbg_testdriver.t.cpp:258:31: warning: TP20: Within loops, act on very verbose
  258 |             while (b)   { if (verbose) { cout << endl; } F(); }
      |                               ^
csabbg_testdriver.t.cpp:259:31: warning: TP20: Within loops, act on very verbose
  259 |             do          { if (verbose) { cout << endl; } F(); } while (b);
      |                               ^
csabbg_testdriver.t.cpp:195:9: warning: TP21: Loops must contain very verbose action
  195 |         for (; b; ) { F(); }
      |         ^
csabbg_testdriver.t.cpp:196:9: warning: TP21: Loops must contain very verbose action
  196 |         while (b)   { F(); }
      |         ^
csabbg_testdriver.t.cpp:197:9: warning: TP21: Loops must contain very verbose action
  197 |         do          { F(); } while (b);
      |         ^
csabbg_testdriver.t.cpp:217:13: warning: TP21: Loops must contain very verbose action
  217 |             for (; b; ) { F(); }
      |             ^
csabbg_testdriver.t.cpp:218:13: warning: TP21: Loops must contain very verbose action
  218 |             while (b)   { F(); }
      |             ^
csabbg_testdriver.t.cpp:219:13: warning: TP21: Loops must contain very verbose action
  219 |             do          { F(); } while (b);
      |             ^
csabbg_testdriver.t.cpp:236:13: warning: TP21: Loops must contain very verbose action
  236 |             for (; b; ) { F(); }
      |             ^
csabbg_testdriver.t.cpp:237:13: warning: TP21: Loops must contain very verbose action
  237 |             while (b)   { F(); }
      |             ^
csabbg_testdriver.t.cpp:238:13: warning: TP21: Loops must contain very verbose action
  238 |             do          { F(); } while (b);
      |             ^
csabbg_testdriver.t.cpp:262:13: warning: TP21: Loops must contain very verbose action
  262 |             for (; b; ) { F(); }
      |             ^
csabbg_testdriver.t.cpp:263:13: warning: TP21: Loops must contain very verbose action
  263 |             while (b)   { F(); }
      |             ^
csabbg_testdriver.t.cpp:264:13: warning: TP21: Loops must contain very verbose action
  264 |             do          { F(); } while (b);
      |             ^
csabbg_testdriver.t.cpp:165:10: warning: TP32: Plans should be numbered like so: //: 1 ...
  165 |         //
      |          ^
csabbg_testdriver.t.cpp:167:9: warning: TP08: Test plan does not have case number 1 for this item
  167 |         //   BREATHING TEST
      |         ^
csabbg_testdriver.t.cpp:29:6: note: TP08: Test plan item is
   29 | // [  ] BREATHING TEST
      |      ^
csabbg_testdriver.t.cpp:151:21: warning: TP18: Incorrect test banner format
  151 |             cout << endl << "'f' AND 'setf'" << endl << "==========" << '\n';
      |                     ^
csabbg_testdriver.t.cpp:151:21: note: TP18: Correct format is
                    "\n" "'f' AND 'setf'" "\n"
                         "==============" "\n"
csabbg_testdriver.t.cpp:138:20: warning: TP22: Mismatch between title in comment and as printed
  138 |         // 'f' AND "setf"
      |                    ^
csabbg_testdriver.t.cpp:151:21: note: TP22: Printed title is
  151 |             cout << endl << "'f' AND 'setf'" << endl << "==========" << '\n';
      |                     ^
csabbg_testdriver.t.cpp:142:10: warning: TP29: Concerns should be numbered like so: //: 1 ...
  142 |         //
      |          ^
csabbg_testdriver.t.cpp:144:10: warning: TP32: Plans should be numbered like so: //: 1 ...
  144 |         //
      |          ^
csabbg_testdriver.t.cpp:146:9: warning: TP08: Test plan does not have case number 2 for this item
  146 |         //   int F() const;
      |         ^
csabbg_testdriver.t.cpp:27:6: note: TP08: Test plan item is
   27 | // [ 5] int F() const;
      |      ^
csabbg_testdriver.t.cpp:147:9: warning: TP09: Test plan should contain this item from 'Testing' section of case 2
  147 |         //   int G() const;
      |         ^
csabbg_testdriver.t.cpp:25:9: warning: TP06: 'Testing' section of case 2 should contain this item from test plan
   25 | // [ 2] void setG();
      |         ^
csabbg_testdriver.t.cpp:124:20: warning: TP18: Incorrect test banner format (not ALL CAPS)
  124 |             printf("Usage Example\n=============\n");
      |                    ^
csabbg_testdriver.t.cpp:124:20: note: TP18: Correct format is
                   "USAGE EXAMPLE" "\n"
                   "=============" "\n"
csabbg_testdriver.t.cpp:107:13: warning: TP22: Mismatch between title in comment and as printed
  107 |         // USAGE EXAMPLE
      |             ^
csabbg_testdriver.t.cpp:124:20: note: TP22: Printed title is
  124 |             printf("Usage Example\n=============\n");
      |                    ^
csabbg_testdriver.t.cpp:110:10: warning: TP29: Concerns should be numbered like so: //: 1 ...
  110 |         //   The usage example provided in the component header file must
      |          ^
csabbg_testdriver.t.cpp:114:10: warning: TP32: Plans should be numbered like so: //: 1 ...
  114 |         //   Incorporate usage example from header into driver, remove leading
      |          ^
csabbg_testdriver.t.cpp:120:9: warning: TP08: Test plan does not have case number 3 for this item
  120 |         //   USAGE EXAMPLE
      |         ^
csabbg_testdriver.t.cpp:30:6: note: TP08: Test plan item is
   30 | // [  ] USAGE EXAMPLE
      |      ^
61 warnings generated.
