csabbg_cmporder.cpp:18:14: warning: CO01: Non-modifiable operand should be on the left
   18 |     if (   a == 1 ) return 1; if (   a < 1 ) return 1;
      |            ~~^~~~
csabbg_cmporder.cpp:18:14: note: CO01: Replace with 1 == a
   18 |     if (   a == 1 ) return 1; if (   a < 1 ) return 1;
      |            ~~^~~~
csabbg_cmporder.cpp:19:14: warning: CO01: Non-modifiable operand should be on the left
   19 |     if (   a == 1.) return 1; if (   a < 1.) return 1;
      |            ~~^~~~~
csabbg_cmporder.cpp:19:14: note: CO01: Replace with 1. == a
   19 |     if (   a == 1.) return 1; if (   a < 1.) return 1;
      |            ~~^~~~~
csabbg_cmporder.cpp:20:14: warning: CO01: Non-modifiable operand should be on the left
   20 |     if (   d == 1 ) return 1; if (   d < 1 ) return 1;
      |            ~~^~~~
csabbg_cmporder.cpp:20:14: note: CO01: Replace with 1 == d
   20 |     if (   d == 1 ) return 1; if (   d < 1 ) return 1;
      |            ~~^~~~
csabbg_cmporder.cpp:21:14: warning: CO01: Non-modifiable operand should be on the left
   21 |     if (   d == 1.) return 1; if (   d < 1.) return 1;
      |            ~~^~~~~
csabbg_cmporder.cpp:21:14: note: CO01: Replace with 1. == d
   21 |     if (   d == 1.) return 1; if (   d < 1.) return 1;
      |            ~~^~~~~
csabbg_cmporder.cpp:22:14: warning: CO02: Constant-expression operand should be on the left
   22 |     if (  ca == 1 ) return 1; if (  ca < 1 ) return 1;
      |           ~~~^~~~
csabbg_cmporder.cpp:22:14: note: CO02: Replace with 1 == ca
   22 |     if (  ca == 1 ) return 1; if (  ca < 1 ) return 1;
      |           ~~~^~~~
csabbg_cmporder.cpp:23:14: warning: CO02: Constant-expression operand should be on the left
   23 |     if (  ca == 1.) return 1; if (  ca < 1.) return 1;
      |           ~~~^~~~~
csabbg_cmporder.cpp:23:14: note: CO02: Replace with 1. == ca
   23 |     if (  ca == 1.) return 1; if (  ca < 1.) return 1;
      |           ~~~^~~~~
csabbg_cmporder.cpp:24:14: warning: CO02: Constant-expression operand should be on the left
   24 |     if (  cd == 1 ) return 1; if (  cd < 1 ) return 1;
      |           ~~~^~~~
csabbg_cmporder.cpp:24:14: note: CO02: Replace with 1 == cd
   24 |     if (  cd == 1 ) return 1; if (  cd < 1 ) return 1;
      |           ~~~^~~~
csabbg_cmporder.cpp:25:14: warning: CO02: Constant-expression operand should be on the left
   25 |     if (  cd == 1.) return 1; if (  cd < 1.) return 1;
      |           ~~~^~~~~
csabbg_cmporder.cpp:25:14: note: CO02: Replace with 1. == cd
   25 |     if (  cd == 1.) return 1; if (  cd < 1.) return 1;
      |           ~~~^~~~~
csabbg_cmporder.cpp:26:14: warning: CO01: Non-modifiable operand should be on the left
   26 |     if ( *pa == 1 ) return 1; if ( *pa < 1 ) return 1;
      |          ~~~~^~~~
csabbg_cmporder.cpp:26:14: note: CO01: Replace with 1 == *pa
   26 |     if ( *pa == 1 ) return 1; if ( *pa < 1 ) return 1;
      |          ~~~~^~~~
csabbg_cmporder.cpp:27:14: warning: CO01: Non-modifiable operand should be on the left
   27 |     if ( *pa == 1.) return 1; if ( *pa < 1.) return 1;
      |          ~~~~^~~~~
csabbg_cmporder.cpp:27:14: note: CO01: Replace with 1. == *pa
   27 |     if ( *pa == 1.) return 1; if ( *pa < 1.) return 1;
      |          ~~~~^~~~~
csabbg_cmporder.cpp:28:14: warning: CO01: Non-modifiable operand should be on the left
   28 |     if ( *pd == 1 ) return 1; if ( *pd < 1 ) return 1;
      |          ~~~~^~~~
csabbg_cmporder.cpp:28:14: note: CO01: Replace with 1 == *pd
   28 |     if ( *pd == 1 ) return 1; if ( *pd < 1 ) return 1;
      |          ~~~~^~~~
csabbg_cmporder.cpp:29:14: warning: CO01: Non-modifiable operand should be on the left
   29 |     if ( *pd == 1.) return 1; if ( *pd < 1.) return 1;
      |          ~~~~^~~~~
csabbg_cmporder.cpp:29:14: note: CO01: Replace with 1. == *pd
   29 |     if ( *pd == 1.) return 1; if ( *pd < 1.) return 1;
      |          ~~~~^~~~~
csabbg_cmporder.cpp:30:14: warning: CO02: Constant-expression operand should be on the left
   30 |     if (*pca == 1 ) return 1; if (*pca < 1 ) return 1;
      |         ~~~~~^~~~
csabbg_cmporder.cpp:30:14: note: CO02: Replace with 1 == *pca
   30 |     if (*pca == 1 ) return 1; if (*pca < 1 ) return 1;
      |         ~~~~~^~~~
csabbg_cmporder.cpp:31:14: warning: CO02: Constant-expression operand should be on the left
   31 |     if (*pca == 1.) return 1; if (*pca < 1.) return 1;
      |         ~~~~~^~~~~
csabbg_cmporder.cpp:31:14: note: CO02: Replace with 1. == *pca
   31 |     if (*pca == 1.) return 1; if (*pca < 1.) return 1;
      |         ~~~~~^~~~~
csabbg_cmporder.cpp:32:14: warning: CO02: Constant-expression operand should be on the left
   32 |     if (*pcd == 1 ) return 1; if (*pcd < 1 ) return 1;
      |         ~~~~~^~~~
csabbg_cmporder.cpp:32:14: note: CO02: Replace with 1 == *pcd
   32 |     if (*pcd == 1 ) return 1; if (*pcd < 1 ) return 1;
      |         ~~~~~^~~~
csabbg_cmporder.cpp:33:14: warning: CO02: Constant-expression operand should be on the left
   33 |     if (*pcd == 1.) return 1; if (*pcd < 1.) return 1;
      |         ~~~~~^~~~~
csabbg_cmporder.cpp:33:14: note: CO02: Replace with 1. == *pcd
   33 |     if (*pcd == 1.) return 1; if (*pcd < 1.) return 1;
      |         ~~~~~^~~~~
csabbg_cmporder.cpp:34:14: warning: CO01: Non-modifiable operand should be on the left
   34 |     if (  ra == 1 ) return 1; if (  ra < 1 ) return 1;
      |           ~~~^~~~
csabbg_cmporder.cpp:34:14: note: CO01: Replace with 1 == ra
   34 |     if (  ra == 1 ) return 1; if (  ra < 1 ) return 1;
      |           ~~~^~~~
csabbg_cmporder.cpp:35:14: warning: CO01: Non-modifiable operand should be on the left
   35 |     if (  ra == 1.) return 1; if (  ra < 1.) return 1;
      |           ~~~^~~~~
csabbg_cmporder.cpp:35:14: note: CO01: Replace with 1. == ra
   35 |     if (  ra == 1.) return 1; if (  ra < 1.) return 1;
      |           ~~~^~~~~
csabbg_cmporder.cpp:36:14: warning: CO01: Non-modifiable operand should be on the left
   36 |     if (  rd == 1 ) return 1; if (  rd < 1 ) return 1;
      |           ~~~^~~~
csabbg_cmporder.cpp:36:14: note: CO01: Replace with 1 == rd
   36 |     if (  rd == 1 ) return 1; if (  rd < 1 ) return 1;
      |           ~~~^~~~
csabbg_cmporder.cpp:37:14: warning: CO01: Non-modifiable operand should be on the left
   37 |     if (  rd == 1.) return 1; if (  rd < 1.) return 1;
      |           ~~~^~~~~
csabbg_cmporder.cpp:37:14: note: CO01: Replace with 1. == rd
   37 |     if (  rd == 1.) return 1; if (  rd < 1.) return 1;
      |           ~~~^~~~~
csabbg_cmporder.cpp:38:14: warning: CO02: Constant-expression operand should be on the left
   38 |     if ( rca == 1 ) return 1; if ( rca < 1 ) return 1;
      |          ~~~~^~~~
csabbg_cmporder.cpp:38:14: note: CO02: Replace with 1 == rca
   38 |     if ( rca == 1 ) return 1; if ( rca < 1 ) return 1;
      |          ~~~~^~~~
csabbg_cmporder.cpp:39:14: warning: CO02: Constant-expression operand should be on the left
   39 |     if ( rca == 1.) return 1; if ( rca < 1.) return 1;
      |          ~~~~^~~~~
csabbg_cmporder.cpp:39:14: note: CO02: Replace with 1. == rca
   39 |     if ( rca == 1.) return 1; if ( rca < 1.) return 1;
      |          ~~~~^~~~~
csabbg_cmporder.cpp:40:14: warning: CO02: Constant-expression operand should be on the left
   40 |     if ( rcd == 1 ) return 1; if ( rcd < 1 ) return 1;
      |          ~~~~^~~~
csabbg_cmporder.cpp:40:14: note: CO02: Replace with 1 == rcd
   40 |     if ( rcd == 1 ) return 1; if ( rcd < 1 ) return 1;
      |          ~~~~^~~~
csabbg_cmporder.cpp:41:14: warning: CO02: Constant-expression operand should be on the left
   41 |     if ( rcd == 1.) return 1; if ( rcd < 1.) return 1;
      |          ~~~~^~~~~
csabbg_cmporder.cpp:41:14: note: CO02: Replace with 1. == rcd
   41 |     if ( rcd == 1.) return 1; if ( rcd < 1.) return 1;
      |          ~~~~^~~~~
csabbg_cmporder.cpp:66:15: warning: CO01: Non-modifiable operand should be on the left
   66 |     if ((   a == 1 ) << (   a < 1 )) return 1;
      |             ~~^~~~
csabbg_cmporder.cpp:66:15: note: CO01: Replace with 1 == a
   66 |     if ((   a == 1 ) << (   a < 1 )) return 1;
      |             ~~^~~~
csabbg_cmporder.cpp:67:15: warning: CO01: Non-modifiable operand should be on the left
   67 |     if ((   a == 1.) << (   a < 1.)) return 1;
      |             ~~^~~~~
csabbg_cmporder.cpp:67:15: note: CO01: Replace with 1. == a
   67 |     if ((   a == 1.) << (   a < 1.)) return 1;
      |             ~~^~~~~
csabbg_cmporder.cpp:68:15: warning: CO01: Non-modifiable operand should be on the left
   68 |     if ((   d == 1 ) << (   d < 1 )) return 1;
      |             ~~^~~~
csabbg_cmporder.cpp:68:15: note: CO01: Replace with 1 == d
   68 |     if ((   d == 1 ) << (   d < 1 )) return 1;
      |             ~~^~~~
csabbg_cmporder.cpp:69:15: warning: CO01: Non-modifiable operand should be on the left
   69 |     if ((   d == 1.) << (   d < 1.)) return 1;
      |             ~~^~~~~
csabbg_cmporder.cpp:69:15: note: CO01: Replace with 1. == d
   69 |     if ((   d == 1.) << (   d < 1.)) return 1;
      |             ~~^~~~~
csabbg_cmporder.cpp:70:15: warning: CO02: Constant-expression operand should be on the left
   70 |     if ((  ca == 1 ) << (  ca < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:70:15: note: CO02: Replace with 1 == ca
   70 |     if ((  ca == 1 ) << (  ca < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:71:15: warning: CO02: Constant-expression operand should be on the left
   71 |     if ((  ca == 1.) << (  ca < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:71:15: note: CO02: Replace with 1. == ca
   71 |     if ((  ca == 1.) << (  ca < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:72:15: warning: CO02: Constant-expression operand should be on the left
   72 |     if ((  cd == 1 ) << (  cd < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:72:15: note: CO02: Replace with 1 == cd
   72 |     if ((  cd == 1 ) << (  cd < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:73:15: warning: CO02: Constant-expression operand should be on the left
   73 |     if ((  cd == 1.) << (  cd < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:73:15: note: CO02: Replace with 1. == cd
   73 |     if ((  cd == 1.) << (  cd < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:74:15: warning: CO01: Non-modifiable operand should be on the left
   74 |     if (( *pa == 1 ) << ( *pa < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:74:15: note: CO01: Replace with 1 == *pa
   74 |     if (( *pa == 1 ) << ( *pa < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:75:15: warning: CO01: Non-modifiable operand should be on the left
   75 |     if (( *pa == 1.) << ( *pa < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:75:15: note: CO01: Replace with 1. == *pa
   75 |     if (( *pa == 1.) << ( *pa < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:76:15: warning: CO01: Non-modifiable operand should be on the left
   76 |     if (( *pd == 1 ) << ( *pd < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:76:15: note: CO01: Replace with 1 == *pd
   76 |     if (( *pd == 1 ) << ( *pd < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:77:15: warning: CO01: Non-modifiable operand should be on the left
   77 |     if (( *pd == 1.) << ( *pd < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:77:15: note: CO01: Replace with 1. == *pd
   77 |     if (( *pd == 1.) << ( *pd < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:78:15: warning: CO02: Constant-expression operand should be on the left
   78 |     if ((*pca == 1 ) << (*pca < 1 )) return 1;
      |          ~~~~~^~~~
csabbg_cmporder.cpp:78:15: note: CO02: Replace with 1 == *pca
   78 |     if ((*pca == 1 ) << (*pca < 1 )) return 1;
      |          ~~~~~^~~~
csabbg_cmporder.cpp:79:15: warning: CO02: Constant-expression operand should be on the left
   79 |     if ((*pca == 1.) << (*pca < 1.)) return 1;
      |          ~~~~~^~~~~
csabbg_cmporder.cpp:79:15: note: CO02: Replace with 1. == *pca
   79 |     if ((*pca == 1.) << (*pca < 1.)) return 1;
      |          ~~~~~^~~~~
csabbg_cmporder.cpp:80:15: warning: CO02: Constant-expression operand should be on the left
   80 |     if ((*pcd == 1 ) << (*pcd < 1 )) return 1;
      |          ~~~~~^~~~
csabbg_cmporder.cpp:80:15: note: CO02: Replace with 1 == *pcd
   80 |     if ((*pcd == 1 ) << (*pcd < 1 )) return 1;
      |          ~~~~~^~~~
csabbg_cmporder.cpp:81:15: warning: CO02: Constant-expression operand should be on the left
   81 |     if ((*pcd == 1.) << (*pcd < 1.)) return 1;
      |          ~~~~~^~~~~
csabbg_cmporder.cpp:81:15: note: CO02: Replace with 1. == *pcd
   81 |     if ((*pcd == 1.) << (*pcd < 1.)) return 1;
      |          ~~~~~^~~~~
csabbg_cmporder.cpp:82:15: warning: CO01: Non-modifiable operand should be on the left
   82 |     if ((  ra == 1 ) << (  ra < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:82:15: note: CO01: Replace with 1 == ra
   82 |     if ((  ra == 1 ) << (  ra < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:83:15: warning: CO01: Non-modifiable operand should be on the left
   83 |     if ((  ra == 1.) << (  ra < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:83:15: note: CO01: Replace with 1. == ra
   83 |     if ((  ra == 1.) << (  ra < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:84:15: warning: CO01: Non-modifiable operand should be on the left
   84 |     if ((  rd == 1 ) << (  rd < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:84:15: note: CO01: Replace with 1 == rd
   84 |     if ((  rd == 1 ) << (  rd < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:85:15: warning: CO01: Non-modifiable operand should be on the left
   85 |     if ((  rd == 1.) << (  rd < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:85:15: note: CO01: Replace with 1. == rd
   85 |     if ((  rd == 1.) << (  rd < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:86:15: warning: CO02: Constant-expression operand should be on the left
   86 |     if (( rca == 1 ) << ( rca < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:86:15: note: CO02: Replace with 1 == rca
   86 |     if (( rca == 1 ) << ( rca < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:87:15: warning: CO02: Constant-expression operand should be on the left
   87 |     if (( rca == 1.) << ( rca < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:87:15: note: CO02: Replace with 1. == rca
   87 |     if (( rca == 1.) << ( rca < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:88:15: warning: CO02: Constant-expression operand should be on the left
   88 |     if (( rcd == 1 ) << ( rcd < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:88:15: note: CO02: Replace with 1 == rcd
   88 |     if (( rcd == 1 ) << ( rcd < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:89:15: warning: CO02: Constant-expression operand should be on the left
   89 |     if (( rcd == 1.) << ( rcd < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:89:15: note: CO02: Replace with 1. == rcd
   89 |     if (( rcd == 1.) << ( rcd < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:90:15: warning: CO01: Non-modifiable operand should be on the left
   90 |     if ((   a == 1 ) != (   a < 1 )) return 1;
      |             ~~^~~~
csabbg_cmporder.cpp:90:15: note: CO01: Replace with 1 == a
   90 |     if ((   a == 1 ) != (   a < 1 )) return 1;
      |             ~~^~~~
csabbg_cmporder.cpp:91:15: warning: CO01: Non-modifiable operand should be on the left
   91 |     if ((   a == 1.) != (   a < 1.)) return 1;
      |             ~~^~~~~
csabbg_cmporder.cpp:91:15: note: CO01: Replace with 1. == a
   91 |     if ((   a == 1.) != (   a < 1.)) return 1;
      |             ~~^~~~~
csabbg_cmporder.cpp:92:15: warning: CO01: Non-modifiable operand should be on the left
   92 |     if ((   d == 1 ) != (   d < 1 )) return 1;
      |             ~~^~~~
csabbg_cmporder.cpp:92:15: note: CO01: Replace with 1 == d
   92 |     if ((   d == 1 ) != (   d < 1 )) return 1;
      |             ~~^~~~
csabbg_cmporder.cpp:93:15: warning: CO01: Non-modifiable operand should be on the left
   93 |     if ((   d == 1.) != (   d < 1.)) return 1;
      |             ~~^~~~~
csabbg_cmporder.cpp:93:15: note: CO01: Replace with 1. == d
   93 |     if ((   d == 1.) != (   d < 1.)) return 1;
      |             ~~^~~~~
csabbg_cmporder.cpp:94:15: warning: CO02: Constant-expression operand should be on the left
   94 |     if ((  ca == 1 ) != (  ca < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:94:15: note: CO02: Replace with 1 == ca
   94 |     if ((  ca == 1 ) != (  ca < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:95:15: warning: CO02: Constant-expression operand should be on the left
   95 |     if ((  ca == 1.) != (  ca < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:95:15: note: CO02: Replace with 1. == ca
   95 |     if ((  ca == 1.) != (  ca < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:96:15: warning: CO02: Constant-expression operand should be on the left
   96 |     if ((  cd == 1 ) != (  cd < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:96:15: note: CO02: Replace with 1 == cd
   96 |     if ((  cd == 1 ) != (  cd < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:97:15: warning: CO02: Constant-expression operand should be on the left
   97 |     if ((  cd == 1.) != (  cd < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:97:15: note: CO02: Replace with 1. == cd
   97 |     if ((  cd == 1.) != (  cd < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:98:15: warning: CO01: Non-modifiable operand should be on the left
   98 |     if (( *pa == 1 ) != ( *pa < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:98:15: note: CO01: Replace with 1 == *pa
   98 |     if (( *pa == 1 ) != ( *pa < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:99:15: warning: CO01: Non-modifiable operand should be on the left
   99 |     if (( *pa == 1.) != ( *pa < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:99:15: note: CO01: Replace with 1. == *pa
   99 |     if (( *pa == 1.) != ( *pa < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:100:15: warning: CO01: Non-modifiable operand should be on the left
  100 |     if (( *pd == 1 ) != ( *pd < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:100:15: note: CO01: Replace with 1 == *pd
  100 |     if (( *pd == 1 ) != ( *pd < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:101:15: warning: CO01: Non-modifiable operand should be on the left
  101 |     if (( *pd == 1.) != ( *pd < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:101:15: note: CO01: Replace with 1. == *pd
  101 |     if (( *pd == 1.) != ( *pd < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:102:15: warning: CO02: Constant-expression operand should be on the left
  102 |     if ((*pca == 1 ) != (*pca < 1 )) return 1;
      |          ~~~~~^~~~
csabbg_cmporder.cpp:102:15: note: CO02: Replace with 1 == *pca
  102 |     if ((*pca == 1 ) != (*pca < 1 )) return 1;
      |          ~~~~~^~~~
csabbg_cmporder.cpp:103:15: warning: CO02: Constant-expression operand should be on the left
  103 |     if ((*pca == 1.) != (*pca < 1.)) return 1;
      |          ~~~~~^~~~~
csabbg_cmporder.cpp:103:15: note: CO02: Replace with 1. == *pca
  103 |     if ((*pca == 1.) != (*pca < 1.)) return 1;
      |          ~~~~~^~~~~
csabbg_cmporder.cpp:104:15: warning: CO02: Constant-expression operand should be on the left
  104 |     if ((*pcd == 1 ) != (*pcd < 1 )) return 1;
      |          ~~~~~^~~~
csabbg_cmporder.cpp:104:15: note: CO02: Replace with 1 == *pcd
  104 |     if ((*pcd == 1 ) != (*pcd < 1 )) return 1;
      |          ~~~~~^~~~
csabbg_cmporder.cpp:105:15: warning: CO02: Constant-expression operand should be on the left
  105 |     if ((*pcd == 1.) != (*pcd < 1.)) return 1;
      |          ~~~~~^~~~~
csabbg_cmporder.cpp:105:15: note: CO02: Replace with 1. == *pcd
  105 |     if ((*pcd == 1.) != (*pcd < 1.)) return 1;
      |          ~~~~~^~~~~
csabbg_cmporder.cpp:106:15: warning: CO01: Non-modifiable operand should be on the left
  106 |     if ((  ra == 1 ) != (  ra < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:106:15: note: CO01: Replace with 1 == ra
  106 |     if ((  ra == 1 ) != (  ra < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:107:15: warning: CO01: Non-modifiable operand should be on the left
  107 |     if ((  ra == 1.) != (  ra < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:107:15: note: CO01: Replace with 1. == ra
  107 |     if ((  ra == 1.) != (  ra < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:108:15: warning: CO01: Non-modifiable operand should be on the left
  108 |     if ((  rd == 1 ) != (  rd < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:108:15: note: CO01: Replace with 1 == rd
  108 |     if ((  rd == 1 ) != (  rd < 1 )) return 1;
      |            ~~~^~~~
csabbg_cmporder.cpp:109:15: warning: CO01: Non-modifiable operand should be on the left
  109 |     if ((  rd == 1.) != (  rd < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:109:15: note: CO01: Replace with 1. == rd
  109 |     if ((  rd == 1.) != (  rd < 1.)) return 1;
      |            ~~~^~~~~
csabbg_cmporder.cpp:110:15: warning: CO02: Constant-expression operand should be on the left
  110 |     if (( rca == 1 ) != ( rca < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:110:15: note: CO02: Replace with 1 == rca
  110 |     if (( rca == 1 ) != ( rca < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:111:15: warning: CO02: Constant-expression operand should be on the left
  111 |     if (( rca == 1.) != ( rca < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:111:15: note: CO02: Replace with 1. == rca
  111 |     if (( rca == 1.) != ( rca < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:112:15: warning: CO02: Constant-expression operand should be on the left
  112 |     if (( rcd == 1 ) != ( rcd < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:112:15: note: CO02: Replace with 1 == rcd
  112 |     if (( rcd == 1 ) != ( rcd < 1 )) return 1;
      |           ~~~~^~~~
csabbg_cmporder.cpp:113:15: warning: CO02: Constant-expression operand should be on the left
  113 |     if (( rcd == 1.) != ( rcd < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:113:15: note: CO02: Replace with 1. == rcd
  113 |     if (( rcd == 1.) != ( rcd < 1.)) return 1;
      |           ~~~~^~~~~
csabbg_cmporder.cpp:166:12: warning: CO01: Non-modifiable operand should be on the left
  166 |     if (o  ==   ca) return 1; if (o  <   ca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:166:12: note: CO01: Replace with ca   ==  o
  166 |     if (o  ==   ca) return 1; if (o  <   ca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:167:12: warning: CO01: Non-modifiable operand should be on the left
  167 |     if (od ==   ca) return 1; if (od <   ca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:167:12: note: CO01: Replace with ca   == od
  167 |     if (od ==   ca) return 1; if (od <   ca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:168:12: warning: CO01: Non-modifiable operand should be on the left
  168 |     if (o  ==   cd) return 1; if (o  <   cd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:168:12: note: CO01: Replace with cd   ==  o
  168 |     if (o  ==   cd) return 1; if (o  <   cd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:169:12: warning: CO01: Non-modifiable operand should be on the left
  169 |     if (od ==   cd) return 1; if (od <   cd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:169:12: note: CO01: Replace with cd   == od
  169 |     if (od ==   cd) return 1; if (od <   cd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:174:12: warning: CO01: Non-modifiable operand should be on the left
  174 |     if (o  == *pca) return 1; if (o  < *pca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:174:12: note: CO01: Replace with *pca ==  o
  174 |     if (o  == *pca) return 1; if (o  < *pca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:175:12: warning: CO01: Non-modifiable operand should be on the left
  175 |     if (od == *pca) return 1; if (od < *pca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:175:12: note: CO01: Replace with *pca == od
  175 |     if (od == *pca) return 1; if (od < *pca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:176:12: warning: CO01: Non-modifiable operand should be on the left
  176 |     if (o  == *pcd) return 1; if (o  < *pcd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:176:12: note: CO01: Replace with *pcd ==  o
  176 |     if (o  == *pcd) return 1; if (o  < *pcd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:177:12: warning: CO01: Non-modifiable operand should be on the left
  177 |     if (od == *pcd) return 1; if (od < *pcd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:177:12: note: CO01: Replace with *pcd == od
  177 |     if (od == *pcd) return 1; if (od < *pcd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:182:12: warning: CO01: Non-modifiable operand should be on the left
  182 |     if (o  ==  rca) return 1; if (o  <  rca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:182:12: note: CO01: Replace with rca  ==  o
  182 |     if (o  ==  rca) return 1; if (o  <  rca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:183:12: warning: CO01: Non-modifiable operand should be on the left
  183 |     if (od ==  rca) return 1; if (od <  rca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:183:12: note: CO01: Replace with rca  == od
  183 |     if (od ==  rca) return 1; if (od <  rca) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:184:12: warning: CO01: Non-modifiable operand should be on the left
  184 |     if (o  ==  rcd) return 1; if (o  <  rcd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:184:12: note: CO01: Replace with rcd  ==  o
  184 |     if (o  ==  rcd) return 1; if (o  <  rcd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:185:12: warning: CO01: Non-modifiable operand should be on the left
  185 |     if (od ==  rcd) return 1; if (od <  rcd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:185:12: note: CO01: Replace with rcd  == od
  185 |     if (od ==  rcd) return 1; if (od <  rcd) return 1;
      |         ~~~^~~~~~~
csabbg_cmporder.cpp:214:13: warning: CO01: Non-modifiable operand should be on the left
  214 |     if ((o  ==   ca) << (o  <   ca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:214:13: note: CO01: Replace with ca   ==  o
  214 |     if ((o  ==   ca) << (o  <   ca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:215:13: warning: CO01: Non-modifiable operand should be on the left
  215 |     if ((od ==   ca) << (od <   ca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:215:13: note: CO01: Replace with ca   == od
  215 |     if ((od ==   ca) << (od <   ca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:216:13: warning: CO01: Non-modifiable operand should be on the left
  216 |     if ((o  ==   cd) << (o  <   cd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:216:13: note: CO01: Replace with cd   ==  o
  216 |     if ((o  ==   cd) << (o  <   cd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:217:13: warning: CO01: Non-modifiable operand should be on the left
  217 |     if ((od ==   cd) << (od <   cd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:217:13: note: CO01: Replace with cd   == od
  217 |     if ((od ==   cd) << (od <   cd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:222:13: warning: CO01: Non-modifiable operand should be on the left
  222 |     if ((o  == *pca) << (o  < *pca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:222:13: note: CO01: Replace with *pca ==  o
  222 |     if ((o  == *pca) << (o  < *pca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:223:13: warning: CO01: Non-modifiable operand should be on the left
  223 |     if ((od == *pca) << (od < *pca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:223:13: note: CO01: Replace with *pca == od
  223 |     if ((od == *pca) << (od < *pca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:224:13: warning: CO01: Non-modifiable operand should be on the left
  224 |     if ((o  == *pcd) << (o  < *pcd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:224:13: note: CO01: Replace with *pcd ==  o
  224 |     if ((o  == *pcd) << (o  < *pcd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:225:13: warning: CO01: Non-modifiable operand should be on the left
  225 |     if ((od == *pcd) << (od < *pcd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:225:13: note: CO01: Replace with *pcd == od
  225 |     if ((od == *pcd) << (od < *pcd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:230:13: warning: CO01: Non-modifiable operand should be on the left
  230 |     if ((o  ==  rca) << (o  <  rca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:230:13: note: CO01: Replace with rca  ==  o
  230 |     if ((o  ==  rca) << (o  <  rca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:231:13: warning: CO01: Non-modifiable operand should be on the left
  231 |     if ((od ==  rca) << (od <  rca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:231:13: note: CO01: Replace with rca  == od
  231 |     if ((od ==  rca) << (od <  rca)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:232:13: warning: CO01: Non-modifiable operand should be on the left
  232 |     if ((o  ==  rcd) << (o  <  rcd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:232:13: note: CO01: Replace with rcd  ==  o
  232 |     if ((o  ==  rcd) << (o  <  rcd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:233:13: warning: CO01: Non-modifiable operand should be on the left
  233 |     if ((od ==  rcd) << (od <  rcd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:233:13: note: CO01: Replace with rcd  == od
  233 |     if ((od ==  rcd) << (od <  rcd)) return 1;
      |          ~~~^~~~~~~
csabbg_cmporder.cpp:234:9: warning: CO01: Non-modifiable operand should be on the left
  234 |     if(a==1)return 1;if(a<1)return 1;
      |        ~^~~
csabbg_cmporder.cpp:234:9: note: CO01: Replace with 1==a
  234 |     if(a==1)return 1;if(a<1)return 1;
      |        ~^~~
csabbg_cmporder.cpp:235:9: warning: CO01: Non-modifiable operand should be on the left
  235 |     if(a==1.)return 1;if(a<1.)return 1;
      |        ~^~~~
csabbg_cmporder.cpp:235:9: note: CO01: Replace with 1.==a
  235 |     if(a==1.)return 1;if(a<1.)return 1;
      |        ~^~~~
csabbg_cmporder.cpp:236:9: warning: CO01: Non-modifiable operand should be on the left
  236 |     if(d==1)return 1;if(d<1)return 1;
      |        ~^~~
csabbg_cmporder.cpp:236:9: note: CO01: Replace with 1==d
  236 |     if(d==1)return 1;if(d<1)return 1;
      |        ~^~~
csabbg_cmporder.cpp:237:9: warning: CO01: Non-modifiable operand should be on the left
  237 |     if(d==1.)return 1;if(d<1.)return 1;
      |        ~^~~~
csabbg_cmporder.cpp:237:9: note: CO01: Replace with 1.==d
  237 |     if(d==1.)return 1;if(d<1.)return 1;
      |        ~^~~~
csabbg_cmporder.cpp:238:10: warning: CO02: Constant-expression operand should be on the left
  238 |     if(ca==1)return 1;if(ca<1)return 1;
      |        ~~^~~
csabbg_cmporder.cpp:238:10: note: CO02: Replace with 1==ca
  238 |     if(ca==1)return 1;if(ca<1)return 1;
      |        ~~^~~
csabbg_cmporder.cpp:239:10: warning: CO02: Constant-expression operand should be on the left
  239 |     if(ca==1.)return 1;if(ca<1.)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:239:10: note: CO02: Replace with 1.==ca
  239 |     if(ca==1.)return 1;if(ca<1.)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:240:10: warning: CO02: Constant-expression operand should be on the left
  240 |     if(cd==1)return 1;if(cd<1)return 1;
      |        ~~^~~
csabbg_cmporder.cpp:240:10: note: CO02: Replace with 1==cd
  240 |     if(cd==1)return 1;if(cd<1)return 1;
      |        ~~^~~
csabbg_cmporder.cpp:241:10: warning: CO02: Constant-expression operand should be on the left
  241 |     if(cd==1.)return 1;if(cd<1.)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:241:10: note: CO02: Replace with 1.==cd
  241 |     if(cd==1.)return 1;if(cd<1.)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:242:11: warning: CO01: Non-modifiable operand should be on the left
  242 |     if(*pa==1)return 1;if(*pa<1)return 1;
      |        ~~~^~~
csabbg_cmporder.cpp:242:11: note: CO01: Replace with 1==*pa
  242 |     if(*pa==1)return 1;if(*pa<1)return 1;
      |        ~~~^~~
csabbg_cmporder.cpp:243:11: warning: CO01: Non-modifiable operand should be on the left
  243 |     if(*pa==1.)return 1;if(*pa<1.)return 1;
      |        ~~~^~~~
csabbg_cmporder.cpp:243:11: note: CO01: Replace with 1.==*pa
  243 |     if(*pa==1.)return 1;if(*pa<1.)return 1;
      |        ~~~^~~~
csabbg_cmporder.cpp:244:11: warning: CO01: Non-modifiable operand should be on the left
  244 |     if(*pd==1)return 1;if(*pd<1)return 1;
      |        ~~~^~~
csabbg_cmporder.cpp:244:11: note: CO01: Replace with 1==*pd
  244 |     if(*pd==1)return 1;if(*pd<1)return 1;
      |        ~~~^~~
csabbg_cmporder.cpp:245:11: warning: CO01: Non-modifiable operand should be on the left
  245 |     if(*pd==1.)return 1;if(*pd<1.)return 1;
      |        ~~~^~~~
csabbg_cmporder.cpp:245:11: note: CO01: Replace with 1.==*pd
  245 |     if(*pd==1.)return 1;if(*pd<1.)return 1;
      |        ~~~^~~~
csabbg_cmporder.cpp:246:12: warning: CO02: Constant-expression operand should be on the left
  246 |     if(*pca==1)return 1;if(*pca<1)return 1;
      |        ~~~~^~~
csabbg_cmporder.cpp:246:12: note: CO02: Replace with 1==*pca
  246 |     if(*pca==1)return 1;if(*pca<1)return 1;
      |        ~~~~^~~
csabbg_cmporder.cpp:247:12: warning: CO02: Constant-expression operand should be on the left
  247 |     if(*pca==1.)return 1;if(*pca<1.)return 1;
      |        ~~~~^~~~
csabbg_cmporder.cpp:247:12: note: CO02: Replace with 1.==*pca
  247 |     if(*pca==1.)return 1;if(*pca<1.)return 1;
      |        ~~~~^~~~
csabbg_cmporder.cpp:248:12: warning: CO02: Constant-expression operand should be on the left
  248 |     if(*pcd==1)return 1;if(*pcd<1)return 1;
      |        ~~~~^~~
csabbg_cmporder.cpp:248:12: note: CO02: Replace with 1==*pcd
  248 |     if(*pcd==1)return 1;if(*pcd<1)return 1;
      |        ~~~~^~~
csabbg_cmporder.cpp:249:12: warning: CO02: Constant-expression operand should be on the left
  249 |     if(*pcd==1.)return 1;if(*pcd<1.)return 1;
      |        ~~~~^~~~
csabbg_cmporder.cpp:249:12: note: CO02: Replace with 1.==*pcd
  249 |     if(*pcd==1.)return 1;if(*pcd<1.)return 1;
      |        ~~~~^~~~
csabbg_cmporder.cpp:250:10: warning: CO01: Non-modifiable operand should be on the left
  250 |     if(ra==1)return 1;if(ra<1)return 1;
      |        ~~^~~
csabbg_cmporder.cpp:250:10: note: CO01: Replace with 1==ra
  250 |     if(ra==1)return 1;if(ra<1)return 1;
      |        ~~^~~
csabbg_cmporder.cpp:251:10: warning: CO01: Non-modifiable operand should be on the left
  251 |     if(ra==1.)return 1;if(ra<1.)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:251:10: note: CO01: Replace with 1.==ra
  251 |     if(ra==1.)return 1;if(ra<1.)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:252:10: warning: CO01: Non-modifiable operand should be on the left
  252 |     if(rd==1)return 1;if(rd<1)return 1;
      |        ~~^~~
csabbg_cmporder.cpp:252:10: note: CO01: Replace with 1==rd
  252 |     if(rd==1)return 1;if(rd<1)return 1;
      |        ~~^~~
csabbg_cmporder.cpp:253:10: warning: CO01: Non-modifiable operand should be on the left
  253 |     if(rd==1.)return 1;if(rd<1.)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:253:10: note: CO01: Replace with 1.==rd
  253 |     if(rd==1.)return 1;if(rd<1.)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:254:11: warning: CO02: Constant-expression operand should be on the left
  254 |     if(rca==1)return 1;if(rca<1)return 1;
      |        ~~~^~~
csabbg_cmporder.cpp:254:11: note: CO02: Replace with 1==rca
  254 |     if(rca==1)return 1;if(rca<1)return 1;
      |        ~~~^~~
csabbg_cmporder.cpp:255:11: warning: CO02: Constant-expression operand should be on the left
  255 |     if(rca==1.)return 1;if(rca<1.)return 1;
      |        ~~~^~~~
csabbg_cmporder.cpp:255:11: note: CO02: Replace with 1.==rca
  255 |     if(rca==1.)return 1;if(rca<1.)return 1;
      |        ~~~^~~~
csabbg_cmporder.cpp:256:11: warning: CO02: Constant-expression operand should be on the left
  256 |     if(rcd==1)return 1;if(rcd<1)return 1;
      |        ~~~^~~
csabbg_cmporder.cpp:256:11: note: CO02: Replace with 1==rcd
  256 |     if(rcd==1)return 1;if(rcd<1)return 1;
      |        ~~~^~~
csabbg_cmporder.cpp:257:11: warning: CO02: Constant-expression operand should be on the left
  257 |     if(rcd==1.)return 1;if(rcd<1.)return 1;
      |        ~~~^~~~
csabbg_cmporder.cpp:257:11: note: CO02: Replace with 1.==rcd
  257 |     if(rcd==1.)return 1;if(rcd<1.)return 1;
      |        ~~~^~~~
csabbg_cmporder.cpp:282:10: warning: CO01: Non-modifiable operand should be on the left
  282 |     if((a==1)<<(a<1))return 1;
      |         ~^~~
csabbg_cmporder.cpp:282:10: note: CO01: Replace with 1==a
  282 |     if((a==1)<<(a<1))return 1;
      |         ~^~~
csabbg_cmporder.cpp:283:10: warning: CO01: Non-modifiable operand should be on the left
  283 |     if((a==1.)<<(a<1.))return 1;
      |         ~^~~~
csabbg_cmporder.cpp:283:10: note: CO01: Replace with 1.==a
  283 |     if((a==1.)<<(a<1.))return 1;
      |         ~^~~~
csabbg_cmporder.cpp:284:10: warning: CO01: Non-modifiable operand should be on the left
  284 |     if((d==1)<<(d<1))return 1;
      |         ~^~~
csabbg_cmporder.cpp:284:10: note: CO01: Replace with 1==d
  284 |     if((d==1)<<(d<1))return 1;
      |         ~^~~
csabbg_cmporder.cpp:285:10: warning: CO01: Non-modifiable operand should be on the left
  285 |     if((d==1.)<<(d<1.))return 1;
      |         ~^~~~
csabbg_cmporder.cpp:285:10: note: CO01: Replace with 1.==d
  285 |     if((d==1.)<<(d<1.))return 1;
      |         ~^~~~
csabbg_cmporder.cpp:286:11: warning: CO02: Constant-expression operand should be on the left
  286 |     if((ca==1)<<(ca<1))return 1;
      |         ~~^~~
csabbg_cmporder.cpp:286:11: note: CO02: Replace with 1==ca
  286 |     if((ca==1)<<(ca<1))return 1;
      |         ~~^~~
csabbg_cmporder.cpp:287:11: warning: CO02: Constant-expression operand should be on the left
  287 |     if((ca==1.)<<(ca<1.))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:287:11: note: CO02: Replace with 1.==ca
  287 |     if((ca==1.)<<(ca<1.))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:288:11: warning: CO02: Constant-expression operand should be on the left
  288 |     if((cd==1)<<(cd<1))return 1;
      |         ~~^~~
csabbg_cmporder.cpp:288:11: note: CO02: Replace with 1==cd
  288 |     if((cd==1)<<(cd<1))return 1;
      |         ~~^~~
csabbg_cmporder.cpp:289:11: warning: CO02: Constant-expression operand should be on the left
  289 |     if((cd==1.)<<(cd<1.))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:289:11: note: CO02: Replace with 1.==cd
  289 |     if((cd==1.)<<(cd<1.))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:290:12: warning: CO01: Non-modifiable operand should be on the left
  290 |     if((*pa==1)<<(*pa<1))return 1;
      |         ~~~^~~
csabbg_cmporder.cpp:290:12: note: CO01: Replace with 1==*pa
  290 |     if((*pa==1)<<(*pa<1))return 1;
      |         ~~~^~~
csabbg_cmporder.cpp:291:12: warning: CO01: Non-modifiable operand should be on the left
  291 |     if((*pa==1.)<<(*pa<1.))return 1;
      |         ~~~^~~~
csabbg_cmporder.cpp:291:12: note: CO01: Replace with 1.==*pa
  291 |     if((*pa==1.)<<(*pa<1.))return 1;
      |         ~~~^~~~
csabbg_cmporder.cpp:292:12: warning: CO01: Non-modifiable operand should be on the left
  292 |     if((*pd==1)<<(*pd<1))return 1;
      |         ~~~^~~
csabbg_cmporder.cpp:292:12: note: CO01: Replace with 1==*pd
  292 |     if((*pd==1)<<(*pd<1))return 1;
      |         ~~~^~~
csabbg_cmporder.cpp:293:12: warning: CO01: Non-modifiable operand should be on the left
  293 |     if((*pd==1.)<<(*pd<1.))return 1;
      |         ~~~^~~~
csabbg_cmporder.cpp:293:12: note: CO01: Replace with 1.==*pd
  293 |     if((*pd==1.)<<(*pd<1.))return 1;
      |         ~~~^~~~
csabbg_cmporder.cpp:294:13: warning: CO02: Constant-expression operand should be on the left
  294 |     if((*pca==1)<<(*pca<1))return 1;
      |         ~~~~^~~
csabbg_cmporder.cpp:294:13: note: CO02: Replace with 1==*pca
  294 |     if((*pca==1)<<(*pca<1))return 1;
      |         ~~~~^~~
csabbg_cmporder.cpp:295:13: warning: CO02: Constant-expression operand should be on the left
  295 |     if((*pca==1.)<<(*pca<1.))return 1;
      |         ~~~~^~~~
csabbg_cmporder.cpp:295:13: note: CO02: Replace with 1.==*pca
  295 |     if((*pca==1.)<<(*pca<1.))return 1;
      |         ~~~~^~~~
csabbg_cmporder.cpp:296:13: warning: CO02: Constant-expression operand should be on the left
  296 |     if((*pcd==1)<<(*pcd<1))return 1;
      |         ~~~~^~~
csabbg_cmporder.cpp:296:13: note: CO02: Replace with 1==*pcd
  296 |     if((*pcd==1)<<(*pcd<1))return 1;
      |         ~~~~^~~
csabbg_cmporder.cpp:297:13: warning: CO02: Constant-expression operand should be on the left
  297 |     if((*pcd==1.)<<(*pcd<1.))return 1;
      |         ~~~~^~~~
csabbg_cmporder.cpp:297:13: note: CO02: Replace with 1.==*pcd
  297 |     if((*pcd==1.)<<(*pcd<1.))return 1;
      |         ~~~~^~~~
csabbg_cmporder.cpp:298:11: warning: CO01: Non-modifiable operand should be on the left
  298 |     if((ra==1)<<(ra<1))return 1;
      |         ~~^~~
csabbg_cmporder.cpp:298:11: note: CO01: Replace with 1==ra
  298 |     if((ra==1)<<(ra<1))return 1;
      |         ~~^~~
csabbg_cmporder.cpp:299:11: warning: CO01: Non-modifiable operand should be on the left
  299 |     if((ra==1.)<<(ra<1.))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:299:11: note: CO01: Replace with 1.==ra
  299 |     if((ra==1.)<<(ra<1.))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:300:11: warning: CO01: Non-modifiable operand should be on the left
  300 |     if((rd==1)<<(rd<1))return 1;
      |         ~~^~~
csabbg_cmporder.cpp:300:11: note: CO01: Replace with 1==rd
  300 |     if((rd==1)<<(rd<1))return 1;
      |         ~~^~~
csabbg_cmporder.cpp:301:11: warning: CO01: Non-modifiable operand should be on the left
  301 |     if((rd==1.)<<(rd<1.))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:301:11: note: CO01: Replace with 1.==rd
  301 |     if((rd==1.)<<(rd<1.))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:302:12: warning: CO02: Constant-expression operand should be on the left
  302 |     if((rca==1)<<(rca<1))return 1;
      |         ~~~^~~
csabbg_cmporder.cpp:302:12: note: CO02: Replace with 1==rca
  302 |     if((rca==1)<<(rca<1))return 1;
      |         ~~~^~~
csabbg_cmporder.cpp:303:12: warning: CO02: Constant-expression operand should be on the left
  303 |     if((rca==1.)<<(rca<1.))return 1;
      |         ~~~^~~~
csabbg_cmporder.cpp:303:12: note: CO02: Replace with 1.==rca
  303 |     if((rca==1.)<<(rca<1.))return 1;
      |         ~~~^~~~
csabbg_cmporder.cpp:304:12: warning: CO02: Constant-expression operand should be on the left
  304 |     if((rcd==1)<<(rcd<1))return 1;
      |         ~~~^~~
csabbg_cmporder.cpp:304:12: note: CO02: Replace with 1==rcd
  304 |     if((rcd==1)<<(rcd<1))return 1;
      |         ~~~^~~
csabbg_cmporder.cpp:305:12: warning: CO02: Constant-expression operand should be on the left
  305 |     if((rcd==1.)<<(rcd<1.))return 1;
      |         ~~~^~~~
csabbg_cmporder.cpp:305:12: note: CO02: Replace with 1.==rcd
  305 |     if((rcd==1.)<<(rcd<1.))return 1;
      |         ~~~^~~~
csabbg_cmporder.cpp:358:9: warning: CO01: Non-modifiable operand should be on the left
  358 |     if(o==ca)return 1;if(o<ca)return 1;
      |        ~^~~~
csabbg_cmporder.cpp:358:9: note: CO01: Replace with ca==o
  358 |     if(o==ca)return 1;if(o<ca)return 1;
      |        ~^~~~
csabbg_cmporder.cpp:359:10: warning: CO01: Non-modifiable operand should be on the left
  359 |     if(od==ca)return 1;if(od<ca)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:359:10: note: CO01: Replace with ca==od
  359 |     if(od==ca)return 1;if(od<ca)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:360:9: warning: CO01: Non-modifiable operand should be on the left
  360 |     if(o==cd)return 1;if(o<cd)return 1;
      |        ~^~~~
csabbg_cmporder.cpp:360:9: note: CO01: Replace with cd==o
  360 |     if(o==cd)return 1;if(o<cd)return 1;
      |        ~^~~~
csabbg_cmporder.cpp:361:10: warning: CO01: Non-modifiable operand should be on the left
  361 |     if(od==cd)return 1;if(od<cd)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:361:10: note: CO01: Replace with cd==od
  361 |     if(od==cd)return 1;if(od<cd)return 1;
      |        ~~^~~~
csabbg_cmporder.cpp:366:9: warning: CO01: Non-modifiable operand should be on the left
  366 |     if(o==*pca)return 1;if(o<*pca)return 1;
      |        ~^~~~~~
csabbg_cmporder.cpp:366:9: note: CO01: Replace with *pca==o
  366 |     if(o==*pca)return 1;if(o<*pca)return 1;
      |        ~^~~~~~
csabbg_cmporder.cpp:367:10: warning: CO01: Non-modifiable operand should be on the left
  367 |     if(od==*pca)return 1;if(od<*pca)return 1;
      |        ~~^~~~~~
csabbg_cmporder.cpp:367:10: note: CO01: Replace with *pca==od
  367 |     if(od==*pca)return 1;if(od<*pca)return 1;
      |        ~~^~~~~~
csabbg_cmporder.cpp:368:9: warning: CO01: Non-modifiable operand should be on the left
  368 |     if(o==*pcd)return 1;if(o<*pcd)return 1;
      |        ~^~~~~~
csabbg_cmporder.cpp:368:9: note: CO01: Replace with *pcd==o
  368 |     if(o==*pcd)return 1;if(o<*pcd)return 1;
      |        ~^~~~~~
csabbg_cmporder.cpp:369:10: warning: CO01: Non-modifiable operand should be on the left
  369 |     if(od==*pcd)return 1;if(od<*pcd)return 1;
      |        ~~^~~~~~
csabbg_cmporder.cpp:369:10: note: CO01: Replace with *pcd==od
  369 |     if(od==*pcd)return 1;if(od<*pcd)return 1;
      |        ~~^~~~~~
csabbg_cmporder.cpp:374:9: warning: CO01: Non-modifiable operand should be on the left
  374 |     if(o==rca)return 1;if(o<rca)return 1;
      |        ~^~~~~
csabbg_cmporder.cpp:374:9: note: CO01: Replace with rca==o
  374 |     if(o==rca)return 1;if(o<rca)return 1;
      |        ~^~~~~
csabbg_cmporder.cpp:375:10: warning: CO01: Non-modifiable operand should be on the left
  375 |     if(od==rca)return 1;if(od<rca)return 1;
      |        ~~^~~~~
csabbg_cmporder.cpp:375:10: note: CO01: Replace with rca==od
  375 |     if(od==rca)return 1;if(od<rca)return 1;
      |        ~~^~~~~
csabbg_cmporder.cpp:376:9: warning: CO01: Non-modifiable operand should be on the left
  376 |     if(o==rcd)return 1;if(o<rcd)return 1;
      |        ~^~~~~
csabbg_cmporder.cpp:376:9: note: CO01: Replace with rcd==o
  376 |     if(o==rcd)return 1;if(o<rcd)return 1;
      |        ~^~~~~
csabbg_cmporder.cpp:377:10: warning: CO01: Non-modifiable operand should be on the left
  377 |     if(od==rcd)return 1;if(od<rcd)return 1;
      |        ~~^~~~~
csabbg_cmporder.cpp:377:10: note: CO01: Replace with rcd==od
  377 |     if(od==rcd)return 1;if(od<rcd)return 1;
      |        ~~^~~~~
csabbg_cmporder.cpp:406:10: warning: CO01: Non-modifiable operand should be on the left
  406 |     if((o==ca)<<(o<ca))return 1;
      |         ~^~~~
csabbg_cmporder.cpp:406:10: note: CO01: Replace with ca==o
  406 |     if((o==ca)<<(o<ca))return 1;
      |         ~^~~~
csabbg_cmporder.cpp:407:11: warning: CO01: Non-modifiable operand should be on the left
  407 |     if((od==ca)<<(od<ca))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:407:11: note: CO01: Replace with ca==od
  407 |     if((od==ca)<<(od<ca))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:408:10: warning: CO01: Non-modifiable operand should be on the left
  408 |     if((o==cd)<<(o<cd))return 1;
      |         ~^~~~
csabbg_cmporder.cpp:408:10: note: CO01: Replace with cd==o
  408 |     if((o==cd)<<(o<cd))return 1;
      |         ~^~~~
csabbg_cmporder.cpp:409:11: warning: CO01: Non-modifiable operand should be on the left
  409 |     if((od==cd)<<(od<cd))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:409:11: note: CO01: Replace with cd==od
  409 |     if((od==cd)<<(od<cd))return 1;
      |         ~~^~~~
csabbg_cmporder.cpp:414:10: warning: CO01: Non-modifiable operand should be on the left
  414 |     if((o==*pca)<<(o<*pca))return 1;
      |         ~^~~~~~
csabbg_cmporder.cpp:414:10: note: CO01: Replace with *pca==o
  414 |     if((o==*pca)<<(o<*pca))return 1;
      |         ~^~~~~~
csabbg_cmporder.cpp:415:11: warning: CO01: Non-modifiable operand should be on the left
  415 |     if((od==*pca)<<(od<*pca))return 1;
      |         ~~^~~~~~
csabbg_cmporder.cpp:415:11: note: CO01: Replace with *pca==od
  415 |     if((od==*pca)<<(od<*pca))return 1;
      |         ~~^~~~~~
csabbg_cmporder.cpp:416:10: warning: CO01: Non-modifiable operand should be on the left
  416 |     if((o==*pcd)<<(o<*pcd))return 1;
      |         ~^~~~~~
csabbg_cmporder.cpp:416:10: note: CO01: Replace with *pcd==o
  416 |     if((o==*pcd)<<(o<*pcd))return 1;
      |         ~^~~~~~
csabbg_cmporder.cpp:417:11: warning: CO01: Non-modifiable operand should be on the left
  417 |     if((od==*pcd)<<(od<*pcd))return 1;
      |         ~~^~~~~~
csabbg_cmporder.cpp:417:11: note: CO01: Replace with *pcd==od
  417 |     if((od==*pcd)<<(od<*pcd))return 1;
      |         ~~^~~~~~
csabbg_cmporder.cpp:422:10: warning: CO01: Non-modifiable operand should be on the left
  422 |     if((o==rca)<<(o<rca))return 1;
      |         ~^~~~~
csabbg_cmporder.cpp:422:10: note: CO01: Replace with rca==o
  422 |     if((o==rca)<<(o<rca))return 1;
      |         ~^~~~~
csabbg_cmporder.cpp:423:11: warning: CO01: Non-modifiable operand should be on the left
  423 |     if((od==rca)<<(od<rca))return 1;
      |         ~~^~~~~
csabbg_cmporder.cpp:423:11: note: CO01: Replace with rca==od
  423 |     if((od==rca)<<(od<rca))return 1;
      |         ~~^~~~~
csabbg_cmporder.cpp:424:10: warning: CO01: Non-modifiable operand should be on the left
  424 |     if((o==rcd)<<(o<rcd))return 1;
      |         ~^~~~~
csabbg_cmporder.cpp:424:10: note: CO01: Replace with rcd==o
  424 |     if((o==rcd)<<(o<rcd))return 1;
      |         ~^~~~~
csabbg_cmporder.cpp:425:11: warning: CO01: Non-modifiable operand should be on the left
  425 |     if((od==rcd)<<(od<rcd))return 1;
      |         ~~^~~~~
csabbg_cmporder.cpp:425:11: note: CO01: Replace with rcd==od
  425 |     if((od==rcd)<<(od<rcd))return 1;
      |         ~~^~~~~
168 warnings generated.
