csamisc_funcalpha.t.cpp:7:18: warning: FABC01: Function 'f3' not in alphanumeric order
    7 |             void f3();
      |                  ^~
csamisc_funcalpha.t.cpp:8:18: note: FABC01: Next function is 'f2'
    8 |             void f2();
      |                  ^~
csamisc_funcalpha.t.cpp:23:18: warning: FABC01: Function 'a100' not in alphanumeric order
   23 |             void a100();
      |                  ^~~~
csamisc_funcalpha.t.cpp:24:18: note: FABC01: Next function is 'a99'
   24 |             void a99();
      |                  ^~~
csamisc_funcalpha.t.cpp:27:17: warning: FABC01: Function 'f3' not in alphanumeric order
   27 |         void X::f3() { }
      |                 ^~
csamisc_funcalpha.t.cpp:28:17: note: FABC01: Next function is 'f2'
   28 |         void X::f2() { }
      |                 ^~
3 warnings generated.
