nobrace.cpp:8:5: warning: IND01: Possibly mis-indented line
    8 |     a = 1;
      |     ^
nobrace.cpp:8:5: note: IND01: Correct version may be
        a = 1;
nobrace.cpp:12:5: warning: IND01: Possibly mis-indented line
   12 |     a = 1;
      |     ^
nobrace.cpp:12:5: note: IND01: Correct version may be
        a = 1;
nobrace.cpp:15:5: warning: IND01: Possibly mis-indented line
   15 |     a = 1;
      |     ^
nobrace.cpp:15:5: note: IND01: Correct version may be
        a = 1;
nobrace.cpp:18:5: warning: IND01: Possibly mis-indented line
   18 |     a = 1;
      |     ^
nobrace.cpp:18:5: note: IND01: Correct version may be
        a = 1;
nobrace.cpp:20:5: warning: IND01: Possibly mis-indented line
   20 |     a = 0;
      |     ^
nobrace.cpp:20:5: note: IND01: Correct version may be
        a = 0;
nobrace.cpp:23:5: warning: IND01: Possibly mis-indented line
   23 |     a = 1;
      |     ^
nobrace.cpp:23:5: note: IND01: Correct version may be
        a = 1;
nobrace.cpp:26:5: warning: IND01: Possibly mis-indented line
   26 |     a = 1;
      |     ^
nobrace.cpp:26:5: note: IND01: Correct version may be
        a = 1;
7 warnings generated.
