In file included from csamisc_verifysameargumentnames.t.cpp:3:
./csamisc_verifysameargumentnames.t.hpp:22:44: warning: AN01: Parameter name mismatch for 1st parameter 'a'
   22 |         void verifysameargumentnames_g(int a, int);
      |                                            ^
./csamisc_verifysameargumentnames.t.hpp:25:44: note: AN01: The other declaration uses 'b'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
./csamisc_verifysameargumentnames.t.hpp:23:49: warning: AN01: Parameter name mismatch for 2nd parameter 'b'
   23 |         void verifysameargumentnames_g(int, int b);
      |                                                 ^
./csamisc_verifysameargumentnames.t.hpp:25:51: note: AN01: The other declaration uses 'a'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
./csamisc_verifysameargumentnames.t.hpp:24:44: warning: AN01: Parameter name mismatch for 1st parameter 'a'
   24 |         void verifysameargumentnames_g(int a, int b);
      |                                            ^
./csamisc_verifysameargumentnames.t.hpp:25:44: note: AN01: The other declaration uses 'b'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
./csamisc_verifysameargumentnames.t.hpp:24:51: warning: AN01: Parameter name mismatch for 2nd parameter 'b'
   24 |         void verifysameargumentnames_g(int a, int b);
      |                                                   ^
./csamisc_verifysameargumentnames.t.hpp:25:51: note: AN01: The other declaration uses 'a'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
./csamisc_verifysameargumentnames.t.hpp:25:44: warning: AN01: Parameter name mismatch for 1st parameter 'b'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
./csamisc_verifysameargumentnames.t.hpp:24:44: note: AN01: The other declaration uses 'a'
   24 |         void verifysameargumentnames_g(int a, int b);
      |                                            ^
./csamisc_verifysameargumentnames.t.hpp:25:51: warning: AN01: Parameter name mismatch for 2nd parameter 'a'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
./csamisc_verifysameargumentnames.t.hpp:24:51: note: AN01: The other declaration uses 'b'
   24 |         void verifysameargumentnames_g(int a, int b);
      |                                                   ^
./csamisc_verifysameargumentnames.t.hpp:25:51: warning: AN01: Parameter name mismatch for 2nd parameter 'a'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
./csamisc_verifysameargumentnames.t.hpp:23:49: note: AN01: The other declaration uses 'b'
   23 |         void verifysameargumentnames_g(int, int b);
      |                                                 ^
./csamisc_verifysameargumentnames.t.hpp:25:44: warning: AN01: Parameter name mismatch for 1st parameter 'b'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
./csamisc_verifysameargumentnames.t.hpp:22:44: note: AN01: The other declaration uses 'a'
   22 |         void verifysameargumentnames_g(int a, int);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:16:44: warning: AN01: Parameter name mismatch for 1st parameter 'a'
   16 |         void verifysameargumentnames_g(int a, int);
      |                                            ^
In file included from csamisc_verifysameargumentnames.t.cpp:3:
./csamisc_verifysameargumentnames.t.hpp:25:44: note: AN01: The other declaration uses 'b'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:16:44: warning: AN01: Parameter name mismatch for 1st parameter 'a'
   16 |         void verifysameargumentnames_g(int a, int);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:19:44: note: AN01: The other declaration uses 'b'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:17:49: warning: AN01: Parameter name mismatch for 2nd parameter 'b'
   17 |         void verifysameargumentnames_g(int, int b);
      |                                                 ^
In file included from csamisc_verifysameargumentnames.t.cpp:3:
./csamisc_verifysameargumentnames.t.hpp:25:51: note: AN01: The other declaration uses 'a'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
csamisc_verifysameargumentnames.t.cpp:17:49: warning: AN01: Parameter name mismatch for 2nd parameter 'b'
   17 |         void verifysameargumentnames_g(int, int b);
      |                                                 ^
csamisc_verifysameargumentnames.t.cpp:19:51: note: AN01: The other declaration uses 'a'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
csamisc_verifysameargumentnames.t.cpp:18:44: warning: AN01: Parameter name mismatch for 1st parameter 'a'
   18 |         void verifysameargumentnames_g(int a, int b);
      |                                            ^
In file included from csamisc_verifysameargumentnames.t.cpp:3:
./csamisc_verifysameargumentnames.t.hpp:25:44: note: AN01: The other declaration uses 'b'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:18:51: warning: AN01: Parameter name mismatch for 2nd parameter 'b'
   18 |         void verifysameargumentnames_g(int a, int b);
      |                                                   ^
In file included from csamisc_verifysameargumentnames.t.cpp:3:
./csamisc_verifysameargumentnames.t.hpp:25:51: note: AN01: The other declaration uses 'a'
   25 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
csamisc_verifysameargumentnames.t.cpp:18:44: warning: AN01: Parameter name mismatch for 1st parameter 'a'
   18 |         void verifysameargumentnames_g(int a, int b);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:19:44: note: AN01: The other declaration uses 'b'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:18:51: warning: AN01: Parameter name mismatch for 2nd parameter 'b'
   18 |         void verifysameargumentnames_g(int a, int b);
      |                                                   ^
csamisc_verifysameargumentnames.t.cpp:19:51: note: AN01: The other declaration uses 'a'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
csamisc_verifysameargumentnames.t.cpp:19:44: warning: AN01: Parameter name mismatch for 1st parameter 'b'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:18:44: note: AN01: The other declaration uses 'a'
   18 |         void verifysameargumentnames_g(int a, int b);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:19:51: warning: AN01: Parameter name mismatch for 2nd parameter 'a'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
csamisc_verifysameargumentnames.t.cpp:18:51: note: AN01: The other declaration uses 'b'
   18 |         void verifysameargumentnames_g(int a, int b);
      |                                                   ^
csamisc_verifysameargumentnames.t.cpp:19:51: warning: AN01: Parameter name mismatch for 2nd parameter 'a'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
csamisc_verifysameargumentnames.t.cpp:17:49: note: AN01: The other declaration uses 'b'
   17 |         void verifysameargumentnames_g(int, int b);
      |                                                 ^
csamisc_verifysameargumentnames.t.cpp:19:44: warning: AN01: Parameter name mismatch for 1st parameter 'b'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:16:44: note: AN01: The other declaration uses 'a'
   16 |         void verifysameargumentnames_g(int a, int);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:19:44: warning: AN01: Parameter name mismatch for 1st parameter 'b'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
In file included from csamisc_verifysameargumentnames.t.cpp:3:
./csamisc_verifysameargumentnames.t.hpp:24:44: note: AN01: The other declaration uses 'a'
   24 |         void verifysameargumentnames_g(int a, int b);
      |                                            ^
csamisc_verifysameargumentnames.t.cpp:19:51: warning: AN01: Parameter name mismatch for 2nd parameter 'a'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
In file included from csamisc_verifysameargumentnames.t.cpp:3:
./csamisc_verifysameargumentnames.t.hpp:24:51: note: AN01: The other declaration uses 'b'
   24 |         void verifysameargumentnames_g(int a, int b);
      |                                                   ^
csamisc_verifysameargumentnames.t.cpp:19:51: warning: AN01: Parameter name mismatch for 2nd parameter 'a'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                                   ^
In file included from csamisc_verifysameargumentnames.t.cpp:3:
./csamisc_verifysameargumentnames.t.hpp:23:49: note: AN01: The other declaration uses 'b'
   23 |         void verifysameargumentnames_g(int, int b);
      |                                                 ^
csamisc_verifysameargumentnames.t.cpp:19:44: warning: AN01: Parameter name mismatch for 1st parameter 'b'
   19 |         void verifysameargumentnames_g(int b, int a);
      |                                            ^
In file included from csamisc_verifysameargumentnames.t.cpp:3:
./csamisc_verifysameargumentnames.t.hpp:22:44: note: AN01: The other declaration uses 'a'
   22 |         void verifysameargumentnames_g(int a, int);
      |                                            ^
24 warnings generated.
