In file included from csatr_componentprefix.v.cpp:3:
./csatr_componentprefix.v.hpp:19:14: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadEnum' without component prefix
   19 |         enum BadEnum
      |              ^
./csatr_componentprefix.v.hpp:21:13: warning: CP01: Globally visible identifier 'bde_verify::csatr::badBadEnumTag' without component prefix
   21 |             badBadEnumTag
      |             ^
./csatr_componentprefix.v.hpp:24:25: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadTypedef' without component prefix
   24 |         typedef BadEnum BadTypedef;
      |                         ^
./csatr_componentprefix.v.hpp:26:16: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadStruct' without component prefix
   26 |         struct BadStruct
      |                ^
./csatr_componentprefix.v.hpp:36:24: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadStruct1' without component prefix
   36 |         typedef struct BadStruct1
      |                        ^
./csatr_componentprefix.v.hpp:40:11: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadStruct2' without component prefix
   40 |         } BadStruct2;
      |           ^
./csatr_componentprefix.v.hpp:46:11: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadStruct3' without component prefix
   46 |         } BadStruct3;
      |           ^
./csatr_componentprefix.v.hpp:48:15: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadClass' without component prefix
   48 |         class BadClass
      |               ^
./csatr_componentprefix.v.hpp:56:15: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadTemplate' without component prefix
   56 |         class BadTemplate
      |               ^
./csatr_componentprefix.v.hpp:64:13: warning: CP01: Globally visible identifier 'bde_verify::csatr::badTemplate' without component prefix
   64 |         int badTemplate()
      |             ^
./csatr_componentprefix.v.hpp:70:13: warning: CP01: Globally visible identifier 'bde_verify::csatr::badFunction' without component prefix
   70 |         int badFunction()
      |             ^
./csatr_componentprefix.v.hpp:76:13: warning: CP01: Globally visible identifier 'bde_verify::csatr::badVariable' without component prefix
   76 |         int badVariable(0);
      |             ^
./csatr_componentprefix.v.hpp:80:13: warning: CP01: Globally visible identifier 'bde_verify::csatr::badGoodEnumTag' without component prefix
   80 |             badGoodEnumTag,
      |             ^
./csatr_componentprefix.v.hpp:142:16: warning: CP01: Globally visible identifier 'bde_verify::csatr::someVariable' without component prefix
  142 |     extern int someVariable;
      |                ^
./csatr_componentprefix.v.hpp:151:20: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadEnumClass' without component prefix
  151 |         enum class BadEnumClass
      |                    ^
./csatr_componentprefix.v.hpp:153:13: warning: CP01: Globally visible identifier 'bde_verify::csatr::BadEnumClass::badBadEnumClassTag' without component prefix
  153 |             badBadEnumClassTag
      |             ^
./csatr_componentprefix.v.hpp:159:9: warning: CP01: Globally visible identifier 'bde_verify::ComponentPrefixGoodEnumClass::badGoodEnumClassTag' without component prefix
  159 |         badGoodEnumClassTag,
      |         ^
17 warnings generated.
