main.cpp:6:11: warning: PC01: C++ header included within C linkage specification
    6 | #include <cppfile.h>
      |           ^
main.cpp:4:8: note: PC01: C linkage specification here
    4 | extern "C" {
      |        ^
In file included from main.cpp:1:
./cppfile.h:3:13: note: PC01: Declaration with C++ linkage here
    3 | inline void cppfile() { }
      |             ^
main.cpp:8:11: warning: PC01: C++ header included within C linkage specification
    8 | #include <cppfile.h>
      |           ^
main.cpp:4:8: note: PC01: C linkage specification here
    4 | extern "C" {
      |        ^
In file included from main.cpp:1:
./cppfile.h:3:13: note: PC01: Declaration with C++ linkage here
    3 | inline void cppfile() { }
      |             ^
main.cpp:11:11: warning: PC01: C++ system header included within C linkage specification
   11 | #include <string>
      |           ^
main.cpp:4:8: note: PC01: C linkage specification here
    4 | extern "C" {
      |        ^
3 warnings generated.
