array-argument.cpp:2:13: warning: AA01: Pointer parameter disguised as sized array
    2 | void f2(int a[10]);
      |             ^
array-argument.cpp:4:13: warning: AA01: Pointer parameter disguised as sized array
    4 | void f4(int [10]);
      |             ^
array-argument.cpp:11:33: warning: AA01: Pointer parameter disguised as sized array
   11 | template <typename T> void t2(T a[10]);
      |                                 ^
array-argument.cpp:13:33: warning: AA01: Pointer parameter disguised as sized array
   13 | template <typename T> void t4(T [10]);
      |                                 ^
4 warnings generated.
