csamisc_shortcompare.cpp:23:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   23 |            ss() != us() ||
      |            ^
csamisc_shortcompare.cpp:28:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   28 |            ss() < us() ||
      |            ^
csamisc_shortcompare.cpp:31:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   31 |            ss() <= us() ||
      |            ^
csamisc_shortcompare.cpp:34:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   34 |            ss() == us() ||
      |            ^
csamisc_shortcompare.cpp:37:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   37 |            ss() > us() ||
      |            ^
csamisc_shortcompare.cpp:39:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   39 |            ss() >= us() ||
      |            ^
csamisc_shortcompare.cpp:42:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   42 |            us() != ss() ||
      |            ^
csamisc_shortcompare.cpp:46:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   46 |            us() < ss() ||
      |            ^
csamisc_shortcompare.cpp:49:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   49 |            us() <= ss() ||
      |            ^
csamisc_shortcompare.cpp:52:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   52 |            us() == ss() ||
      |            ^
csamisc_shortcompare.cpp:55:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   55 |            us() > ss() ||
      |            ^
csamisc_shortcompare.cpp:58:12: warning: US01: Comparison between signed and unsigned short may cause unexpected behavior
   58 |            us() >= ss() ||
      |            ^
12 warnings generated.
