csatr_globaltypeonlyinsource.v.cpp:12:33: warning: TR11: Globally visible type 'bde_verify::csatr::s_extern' should be defined in header.
   12 |                          struct s_extern { int member; };
      |                                 ^
csatr_globaltypeonlyinsource.v.cpp:17:33: warning: TR11: Globally visible type 'bde_verify::csatr::c_extern' should be defined in header.
   17 |                          class  c_extern { int member; };
      |                                 ^
csatr_globaltypeonlyinsource.v.cpp:22:33: warning: TR11: Globally visible type 'bde_verify::csatr::e_extern' should be defined in header.
   22 |                          enum   e_extern { e2_member   };
      |                                 ^
3 warnings generated.
