In file included from csabbg_allocatorforward.t.cpp:3:
./csabbg_allocatorforward.t.hpp:34:15: warning: AT02: Class 'allocatorforward_alloc_used' uses allocators but does not have an allocator trait
   34 |         class allocatorforward_alloc_used;
      |               ^
./csabbg_allocatorforward.t.hpp:34:15: warning: AP02: Class 'allocatorforward_alloc_used' needs d_allocator_p member
./csabbg_allocatorforward.t.hpp:34:15: warning: AL01: Class 'allocatorforward_alloc_used' needs allocator() method
./csabbg_allocatorforward.t.hpp:47:27: warning: AC02: Class 'allocatorforward_alloc_used' implicit copy constructor is not allocator-aware
   47 | class bde_verify::csabbg::allocatorforward_alloc_used
      |                           ^
csabbg_allocatorforward.t.cpp:15:19: warning: AT02: Class 'test' uses allocators but does not have an allocator trait
   15 |             class test:
      |                   ^
csabbg_allocatorforward.t.cpp:15:19: warning: AP02: Class 'test' needs d_allocator_p member
csabbg_allocatorforward.t.cpp:15:19: warning: AL01: Class 'test' needs allocator() method
csabbg_allocatorforward.t.cpp:15:19: warning: AC02: Class 'test' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:45:5: warning: MA01: Allocator not passed to base class bde_verify::csabbg::allocatorforward_alloc_used
   45 |     allocatorforward_alloc_used(i),
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
csabbg_allocatorforward.t.cpp:46:5: warning: MA02: Allocator not passed to member used0_
   46 |     used0_(i),
      |     ^~~~~~~~~
csabbg_allocatorforward.t.cpp:44:70: warning: MA02: Allocator not passed to member used2_
   44 | bde_verify::csabbg::test::test(int i, BloombergLP::bslma::Allocator* alloc):
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
csabbg_allocatorforward.t.cpp:70:5: warning: MA02: Allocator not passed to member used0_
   70 |     used0_(bde_verify::csabbg::dummy(alloc)),
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
csabbg_allocatorforward.t.cpp:85:20: warning: AT02: Class 'tbase' uses allocators but does not have an allocator trait
   85 |             struct tbase
      |                    ^
csabbg_allocatorforward.t.cpp:85:20: warning: AP02: Class 'tbase' needs d_allocator_p member
csabbg_allocatorforward.t.cpp:85:20: warning: AL01: Class 'tbase' needs allocator() method
csabbg_allocatorforward.t.cpp:88:62: warning: MA02: Allocator not passed to member used0_
   88 |                 explicit tbase(BloombergLP::bslma::Allocator*);
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
csabbg_allocatorforward.t.cpp:85:20: warning: AC02: Class 'tbase' implicit copy constructor is not allocator-aware
   85 |             struct tbase
      |                    ^
csabbg_allocatorforward.t.cpp:130:24: warning: AT02: Class 'M' uses allocators but does not have an allocator trait
  130 |                 struct M { M(BloombergLP::bslma::Allocator*) {} };
      |                        ^
csabbg_allocatorforward.t.cpp:130:24: warning: AP02: Class 'M' needs d_allocator_p member
csabbg_allocatorforward.t.cpp:130:24: warning: AL01: Class 'M' needs allocator() method
csabbg_allocatorforward.t.cpp:132:24: warning: AT02: Class 'S' uses allocators but does not have an allocator trait
  132 |                 struct S { S(const T*) {} S(const T*, const A&) {} };
      |                        ^
csabbg_allocatorforward.t.cpp:132:24: warning: AP02: Class 'S' needs d_allocator_p member
csabbg_allocatorforward.t.cpp:132:24: warning: AL01: Class 'S' needs allocator() method
csabbg_allocatorforward.t.cpp:132:24: warning: AC02: Class 'S' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:133:28: warning: AC02: Class 'M' implicit copy constructor is not allocator-aware
  133 |             template class M<char>;  // TBD should not be needed
      |                            ^
csabbg_allocatorforward.t.cpp:136:53: warning: MA02: Allocator not passed to member s
  136 |                 C(BloombergLP::bslma::Allocator*) : s("") { }
      |                                                     ^~~~~
csabbg_allocatorforward.t.cpp:134:20: warning: AT02: Class 'C' uses allocators but does not have an allocator trait
  134 |             struct C {
      |                    ^
csabbg_allocatorforward.t.cpp:134:20: warning: AP02: Class 'C' needs d_allocator_p member
csabbg_allocatorforward.t.cpp:134:20: warning: AL01: Class 'C' needs allocator() method
csabbg_allocatorforward.t.cpp:134:20: warning: AC02: Class 'C' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:148:16: warning: AT02: Class 'not_alloc' uses allocators but does not have an allocator trait
  148 |         struct not_alloc {
      |                ^
csabbg_allocatorforward.t.cpp:148:16: warning: AP02: Class 'not_alloc' needs d_allocator_p member
csabbg_allocatorforward.t.cpp:148:16: warning: AL01: Class 'not_alloc' needs allocator() method
csabbg_allocatorforward.t.cpp:148:16: warning: AC02: Class 'not_alloc' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:154:15: warning: MA02: Allocator not passed to member member
  154 |             : member(na) { }
      |               ^~~~~~~~~~
csabbg_allocatorforward.t.cpp:151:16: warning: AP02: Class 'object' needs d_allocator_p member
  151 |         struct object {
      |                ^
csabbg_allocatorforward.t.cpp:151:16: warning: AL01: Class 'object' needs allocator() method
csabbg_allocatorforward.t.cpp:151:16: warning: AC02: Class 'object' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:201:8: warning: AP02: Class 'alloc_a' needs d_allocator_p member
  201 | struct alloc_a {
      |        ^
csabbg_allocatorforward.t.cpp:201:8: warning: AL01: Class 'alloc_a' needs allocator() method
csabbg_allocatorforward.t.cpp:201:8: warning: AC02: Class 'alloc_a' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:206:8: warning: AP02: Class 'alloc_b' needs d_allocator_p member
  206 | struct alloc_b {
      |        ^
csabbg_allocatorforward.t.cpp:206:8: warning: AL01: Class 'alloc_b' needs allocator() method
csabbg_allocatorforward.t.cpp:206:8: warning: AC02: Class 'alloc_b' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:211:8: warning: AP02: Class 'alloc_c' needs d_allocator_p member
  211 | struct alloc_c {
      |        ^
csabbg_allocatorforward.t.cpp:211:8: warning: AL01: Class 'alloc_c' needs allocator() method
csabbg_allocatorforward.t.cpp:211:8: warning: AC02: Class 'alloc_c' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:215:8: warning: AT02: Class 'alloc_d' uses allocators but does not have an allocator trait
  215 | struct alloc_d {
      |        ^
csabbg_allocatorforward.t.cpp:215:8: warning: AP02: Class 'alloc_d' needs d_allocator_p member
csabbg_allocatorforward.t.cpp:215:8: warning: AL01: Class 'alloc_d' needs allocator() method
csabbg_allocatorforward.t.cpp:215:8: warning: AC02: Class 'alloc_d' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:219:8: warning: AP02: Class 'alloc_e' needs d_allocator_p member
  219 | struct alloc_e {
      |        ^
csabbg_allocatorforward.t.cpp:219:8: warning: AL01: Class 'alloc_e' needs allocator() method
csabbg_allocatorforward.t.cpp:219:8: warning: AC02: Class 'alloc_e' implicit copy constructor is not allocator-aware
csabbg_allocatorforward.t.cpp:230:8: warning: AP02: Class 'alloc_g' needs d_allocator_p member
  230 | struct alloc_g {
      |        ^
csabbg_allocatorforward.t.cpp:230:8: warning: AL01: Class 'alloc_g' needs allocator() method
csabbg_allocatorforward.t.cpp:240:8: warning: AP02: Class 'alloc_i' needs d_allocator_p member
  240 | struct alloc_i {
      |        ^
csabbg_allocatorforward.t.cpp:240:8: warning: AL01: Class 'alloc_i' needs allocator() method
csabbg_allocatorforward.t.cpp:246:8: warning: AP02: Class 'alloc_j' needs d_allocator_p member
  246 | struct alloc_j {
      |        ^
csabbg_allocatorforward.t.cpp:246:8: warning: AL01: Class 'alloc_j' needs allocator() method
csabbg_allocatorforward.t.cpp:251:16: warning: AC02: Class 'alloc_j' implicit copy constructor is not allocator-aware
  251 | template class alloc_j<int>;
      |                ^
csabbg_allocatorforward.t.cpp:254:8: warning: AP02: Class 'alloc_k' needs d_allocator_p member
  254 | struct alloc_k {
      |        ^
csabbg_allocatorforward.t.cpp:254:8: warning: AL01: Class 'alloc_k' needs allocator() method
csabbg_allocatorforward.t.cpp:266:8: warning: AP02: Class 'alloc_m' needs d_allocator_p member
  266 | struct alloc_m {
      |        ^
csabbg_allocatorforward.t.cpp:266:8: warning: AL01: Class 'alloc_m' needs allocator() method
csabbg_allocatorforward.t.cpp:271:16: warning: AC02: Class 'alloc_m' implicit copy constructor is not allocator-aware
  271 | template class alloc_m<int>;
      |                ^
csabbg_allocatorforward.t.cpp:282:8: warning: AT02: Class 'alloc_o' uses allocators but does not have an allocator trait
  282 | struct alloc_o {
      |        ^
csabbg_allocatorforward.t.cpp:282:8: warning: AP02: Class 'alloc_o' needs d_allocator_p member
csabbg_allocatorforward.t.cpp:282:8: warning: AL01: Class 'alloc_o' needs allocator() method
csabbg_allocatorforward.t.cpp:287:8: warning: AT02: Class 'alloc_p' uses allocators but does not have an allocator trait
  287 | struct alloc_p {
      |        ^
csabbg_allocatorforward.t.cpp:287:8: warning: AP02: Class 'alloc_p' needs d_allocator_p member
csabbg_allocatorforward.t.cpp:287:8: warning: AL01: Class 'alloc_p' needs allocator() method
csabbg_allocatorforward.t.cpp:291:16: warning: AC02: Class 'alloc_p' implicit copy constructor is not allocator-aware
  291 | template class alloc_p<int>;
      |                ^
csabbg_allocatorforward.t.cpp:177:22: warning: AM01: Allocator argument initializes non-allocator parameter 1 ('na') of type 'not_alloc' rather than allocator parameter 2
  177 |             object o(a);
      |                      ^
csabbg_allocatorforward.t.cpp:182:17: warning: AR01: Type using allocator is returned by value
  182 |                 return o;
      |                 ^
csabbg_allocatorforward.t.cpp:184:17: warning: AR01: Type using allocator is returned by value
  184 |                 return object(o);
      |                 ^
csabbg_allocatorforward.t.cpp:313:29: warning: GA01: Variable with global storage must be initialized with non-default allocator
  313 | bde_verify::csabbg::alloc_a a{};
      |                             ^
csabbg_allocatorforward.t.cpp:314:29: warning: GA01: Variable with global storage must be initialized with non-default allocator
  314 | bde_verify::csabbg::alloc_a b{0};
      |                             ^
csabbg_allocatorforward.t.cpp:315:29: warning: GA01: Variable with global storage must be initialized with non-default allocator
  315 | bde_verify::csabbg::alloc_a c[2];
      |                             ^
csabbg_allocatorforward.t.cpp:316:29: warning: GA01: Variable with global storage must be initialized with non-default allocator
  316 | bde_verify::csabbg::alloc_a d[2][2];
      |                             ^
80 warnings generated.
