csamisc_swapab.t.cpp:8:19: warning: SWAB01: First parameter of 'swap' should be named 'a'
    8 |         void swap(int *x, int *y);
      |                   ^~~~~~
csamisc_swapab.t.cpp:8:27: warning: SWAB01: Second parameter of 'swap' should be named 'b'
    8 |         void swap(int *x, int *y);
      |                           ^~~~~~
csamisc_swapab.t.cpp:9:19: warning: SWAB01: First parameter of 'swap' should be named 'a'
    9 |         void swap(int *x, int *b);
      |                   ^~~~~~
csamisc_swapab.t.cpp:10:27: warning: SWAB01: Second parameter of 'swap' should be named 'b'
   10 |         void swap(int *a, int *y);
      |                           ^~~~~~
csamisc_swapab.t.cpp:12:19: warning: SWAB01: First parameter of 'swap' should be named 'a'
   12 |         void swap(int &x, int &y);
      |                   ^~~~~~
csamisc_swapab.t.cpp:12:27: warning: SWAB01: Second parameter of 'swap' should be named 'b'
   12 |         void swap(int &x, int &y);
      |                           ^~~~~~
csamisc_swapab.t.cpp:13:19: warning: SWAB01: First parameter of 'swap' should be named 'a'
   13 |         void swap(int &x, int &b);
      |                   ^~~~~~
csamisc_swapab.t.cpp:14:27: warning: SWAB01: Second parameter of 'swap' should be named 'b'
   14 |         void swap(int &a, int &y);
      |                           ^~~~~~
csamisc_swapab.t.cpp:27:39: warning: SWAB01: First parameter of 'swap' should be named 'a'
   27 |         template <class SS> void swap(SS *x, SS *y);
      |                                       ^~~~~
csamisc_swapab.t.cpp:27:46: warning: SWAB01: Second parameter of 'swap' should be named 'b'
   27 |         template <class SS> void swap(SS *x, SS *y);
      |                                              ^~~~~
csamisc_swapab.t.cpp:28:39: warning: SWAB01: First parameter of 'swap' should be named 'a'
   28 |         template <class SS> void swap(SS *x, SS *b);
      |                                       ^~~~~
csamisc_swapab.t.cpp:29:46: warning: SWAB01: Second parameter of 'swap' should be named 'b'
   29 |         template <class SS> void swap(SS *a, SS *y);
      |                                              ^~~~~
csamisc_swapab.t.cpp:31:39: warning: SWAB01: First parameter of 'swap' should be named 'a'
   31 |         template <class SS> void swap(SS &x, SS &y);
      |                                       ^~~~~
csamisc_swapab.t.cpp:31:46: warning: SWAB01: Second parameter of 'swap' should be named 'b'
   31 |         template <class SS> void swap(SS &x, SS &y);
      |                                              ^~~~~
csamisc_swapab.t.cpp:32:39: warning: SWAB01: First parameter of 'swap' should be named 'a'
   32 |         template <class SS> void swap(SS &x, SS &b);
      |                                       ^~~~~
csamisc_swapab.t.cpp:33:46: warning: SWAB01: Second parameter of 'swap' should be named 'b'
   33 |         template <class SS> void swap(SS &a, SS &y);
      |                                              ^~~~~
16 warnings generated.
