In file included from csatr_friendship.t.cpp:3:
./csatr_friendship.t.hpp:36:13: warning: TR19: Friendship to a class can only be granted within a component
   36 |             friend class bde_verify::csamisc::BadGroup;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_friendship.t.hpp:37:13: warning: TR19: Friendship to a class can only be granted within a component
   37 |             friend class bde_verify::csatr::BadPackage;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_friendship.t.hpp:38:13: warning: TR19: Friendship to a class can only be granted within a component
   38 |             friend class bde_verify::csatr::BadExtern;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_friendship.t.hpp:39:13: warning: TR19: Friendship to a method can only be granted within a component
   39 |             friend void bde_verify::csatr::BadExtern::f() const;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_friendship.t.hpp:40:13: warning: TR19: Friendship to a class can only be granted within a component
   40 |             friend class bde_verify::csatr::BadExtern::Nested;
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_friendship.t.hpp:43:32: warning: TR19: Friendship to a class template can only be granted within a component
   43 |             template <class T> friend class BadPackageTemplate;
      |             ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_friendship.t.hpp:45:13: warning: TR19: Friendship to a function can only be granted within a component
   45 |             friend void bde_verify::csatr::operator+ (BadExtern const&);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_friendship.t.hpp:47:13: warning: TR19: Friendship to a function template can only be granted within a component
   46 |             template <class T>
      |             ~~~~~~~~~~~~~~~~~~
   47 |             friend void bde_verify::csatr::operator+ (BadExtern const&, T);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_friendship.t.hpp:54:13: warning: TR19: Friendship to a function template can only be granted within a component
   53 |             template <class T>
      |             ~~~~~~~~~~~~~~~~~~
   54 |             friend void BadExtern::g(T);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
9 warnings generated.
