h.cpp:16:15: warning: MA02: Allocator not passed to member d_fields
   16 |             : d_fields(fields) {  // <--- allocator not forwarded
      |               ^~~~~~~~~~~~~~~~
h.cpp:9:11: warning: AL01: Class 'Functor' needs allocator() method
    9 |     class Functor {
      |           ^
h.cpp:19:15: warning: MA02: Allocator not passed to member d_fields
   19 |             : d_fields(other.d_fields) {  // <--- allocator not forwarded
      |               ^~~~~~~~~~~~~~~~~~~~~~~~
3 warnings generated.
