In file included from testnotinmain.t.cpp:85:
./testnotinmain.h:15:24: warning: TP27: Method not called in test driver
   15 |     template <class A> F();
      |                        ^
./testnotinmain.h:16:24: warning: TP27: Method not called in test driver
   16 |     template <class A> F(const A&);
      |                        ^
./testnotinmain.h:18:29: warning: TP27: Method not called in test driver
   18 |     template <class A> void H() { }
      |                             ^
testnotinmain.t.cpp:75:14: warning: TP27: Method not called in test driver
   75 |         void h();
      |              ^
testnotinmain.t.cpp:81:14: warning: TP27: Method not called in test driver
   81 |         void k();
      |              ^
testnotinmain.t.cpp:15:1: warning: TP26: Tested classes have 3 functions named 'F' but the test plan has none
   15 | // [ 1] void joe<T>::f();
      | ^
testnotinmain.t.cpp:15:1: warning: TP26: Tested classes have a function named 'H' but the test plan has none
7 warnings generated.
