In file included from sections.cpp:1:
./sections.h:5:10: warning: KS00: Declaration not preceded by section tag comment
    5 |     void accessor_0() const;
      |          ^
./sections.h:6:10: warning: KS00: Declaration not preceded by section tag comment
    6 |     void manipulator_0();
      |          ^
./sections.h:7:10: warning: KS00: Declaration not preceded by section tag comment
    7 |     void aspect_0();
      |          ^
./sections.h:8:16: warning: KS00: Declaration not preceded by section tag comment
    8 |     static int s_class_data_0;
      |                ^
./sections.h:9:17: warning: KS00: Declaration not preceded by section tag comment
    9 |     static void s_class_method_0();
      |                 ^
./sections.h:10:22: warning: KS00: Declaration not preceded by section tag comment
   10 |     static const int s_CONSTANT_0 = 7;
      |                      ^
./sections.h:11:5: warning: KS00: Declaration not preceded by section tag comment
   11 |     X(Z<0>);
      |     ^
./sections.h:12:8: warning: KS00: Declaration not preceded by section tag comment
   12 |     X& operator=(Z<0>);
      |        ^
./sections.h:13:9: warning: KS00: Declaration not preceded by section tag comment
   13 |     int d_data_0;
      |         ^
./sections.h:14:17: warning: KS00: Declaration not preceded by section tag comment
   14 |     typedef int Type_0;
      |                 ^
./sections.h:15:5: warning: KS00: Declaration not preceded by section tag comment
   15 |     operator Z<0>();
      |     ^
./sections.h:16:5: warning: KS00: Declaration not preceded by section tag comment
   16 |     operator Z<0>() const;
      |     ^
./sections.h:20:5: warning: KS01: Tag requires public declaration
   20 |     X();
      |     ^
./sections.h:18:1: note: KS01: Tag is here
   18 | // CREATORS
      | ^
./sections.h:21:5: warning: KS01: Tag requires public declaration
   21 |     ~X();
      |     ^
./sections.h:18:1: note: KS01: Tag is here
   18 | // CREATORS
      | ^
./sections.h:31:10: warning: KS01: Tag requires public declaration
   31 |     void accessor_26() const;
      |          ^
./sections.h:29:1: note: KS01: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:32:10: warning: KS07: Tag requires const method declaration
   32 |     void manipulator_26();
      |          ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:33:10: warning: KS07: Tag requires const method declaration
   33 |     void aspect_26();
      |          ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:34:16: warning: KS07: Tag requires const method declaration
   34 |     static int s_class_data_26;
      |                ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:35:17: warning: KS07: Tag requires const method declaration
   35 |     static void s_class_method_26();
      |                 ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:36:22: warning: KS07: Tag requires const method declaration
   36 |     static const int s_CONSTANT_26 = 7;
      |                      ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:37:5: warning: KS09: Constructor or destructor requires CREATORS tag
   37 |     X(Z<26>);
      |     ^
./sections.h:29:1: note: KS09: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:38:8: warning: KS07: Tag requires const method declaration
   38 |     X& operator=(Z<26>);
      |        ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:39:9: warning: KS07: Tag requires const method declaration
   39 |     int d_data_26;
      |         ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:40:17: warning: KS07: Tag requires const method declaration
   40 |     typedef int Type_26;
      |                 ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:41:5: warning: KS07: Tag requires const method declaration
   41 |     operator Z<26>();
      |     ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:42:5: warning: KS01: Tag requires public declaration
   42 |     operator Z<26>() const;
      |     ^
./sections.h:29:1: note: KS01: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:45:10: warning: KS07: Tag requires const method declaration
   45 |     void manipulator_25();
      |          ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:46:10: warning: KS07: Tag requires const method declaration
   46 |     void aspect_25();
      |          ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:47:16: warning: KS07: Tag requires const method declaration
   47 |     static int s_class_data_25;
      |                ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:48:17: warning: KS07: Tag requires const method declaration
   48 |     static void s_class_method_25();
      |                 ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:49:22: warning: KS07: Tag requires const method declaration
   49 |     static const int s_CONSTANT_25 = 7;
      |                      ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:50:5: warning: KS09: Constructor or destructor requires CREATORS tag
   50 |     X(Z<25>);
      |     ^
./sections.h:29:1: note: KS09: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:51:8: warning: KS07: Tag requires const method declaration
   51 |     X& operator=(Z<25>);
      |        ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:52:9: warning: KS07: Tag requires const method declaration
   52 |     int d_data_25;
      |         ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:53:17: warning: KS07: Tag requires const method declaration
   53 |     typedef int Type_25;
      |                 ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:54:5: warning: KS07: Tag requires const method declaration
   54 |     operator Z<25>();
      |     ^
./sections.h:29:1: note: KS07: Tag is here
   29 | // ACCESSORS
      | ^
./sections.h:59:10: warning: KS01: Tag requires public declaration
   59 |     void accessor_24() const;
      |          ^
./sections.h:57:1: note: KS01: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:60:10: warning: KS01: Tag requires public declaration
   60 |     void manipulator_24();
      |          ^
./sections.h:57:1: note: KS01: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:61:10: warning: KS01: Tag requires public declaration
   61 |     void aspect_24();
      |          ^
./sections.h:57:1: note: KS01: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:62:16: warning: KS03: Tag requires function declaration
   62 |     static int s_class_data_24;
      |                ^
./sections.h:57:1: note: KS03: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:63:17: warning: KS01: Tag requires public declaration
   63 |     static void s_class_method_24();
      |                 ^
./sections.h:57:1: note: KS01: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:64:22: warning: KS03: Tag requires function declaration
   64 |     static const int s_CONSTANT_24 = 7;
      |                      ^
./sections.h:57:1: note: KS03: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:65:5: warning: KS09: Constructor or destructor requires CREATORS tag
   65 |     X(Z<24>);
      |     ^
./sections.h:57:1: note: KS09: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:66:8: warning: KS01: Tag requires public declaration
   66 |     X& operator=(Z<24>);
      |        ^
./sections.h:57:1: note: KS01: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:67:9: warning: KS03: Tag requires function declaration
   67 |     int d_data_24;
      |         ^
./sections.h:57:1: note: KS03: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:68:17: warning: KS03: Tag requires function declaration
   68 |     typedef int Type_24;
      |                 ^
./sections.h:57:1: note: KS03: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:69:5: warning: KS01: Tag requires public declaration
   69 |     operator Z<24>();
      |     ^
./sections.h:57:1: note: KS01: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:70:5: warning: KS01: Tag requires public declaration
   70 |     operator Z<24>() const;
      |     ^
./sections.h:57:1: note: KS01: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:75:16: warning: KS03: Tag requires function declaration
   75 |     static int s_class_data_23;
      |                ^
./sections.h:57:1: note: KS03: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:77:22: warning: KS03: Tag requires function declaration
   77 |     static const int s_CONSTANT_23 = 7;
      |                      ^
./sections.h:57:1: note: KS03: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:78:5: warning: KS09: Constructor or destructor requires CREATORS tag
   78 |     X(Z<23>);
      |     ^
./sections.h:57:1: note: KS09: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:80:9: warning: KS03: Tag requires function declaration
   80 |     int d_data_23;
      |         ^
./sections.h:57:1: note: KS03: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:81:17: warning: KS03: Tag requires function declaration
   81 |     typedef int Type_23;
      |                 ^
./sections.h:57:1: note: KS03: Tag is here
   57 | // ASPECTS
      | ^
./sections.h:87:10: warning: KS05: Tag requires static data field declaration
   87 |     void accessor_22() const;
      |          ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:88:10: warning: KS05: Tag requires static data field declaration
   88 |     void manipulator_22();
      |          ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:89:10: warning: KS05: Tag requires static data field declaration
   89 |     void aspect_22();
      |          ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:91:17: warning: KS05: Tag requires static data field declaration
   91 |     static void s_class_method_22();
      |                 ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:93:5: warning: KS09: Constructor or destructor requires CREATORS tag
   93 |     X(Z<22>);
      |     ^
./sections.h:85:1: note: KS09: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:94:8: warning: KS05: Tag requires static data field declaration
   94 |     X& operator=(Z<22>);
      |        ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:95:9: warning: KS05: Tag requires static data field declaration
   95 |     int d_data_22;
      |         ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:96:17: warning: KS05: Tag requires static data field declaration
   96 |     typedef int Type_22;
      |                 ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:97:5: warning: KS05: Tag requires static data field declaration
   97 |     operator Z<22>();
      |     ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:98:5: warning: KS05: Tag requires static data field declaration
   98 |     operator Z<22>() const;
      |     ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:100:10: warning: KS05: Tag requires static data field declaration
  100 |     void accessor_21() const;
      |          ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:101:10: warning: KS05: Tag requires static data field declaration
  101 |     void manipulator_21();
      |          ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:102:10: warning: KS05: Tag requires static data field declaration
  102 |     void aspect_21();
      |          ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:103:16: warning: KS02: Tag implicitly requires private declaration
  103 |     static int s_class_data_21;
      |                ^
./sections.h:85:1: note: KS02: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:104:17: warning: KS05: Tag requires static data field declaration
  104 |     static void s_class_method_21();
      |                 ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:105:22: warning: KS02: Tag implicitly requires private declaration
  105 |     static const int s_CONSTANT_21 = 7;
      |                      ^
./sections.h:85:1: note: KS02: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:106:5: warning: KS09: Constructor or destructor requires CREATORS tag
  106 |     X(Z<21>);
      |     ^
./sections.h:85:1: note: KS09: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:107:8: warning: KS05: Tag requires static data field declaration
  107 |     X& operator=(Z<21>);
      |        ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:108:9: warning: KS05: Tag requires static data field declaration
  108 |     int d_data_21;
      |         ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:109:17: warning: KS05: Tag requires static data field declaration
  109 |     typedef int Type_21;
      |                 ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:110:5: warning: KS05: Tag requires static data field declaration
  110 |     operator Z<21>();
      |     ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:111:5: warning: KS05: Tag requires static data field declaration
  111 |     operator Z<21>() const;
      |     ^
./sections.h:85:1: note: KS05: Tag is here
   85 | // CLASS DATA
      | ^
./sections.h:115:10: warning: KS11: Tag requires static method declaration
  115 |     void accessor_19() const;
      |          ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:116:10: warning: KS11: Tag requires static method declaration
  116 |     void manipulator_19();
      |          ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:117:10: warning: KS11: Tag requires static method declaration
  117 |     void aspect_19();
      |          ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:118:16: warning: KS11: Tag requires static method declaration
  118 |     static int s_class_data_19;
      |                ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:119:17: warning: KS01: Tag requires public declaration
  119 |     static void s_class_method_19();
      |                 ^
./sections.h:113:1: note: KS01: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:120:22: warning: KS11: Tag requires static method declaration
  120 |     static const int s_CONSTANT_19 = 7;
      |                      ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:121:5: warning: KS09: Constructor or destructor requires CREATORS tag
  121 |     X(Z<19>);
      |     ^
./sections.h:113:1: note: KS09: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:122:8: warning: KS11: Tag requires static method declaration
  122 |     X& operator=(Z<19>);
      |        ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:123:9: warning: KS11: Tag requires static method declaration
  123 |     int d_data_19;
      |         ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:124:17: warning: KS11: Tag requires static method declaration
  124 |     typedef int Type_19;
      |                 ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:125:5: warning: KS11: Tag requires static method declaration
  125 |     operator Z<19>();
      |     ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:126:5: warning: KS11: Tag requires static method declaration
  126 |     operator Z<19>() const;
      |     ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:128:10: warning: KS11: Tag requires static method declaration
  128 |     void accessor_18() const;
      |          ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:129:10: warning: KS11: Tag requires static method declaration
  129 |     void manipulator_18();
      |          ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:130:10: warning: KS11: Tag requires static method declaration
  130 |     void aspect_18();
      |          ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:131:16: warning: KS11: Tag requires static method declaration
  131 |     static int s_class_data_18;
      |                ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:133:22: warning: KS11: Tag requires static method declaration
  133 |     static const int s_CONSTANT_18 = 7;
      |                      ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:134:5: warning: KS09: Constructor or destructor requires CREATORS tag
  134 |     X(Z<18>);
      |     ^
./sections.h:113:1: note: KS09: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:135:8: warning: KS11: Tag requires static method declaration
  135 |     X& operator=(Z<18>);
      |        ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:136:9: warning: KS11: Tag requires static method declaration
  136 |     int d_data_18;
      |         ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:137:17: warning: KS11: Tag requires static method declaration
  137 |     typedef int Type_18;
      |                 ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:138:5: warning: KS11: Tag requires static method declaration
  138 |     operator Z<18>();
      |     ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:139:5: warning: KS11: Tag requires static method declaration
  139 |     operator Z<18>() const;
      |     ^
./sections.h:113:1: note: KS11: Tag is here
  113 | // CLASS METHODS
      | ^
./sections.h:143:10: warning: KS10: Tag requires constant data declaration
  143 |     void accessor_17() const;
      |          ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:144:10: warning: KS10: Tag requires constant data declaration
  144 |     void manipulator_17();
      |          ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:145:10: warning: KS10: Tag requires constant data declaration
  145 |     void aspect_17();
      |          ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:146:16: warning: KS10: Tag requires constant data declaration
  146 |     static int s_class_data_17;
      |                ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:147:17: warning: KS10: Tag requires constant data declaration
  147 |     static void s_class_method_17();
      |                 ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:148:22: warning: KS01: Tag requires public declaration
  148 |     static const int s_CONSTANT_17 = 7;
      |                      ^
./sections.h:141:1: note: KS01: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:149:5: warning: KS09: Constructor or destructor requires CREATORS tag
  149 |     X(Z<17>);
      |     ^
./sections.h:141:1: note: KS09: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:150:8: warning: KS10: Tag requires constant data declaration
  150 |     X& operator=(Z<17>);
      |        ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:151:9: warning: KS10: Tag requires constant data declaration
  151 |     int d_data_17;
      |         ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:152:17: warning: KS10: Tag requires constant data declaration
  152 |     typedef int Type_17;
      |                 ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:153:5: warning: KS10: Tag requires constant data declaration
  153 |     operator Z<17>();
      |     ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:154:5: warning: KS10: Tag requires constant data declaration
  154 |     operator Z<17>() const;
      |     ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:156:10: warning: KS10: Tag requires constant data declaration
  156 |     void accessor_16() const;
      |          ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:157:10: warning: KS10: Tag requires constant data declaration
  157 |     void manipulator_16();
      |          ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:158:10: warning: KS10: Tag requires constant data declaration
  158 |     void aspect_16();
      |          ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:159:16: warning: KS10: Tag requires constant data declaration
  159 |     static int s_class_data_16;
      |                ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:160:17: warning: KS10: Tag requires constant data declaration
  160 |     static void s_class_method_16();
      |                 ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:162:5: warning: KS09: Constructor or destructor requires CREATORS tag
  162 |     X(Z<16>);
      |     ^
./sections.h:141:1: note: KS09: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:163:8: warning: KS10: Tag requires constant data declaration
  163 |     X& operator=(Z<16>);
      |        ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:164:9: warning: KS10: Tag requires constant data declaration
  164 |     int d_data_16;
      |         ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:165:17: warning: KS10: Tag requires constant data declaration
  165 |     typedef int Type_16;
      |                 ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:166:5: warning: KS10: Tag requires constant data declaration
  166 |     operator Z<16>();
      |     ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:167:5: warning: KS10: Tag requires constant data declaration
  167 |     operator Z<16>() const;
      |     ^
./sections.h:141:1: note: KS10: Tag is here
  141 | // CONSTANTS
      | ^
./sections.h:171:10: warning: KS04: Tag requires instance data field declaration
  171 |     void accessor_15() const;
      |          ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:172:10: warning: KS04: Tag requires instance data field declaration
  172 |     void manipulator_15();
      |          ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:173:10: warning: KS04: Tag requires instance data field declaration
  173 |     void aspect_15();
      |          ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:174:16: warning: KS04: Tag requires instance data field declaration
  174 |     static int s_class_data_15;
      |                ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:175:17: warning: KS04: Tag requires instance data field declaration
  175 |     static void s_class_method_15();
      |                 ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:176:22: warning: KS04: Tag requires instance data field declaration
  176 |     static const int s_CONSTANT_15 = 7;
      |                      ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:177:5: warning: KS09: Constructor or destructor requires CREATORS tag
  177 |     X(Z<15>);
      |     ^
./sections.h:169:1: note: KS09: Tag is here
  169 | // DATA
      | ^
./sections.h:178:8: warning: KS04: Tag requires instance data field declaration
  178 |     X& operator=(Z<15>);
      |        ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:180:17: warning: KS04: Tag requires instance data field declaration
  180 |     typedef int Type_15;
      |                 ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:181:5: warning: KS04: Tag requires instance data field declaration
  181 |     operator Z<15>();
      |     ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:182:5: warning: KS04: Tag requires instance data field declaration
  182 |     operator Z<15>() const;
      |     ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:184:10: warning: KS04: Tag requires instance data field declaration
  184 |     void accessor_14() const;
      |          ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:185:10: warning: KS04: Tag requires instance data field declaration
  185 |     void manipulator_14();
      |          ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:186:10: warning: KS04: Tag requires instance data field declaration
  186 |     void aspect_14();
      |          ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:187:16: warning: KS04: Tag requires instance data field declaration
  187 |     static int s_class_data_14;
      |                ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:188:17: warning: KS04: Tag requires instance data field declaration
  188 |     static void s_class_method_14();
      |                 ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:189:22: warning: KS04: Tag requires instance data field declaration
  189 |     static const int s_CONSTANT_14 = 7;
      |                      ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:190:5: warning: KS09: Constructor or destructor requires CREATORS tag
  190 |     X(Z<14>);
      |     ^
./sections.h:169:1: note: KS09: Tag is here
  169 | // DATA
      | ^
./sections.h:191:8: warning: KS04: Tag requires instance data field declaration
  191 |     X& operator=(Z<14>);
      |        ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:192:9: warning: KS02: Tag implicitly requires private declaration
  192 |     int d_data_14;
      |         ^
./sections.h:169:1: note: KS02: Tag is here
  169 | // DATA
      | ^
./sections.h:193:17: warning: KS04: Tag requires instance data field declaration
  193 |     typedef int Type_14;
      |                 ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:194:5: warning: KS04: Tag requires instance data field declaration
  194 |     operator Z<14>();
      |     ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:195:5: warning: KS04: Tag requires instance data field declaration
  195 |     operator Z<14>() const;
      |     ^
./sections.h:169:1: note: KS04: Tag is here
  169 | // DATA
      | ^
./sections.h:199:10: warning: KS04: Tag requires instance data field declaration
  199 |     void accessor_13() const;
      |          ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:200:10: warning: KS04: Tag requires instance data field declaration
  200 |     void manipulator_13();
      |          ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:201:10: warning: KS04: Tag requires instance data field declaration
  201 |     void aspect_13();
      |          ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:202:16: warning: KS04: Tag requires instance data field declaration
  202 |     static int s_class_data_13;
      |                ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:203:17: warning: KS04: Tag requires instance data field declaration
  203 |     static void s_class_method_13();
      |                 ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:204:22: warning: KS04: Tag requires instance data field declaration
  204 |     static const int s_CONSTANT_13 = 7;
      |                      ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:205:5: warning: KS09: Constructor or destructor requires CREATORS tag
  205 |     X(Z<13>);
      |     ^
./sections.h:197:1: note: KS09: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:206:8: warning: KS04: Tag requires instance data field declaration
  206 |     X& operator=(Z<13>);
      |        ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:208:17: warning: KS04: Tag requires instance data field declaration
  208 |     typedef int Type_13;
      |                 ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:209:5: warning: KS04: Tag requires instance data field declaration
  209 |     operator Z<13>();
      |     ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:210:5: warning: KS04: Tag requires instance data field declaration
  210 |     operator Z<13>() const;
      |     ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:212:10: warning: KS04: Tag requires instance data field declaration
  212 |     void accessor_12() const;
      |          ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:213:10: warning: KS04: Tag requires instance data field declaration
  213 |     void manipulator_12();
      |          ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:214:10: warning: KS04: Tag requires instance data field declaration
  214 |     void aspect_12();
      |          ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:215:16: warning: KS04: Tag requires instance data field declaration
  215 |     static int s_class_data_12;
      |                ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:216:17: warning: KS04: Tag requires instance data field declaration
  216 |     static void s_class_method_12();
      |                 ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:217:22: warning: KS04: Tag requires instance data field declaration
  217 |     static const int s_CONSTANT_12 = 7;
      |                      ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:218:5: warning: KS09: Constructor or destructor requires CREATORS tag
  218 |     X(Z<12>);
      |     ^
./sections.h:197:1: note: KS09: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:219:8: warning: KS04: Tag requires instance data field declaration
  219 |     X& operator=(Z<12>);
      |        ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:220:9: warning: KS02: Tag implicitly requires private declaration
  220 |     int d_data_12;
      |         ^
./sections.h:197:1: note: KS02: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:221:17: warning: KS04: Tag requires instance data field declaration
  221 |     typedef int Type_12;
      |                 ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:222:5: warning: KS04: Tag requires instance data field declaration
  222 |     operator Z<12>();
      |     ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:223:5: warning: KS04: Tag requires instance data field declaration
  223 |     operator Z<12>() const;
      |     ^
./sections.h:197:1: note: KS04: Tag is here
  197 | // DATA MEMBERS
      | ^
./sections.h:227:10: warning: KS08: Tag requires non-const method declaration
  227 |     void accessor_11() const;
      |          ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:228:10: warning: KS01: Tag requires public declaration
  228 |     void manipulator_11();
      |          ^
./sections.h:225:1: note: KS01: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:229:10: warning: KS01: Tag requires public declaration
  229 |     void aspect_11();
      |          ^
./sections.h:225:1: note: KS01: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:230:16: warning: KS08: Tag requires non-const method declaration
  230 |     static int s_class_data_11;
      |                ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:231:17: warning: KS01: Tag requires public declaration
  231 |     static void s_class_method_11();
      |                 ^
./sections.h:225:1: note: KS01: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:232:22: warning: KS08: Tag requires non-const method declaration
  232 |     static const int s_CONSTANT_11 = 7;
      |                      ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:233:5: warning: KS09: Constructor or destructor requires CREATORS tag
  233 |     X(Z<11>);
      |     ^
./sections.h:225:1: note: KS09: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:234:8: warning: KS01: Tag requires public declaration
  234 |     X& operator=(Z<11>);
      |        ^
./sections.h:225:1: note: KS01: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:235:9: warning: KS08: Tag requires non-const method declaration
  235 |     int d_data_11;
      |         ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:236:17: warning: KS08: Tag requires non-const method declaration
  236 |     typedef int Type_11;
      |                 ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:237:5: warning: KS01: Tag requires public declaration
  237 |     operator Z<11>();
      |     ^
./sections.h:225:1: note: KS01: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:238:5: warning: KS08: Tag requires non-const method declaration
  238 |     operator Z<11>() const;
      |     ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:240:10: warning: KS08: Tag requires non-const method declaration
  240 |     void accessor_9() const;
      |          ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:243:16: warning: KS08: Tag requires non-const method declaration
  243 |     static int s_class_data_9;
      |                ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:245:22: warning: KS08: Tag requires non-const method declaration
  245 |     static const int s_CONSTANT_9 = 7;
      |                      ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:246:5: warning: KS09: Constructor or destructor requires CREATORS tag
  246 |     X(Z<9>);
      |     ^
./sections.h:225:1: note: KS09: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:248:9: warning: KS08: Tag requires non-const method declaration
  248 |     int d_data_9;
      |         ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:249:17: warning: KS08: Tag requires non-const method declaration
  249 |     typedef int Type_9;
      |                 ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:251:5: warning: KS08: Tag requires non-const method declaration
  251 |     operator Z<9>() const;
      |     ^
./sections.h:225:1: note: KS08: Tag is here
  225 | // FUNCTIONS
      | ^
./sections.h:255:10: warning: KS08: Tag requires non-const method declaration
  255 |     void accessor_8() const;
      |          ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:256:10: warning: KS01: Tag requires public declaration
  256 |     void manipulator_8();
      |          ^
./sections.h:253:1: note: KS01: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:257:10: warning: KS01: Tag requires public declaration
  257 |     void aspect_8();
      |          ^
./sections.h:253:1: note: KS01: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:258:16: warning: KS08: Tag requires non-const method declaration
  258 |     static int s_class_data_8;
      |                ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:259:17: warning: KS01: Tag requires public declaration
  259 |     static void s_class_method_8();
      |                 ^
./sections.h:253:1: note: KS01: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:260:22: warning: KS08: Tag requires non-const method declaration
  260 |     static const int s_CONSTANT_8 = 7;
      |                      ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:261:5: warning: KS09: Constructor or destructor requires CREATORS tag
  261 |     X(Z<8>);
      |     ^
./sections.h:253:1: note: KS09: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:262:8: warning: KS01: Tag requires public declaration
  262 |     X& operator=(Z<8>);
      |        ^
./sections.h:253:1: note: KS01: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:263:9: warning: KS08: Tag requires non-const method declaration
  263 |     int d_data_8;
      |         ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:264:17: warning: KS08: Tag requires non-const method declaration
  264 |     typedef int Type_8;
      |                 ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:265:5: warning: KS01: Tag requires public declaration
  265 |     operator Z<8>();
      |     ^
./sections.h:253:1: note: KS01: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:266:5: warning: KS08: Tag requires non-const method declaration
  266 |     operator Z<8>() const;
      |     ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:268:10: warning: KS08: Tag requires non-const method declaration
  268 |     void accessor_7() const;
      |          ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:271:16: warning: KS08: Tag requires non-const method declaration
  271 |     static int s_class_data_7;
      |                ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:273:22: warning: KS08: Tag requires non-const method declaration
  273 |     static const int s_CONSTANT_7 = 7;
      |                      ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:274:5: warning: KS09: Constructor or destructor requires CREATORS tag
  274 |     X(Z<7>);
      |     ^
./sections.h:253:1: note: KS09: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:276:9: warning: KS08: Tag requires non-const method declaration
  276 |     int d_data_7;
      |         ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:277:17: warning: KS08: Tag requires non-const method declaration
  277 |     typedef int Type_7;
      |                 ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:279:5: warning: KS08: Tag requires non-const method declaration
  279 |     operator Z<7>() const;
      |     ^
./sections.h:253:1: note: KS08: Tag is here
  253 | // MANIPULATORS
      | ^
./sections.h:286:16: warning: KS03: Tag requires function declaration
  286 |     static int s_class_data_6;
      |                ^
./sections.h:281:1: note: KS03: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:288:22: warning: KS03: Tag requires function declaration
  288 |     static const int s_CONSTANT_6 = 7;
      |                      ^
./sections.h:281:1: note: KS03: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:291:9: warning: KS03: Tag requires function declaration
  291 |     int d_data_6;
      |         ^
./sections.h:281:1: note: KS03: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:292:17: warning: KS03: Tag requires function declaration
  292 |     typedef int Type_6;
      |                 ^
./sections.h:281:1: note: KS03: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:296:10: warning: KS02: Tag implicitly requires private declaration
  296 |     void accessor_5() const;
      |          ^
./sections.h:281:1: note: KS02: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:297:10: warning: KS02: Tag implicitly requires private declaration
  297 |     void manipulator_5();
      |          ^
./sections.h:281:1: note: KS02: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:298:10: warning: KS02: Tag implicitly requires private declaration
  298 |     void aspect_5();
      |          ^
./sections.h:281:1: note: KS02: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:299:16: warning: KS03: Tag requires function declaration
  299 |     static int s_class_data_5;
      |                ^
./sections.h:281:1: note: KS03: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:300:17: warning: KS02: Tag implicitly requires private declaration
  300 |     static void s_class_method_5();
      |                 ^
./sections.h:281:1: note: KS02: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:301:22: warning: KS03: Tag requires function declaration
  301 |     static const int s_CONSTANT_5 = 7;
      |                      ^
./sections.h:281:1: note: KS03: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:302:5: warning: KS02: Tag implicitly requires private declaration
  302 |     X(Z<5>);
      |     ^
./sections.h:281:1: note: KS02: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:303:8: warning: KS02: Tag implicitly requires private declaration
  303 |     X& operator=(Z<5>);
      |        ^
./sections.h:281:1: note: KS02: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:304:9: warning: KS03: Tag requires function declaration
  304 |     int d_data_5;
      |         ^
./sections.h:281:1: note: KS03: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:305:17: warning: KS03: Tag requires function declaration
  305 |     typedef int Type_5;
      |                 ^
./sections.h:281:1: note: KS03: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:306:5: warning: KS02: Tag implicitly requires private declaration
  306 |     operator Z<5>();
      |     ^
./sections.h:281:1: note: KS02: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:307:5: warning: KS02: Tag implicitly requires private declaration
  307 |     operator Z<5>() const;
      |     ^
./sections.h:281:1: note: KS02: Tag is here
  281 | // NOT IMPLEMENTED
      | ^
./sections.h:311:10: warning: KS14: Tag requires conversion operator declaration
  311 |     void accessor_4() const;
      |          ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:312:10: warning: KS14: Tag requires conversion operator declaration
  312 |     void manipulator_4();
      |          ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:313:10: warning: KS14: Tag requires conversion operator declaration
  313 |     void aspect_4();
      |          ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:314:16: warning: KS14: Tag requires conversion operator declaration
  314 |     static int s_class_data_4;
      |                ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:315:17: warning: KS14: Tag requires conversion operator declaration
  315 |     static void s_class_method_4();
      |                 ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:316:22: warning: KS14: Tag requires conversion operator declaration
  316 |     static const int s_CONSTANT_4 = 7;
      |                      ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:317:5: warning: KS09: Constructor or destructor requires CREATORS tag
  317 |     X(Z<4>);
      |     ^
./sections.h:309:1: note: KS09: Tag is here
  309 | // TRAITS
      | ^
./sections.h:318:8: warning: KS14: Tag requires conversion operator declaration
  318 |     X& operator=(Z<4>);
      |        ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:319:9: warning: KS14: Tag requires conversion operator declaration
  319 |     int d_data_4;
      |         ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:320:17: warning: KS14: Tag requires conversion operator declaration
  320 |     typedef int Type_4;
      |                 ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:321:5: warning: KS01: Tag requires public declaration
  321 |     operator Z<4>();
      |     ^
./sections.h:309:1: note: KS01: Tag is here
  309 | // TRAITS
      | ^
./sections.h:322:5: warning: KS01: Tag requires public declaration
  322 |     operator Z<4>() const;
      |     ^
./sections.h:309:1: note: KS01: Tag is here
  309 | // TRAITS
      | ^
./sections.h:324:10: warning: KS14: Tag requires conversion operator declaration
  324 |     void accessor_3() const;
      |          ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:325:10: warning: KS14: Tag requires conversion operator declaration
  325 |     void manipulator_3();
      |          ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:326:10: warning: KS14: Tag requires conversion operator declaration
  326 |     void aspect_3();
      |          ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:327:16: warning: KS14: Tag requires conversion operator declaration
  327 |     static int s_class_data_3;
      |                ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:328:17: warning: KS14: Tag requires conversion operator declaration
  328 |     static void s_class_method_3();
      |                 ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:329:22: warning: KS14: Tag requires conversion operator declaration
  329 |     static const int s_CONSTANT_3 = 7;
      |                      ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:330:5: warning: KS09: Constructor or destructor requires CREATORS tag
  330 |     X(Z<3>);
      |     ^
./sections.h:309:1: note: KS09: Tag is here
  309 | // TRAITS
      | ^
./sections.h:331:8: warning: KS14: Tag requires conversion operator declaration
  331 |     X& operator=(Z<3>);
      |        ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:332:9: warning: KS14: Tag requires conversion operator declaration
  332 |     int d_data_3;
      |         ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:333:17: warning: KS14: Tag requires conversion operator declaration
  333 |     typedef int Type_3;
      |                 ^
./sections.h:309:1: note: KS14: Tag is here
  309 | // TRAITS
      | ^
./sections.h:339:10: warning: KS06: Tag requires type declaration
  339 |     void accessor_2() const;
      |          ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:340:10: warning: KS06: Tag requires type declaration
  340 |     void manipulator_2();
      |          ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:341:10: warning: KS06: Tag requires type declaration
  341 |     void aspect_2();
      |          ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:342:16: warning: KS06: Tag requires type declaration
  342 |     static int s_class_data_2;
      |                ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:343:17: warning: KS06: Tag requires type declaration
  343 |     static void s_class_method_2();
      |                 ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:344:22: warning: KS06: Tag requires type declaration
  344 |     static const int s_CONSTANT_2 = 7;
      |                      ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:345:5: warning: KS09: Constructor or destructor requires CREATORS tag
  345 |     X(Z<2>);
      |     ^
./sections.h:337:1: note: KS09: Tag is here
  337 | // TYPES
      | ^
./sections.h:346:8: warning: KS06: Tag requires type declaration
  346 |     X& operator=(Z<2>);
      |        ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:347:9: warning: KS06: Tag requires type declaration
  347 |     int d_data_2;
      |         ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:348:17: warning: KS01: Tag requires public declaration
  348 |     typedef int Type_2;
      |                 ^
./sections.h:337:1: note: KS01: Tag is here
  337 | // TYPES
      | ^
./sections.h:349:5: warning: KS06: Tag requires type declaration
  349 |     operator Z<2>();
      |     ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:350:5: warning: KS06: Tag requires type declaration
  350 |     operator Z<2>() const;
      |     ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:352:10: warning: KS06: Tag requires type declaration
  352 |     void accessor_1() const;
      |          ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:353:10: warning: KS06: Tag requires type declaration
  353 |     void manipulator_1();
      |          ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:354:10: warning: KS06: Tag requires type declaration
  354 |     void aspect_1();
      |          ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:355:16: warning: KS06: Tag requires type declaration
  355 |     static int s_class_data_1;
      |                ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:356:17: warning: KS06: Tag requires type declaration
  356 |     static void s_class_method_1();
      |                 ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:357:22: warning: KS06: Tag requires type declaration
  357 |     static const int s_CONSTANT_1 = 7;
      |                      ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:358:5: warning: KS09: Constructor or destructor requires CREATORS tag
  358 |     X(Z<1>);
      |     ^
./sections.h:337:1: note: KS09: Tag is here
  337 | // TYPES
      | ^
./sections.h:359:8: warning: KS06: Tag requires type declaration
  359 |     X& operator=(Z<1>);
      |        ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:360:9: warning: KS06: Tag requires type declaration
  360 |     int d_data_1;
      |         ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:362:5: warning: KS06: Tag requires type declaration
  362 |     operator Z<1>();
      |     ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:363:5: warning: KS06: Tag requires type declaration
  363 |     operator Z<1>() const;
      |     ^
./sections.h:337:1: note: KS06: Tag is here
  337 | // TYPES
      | ^
./sections.h:368:10: warning: KS07: Tag requires const method declaration
  368 |     void manipulator_260();
      |          ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:369:10: warning: KS07: Tag requires const method declaration
  369 |     void aspect_260();
      |          ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:370:16: warning: KS07: Tag requires const method declaration
  370 |     static int s_class_data_260;
      |                ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:371:17: warning: KS07: Tag requires const method declaration
  371 |     static void s_class_method_260();
      |                 ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:372:22: warning: KS07: Tag requires const method declaration
  372 |     static const int s_CONSTANT_260 = 70;
      |                      ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:373:5: warning: KS09: Constructor or destructor requires CREATORS tag
  373 |     X(Z<260>);
      |     ^
./sections.h:365:1: note: KS09: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:374:8: warning: KS07: Tag requires const method declaration
  374 |     X& operator=(Z<260>);
      |        ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:375:9: warning: KS07: Tag requires const method declaration
  375 |     int d_data_260;
      |         ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:376:17: warning: KS07: Tag requires const method declaration
  376 |     typedef int Type_260;
      |                 ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:377:5: warning: KS07: Tag requires const method declaration
  377 |     operator Z<260>();
      |     ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:380:10: warning: KS02: Tag requires private declaration
  380 |     void accessor_250() const;
      |          ^
./sections.h:365:1: note: KS02: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:381:10: warning: KS07: Tag requires const method declaration
  381 |     void manipulator_250();
      |          ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:382:10: warning: KS07: Tag requires const method declaration
  382 |     void aspect_250();
      |          ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:383:16: warning: KS07: Tag requires const method declaration
  383 |     static int s_class_data_250;
      |                ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:384:17: warning: KS07: Tag requires const method declaration
  384 |     static void s_class_method_250();
      |                 ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:385:22: warning: KS07: Tag requires const method declaration
  385 |     static const int s_CONSTANT_250 = 70;
      |                      ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:386:5: warning: KS09: Constructor or destructor requires CREATORS tag
  386 |     X(Z<250>);
      |     ^
./sections.h:365:1: note: KS09: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:387:8: warning: KS07: Tag requires const method declaration
  387 |     X& operator=(Z<250>);
      |        ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:388:9: warning: KS07: Tag requires const method declaration
  388 |     int d_data_250;
      |         ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:389:17: warning: KS07: Tag requires const method declaration
  389 |     typedef int Type_250;
      |                 ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:390:5: warning: KS07: Tag requires const method declaration
  390 |     operator Z<250>();
      |     ^
./sections.h:365:1: note: KS07: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:391:5: warning: KS02: Tag requires private declaration
  391 |     operator Z<250>() const;
      |     ^
./sections.h:365:1: note: KS02: Tag is here
  365 | // PRIVATE ACCESSORS
      | ^
./sections.h:398:16: warning: KS03: Tag requires function declaration
  398 |     static int s_class_data_240;
      |                ^
./sections.h:393:1: note: KS03: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:400:22: warning: KS03: Tag requires function declaration
  400 |     static const int s_CONSTANT_240 = 70;
      |                      ^
./sections.h:393:1: note: KS03: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:401:5: warning: KS09: Constructor or destructor requires CREATORS tag
  401 |     X(Z<240>);
      |     ^
./sections.h:393:1: note: KS09: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:403:9: warning: KS03: Tag requires function declaration
  403 |     int d_data_240;
      |         ^
./sections.h:393:1: note: KS03: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:404:17: warning: KS03: Tag requires function declaration
  404 |     typedef int Type_240;
      |                 ^
./sections.h:393:1: note: KS03: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:408:10: warning: KS02: Tag requires private declaration
  408 |     void accessor_230() const;
      |          ^
./sections.h:393:1: note: KS02: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:409:10: warning: KS02: Tag requires private declaration
  409 |     void manipulator_230();
      |          ^
./sections.h:393:1: note: KS02: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:410:10: warning: KS02: Tag requires private declaration
  410 |     void aspect_230();
      |          ^
./sections.h:393:1: note: KS02: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:411:16: warning: KS03: Tag requires function declaration
  411 |     static int s_class_data_230;
      |                ^
./sections.h:393:1: note: KS03: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:412:17: warning: KS02: Tag requires private declaration
  412 |     static void s_class_method_230();
      |                 ^
./sections.h:393:1: note: KS02: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:413:22: warning: KS03: Tag requires function declaration
  413 |     static const int s_CONSTANT_230 = 70;
      |                      ^
./sections.h:393:1: note: KS03: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:414:5: warning: KS09: Constructor or destructor requires CREATORS tag
  414 |     X(Z<230>);
      |     ^
./sections.h:393:1: note: KS09: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:415:8: warning: KS02: Tag requires private declaration
  415 |     X& operator=(Z<230>);
      |        ^
./sections.h:393:1: note: KS02: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:416:9: warning: KS03: Tag requires function declaration
  416 |     int d_data_230;
      |         ^
./sections.h:393:1: note: KS03: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:417:17: warning: KS03: Tag requires function declaration
  417 |     typedef int Type_230;
      |                 ^
./sections.h:393:1: note: KS03: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:418:5: warning: KS02: Tag requires private declaration
  418 |     operator Z<230>();
      |     ^
./sections.h:393:1: note: KS02: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:419:5: warning: KS02: Tag requires private declaration
  419 |     operator Z<230>() const;
      |     ^
./sections.h:393:1: note: KS02: Tag is here
  393 | // PRIVATE ASPECTS
      | ^
./sections.h:423:10: warning: KS05: Tag requires static data field declaration
  423 |     void accessor_220() const;
      |          ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:424:10: warning: KS05: Tag requires static data field declaration
  424 |     void manipulator_220();
      |          ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:425:10: warning: KS05: Tag requires static data field declaration
  425 |     void aspect_220();
      |          ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:427:17: warning: KS05: Tag requires static data field declaration
  427 |     static void s_class_method_220();
      |                 ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:429:5: warning: KS09: Constructor or destructor requires CREATORS tag
  429 |     X(Z<220>);
      |     ^
./sections.h:421:1: note: KS09: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:430:8: warning: KS05: Tag requires static data field declaration
  430 |     X& operator=(Z<220>);
      |        ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:431:9: warning: KS05: Tag requires static data field declaration
  431 |     int d_data_220;
      |         ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:432:17: warning: KS05: Tag requires static data field declaration
  432 |     typedef int Type_220;
      |                 ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:433:5: warning: KS05: Tag requires static data field declaration
  433 |     operator Z<220>();
      |     ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:434:5: warning: KS05: Tag requires static data field declaration
  434 |     operator Z<220>() const;
      |     ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:436:10: warning: KS05: Tag requires static data field declaration
  436 |     void accessor_210() const;
      |          ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:437:10: warning: KS05: Tag requires static data field declaration
  437 |     void manipulator_210();
      |          ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:438:10: warning: KS05: Tag requires static data field declaration
  438 |     void aspect_210();
      |          ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:439:16: warning: KS02: Tag requires private declaration
  439 |     static int s_class_data_210;
      |                ^
./sections.h:421:1: note: KS02: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:440:17: warning: KS05: Tag requires static data field declaration
  440 |     static void s_class_method_210();
      |                 ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:441:22: warning: KS02: Tag requires private declaration
  441 |     static const int s_CONSTANT_210 = 70;
      |                      ^
./sections.h:421:1: note: KS02: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:442:5: warning: KS09: Constructor or destructor requires CREATORS tag
  442 |     X(Z<210>);
      |     ^
./sections.h:421:1: note: KS09: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:443:8: warning: KS05: Tag requires static data field declaration
  443 |     X& operator=(Z<210>);
      |        ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:444:9: warning: KS05: Tag requires static data field declaration
  444 |     int d_data_210;
      |         ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:445:17: warning: KS05: Tag requires static data field declaration
  445 |     typedef int Type_210;
      |                 ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:446:5: warning: KS05: Tag requires static data field declaration
  446 |     operator Z<210>();
      |     ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:447:5: warning: KS05: Tag requires static data field declaration
  447 |     operator Z<210>() const;
      |     ^
./sections.h:421:1: note: KS05: Tag is here
  421 | // PRIVATE CLASS DATA
      | ^
./sections.h:451:10: warning: KS11: Tag requires static method declaration
  451 |     void accessor_190() const;
      |          ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:452:10: warning: KS11: Tag requires static method declaration
  452 |     void manipulator_190();
      |          ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:453:10: warning: KS11: Tag requires static method declaration
  453 |     void aspect_190();
      |          ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:454:16: warning: KS11: Tag requires static method declaration
  454 |     static int s_class_data_190;
      |                ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:456:22: warning: KS11: Tag requires static method declaration
  456 |     static const int s_CONSTANT_190 = 70;
      |                      ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:457:5: warning: KS09: Constructor or destructor requires CREATORS tag
  457 |     X(Z<190>);
      |     ^
./sections.h:449:1: note: KS09: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:458:8: warning: KS11: Tag requires static method declaration
  458 |     X& operator=(Z<190>);
      |        ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:459:9: warning: KS11: Tag requires static method declaration
  459 |     int d_data_190;
      |         ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:460:17: warning: KS11: Tag requires static method declaration
  460 |     typedef int Type_190;
      |                 ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:461:5: warning: KS11: Tag requires static method declaration
  461 |     operator Z<190>();
      |     ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:462:5: warning: KS11: Tag requires static method declaration
  462 |     operator Z<190>() const;
      |     ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:464:10: warning: KS11: Tag requires static method declaration
  464 |     void accessor_180() const;
      |          ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:465:10: warning: KS11: Tag requires static method declaration
  465 |     void manipulator_180();
      |          ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:466:10: warning: KS11: Tag requires static method declaration
  466 |     void aspect_180();
      |          ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:467:16: warning: KS11: Tag requires static method declaration
  467 |     static int s_class_data_180;
      |                ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:468:17: warning: KS02: Tag requires private declaration
  468 |     static void s_class_method_180();
      |                 ^
./sections.h:449:1: note: KS02: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:469:22: warning: KS11: Tag requires static method declaration
  469 |     static const int s_CONSTANT_180 = 70;
      |                      ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:470:5: warning: KS09: Constructor or destructor requires CREATORS tag
  470 |     X(Z<180>);
      |     ^
./sections.h:449:1: note: KS09: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:471:8: warning: KS11: Tag requires static method declaration
  471 |     X& operator=(Z<180>);
      |        ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:472:9: warning: KS11: Tag requires static method declaration
  472 |     int d_data_180;
      |         ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:473:17: warning: KS11: Tag requires static method declaration
  473 |     typedef int Type_180;
      |                 ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:474:5: warning: KS11: Tag requires static method declaration
  474 |     operator Z<180>();
      |     ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:475:5: warning: KS11: Tag requires static method declaration
  475 |     operator Z<180>() const;
      |     ^
./sections.h:449:1: note: KS11: Tag is here
  449 | // PRIVATE CLASS METHODS
      | ^
./sections.h:479:10: warning: KS10: Tag requires constant data declaration
  479 |     void accessor_170() const;
      |          ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:480:10: warning: KS10: Tag requires constant data declaration
  480 |     void manipulator_170();
      |          ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:481:10: warning: KS10: Tag requires constant data declaration
  481 |     void aspect_170();
      |          ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:482:16: warning: KS10: Tag requires constant data declaration
  482 |     static int s_class_data_170;
      |                ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:483:17: warning: KS10: Tag requires constant data declaration
  483 |     static void s_class_method_170();
      |                 ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:485:5: warning: KS09: Constructor or destructor requires CREATORS tag
  485 |     X(Z<170>);
      |     ^
./sections.h:477:1: note: KS09: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:486:8: warning: KS10: Tag requires constant data declaration
  486 |     X& operator=(Z<170>);
      |        ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:487:9: warning: KS10: Tag requires constant data declaration
  487 |     int d_data_170;
      |         ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:488:17: warning: KS10: Tag requires constant data declaration
  488 |     typedef int Type_170;
      |                 ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:489:5: warning: KS10: Tag requires constant data declaration
  489 |     operator Z<170>();
      |     ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:490:5: warning: KS10: Tag requires constant data declaration
  490 |     operator Z<170>() const;
      |     ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:492:10: warning: KS10: Tag requires constant data declaration
  492 |     void accessor_160() const;
      |          ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:493:10: warning: KS10: Tag requires constant data declaration
  493 |     void manipulator_160();
      |          ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:494:10: warning: KS10: Tag requires constant data declaration
  494 |     void aspect_160();
      |          ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:495:16: warning: KS10: Tag requires constant data declaration
  495 |     static int s_class_data_160;
      |                ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:496:17: warning: KS10: Tag requires constant data declaration
  496 |     static void s_class_method_160();
      |                 ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:497:22: warning: KS02: Tag requires private declaration
  497 |     static const int s_CONSTANT_160 = 70;
      |                      ^
./sections.h:477:1: note: KS02: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:498:5: warning: KS09: Constructor or destructor requires CREATORS tag
  498 |     X(Z<160>);
      |     ^
./sections.h:477:1: note: KS09: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:499:8: warning: KS10: Tag requires constant data declaration
  499 |     X& operator=(Z<160>);
      |        ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:500:9: warning: KS10: Tag requires constant data declaration
  500 |     int d_data_160;
      |         ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:501:17: warning: KS10: Tag requires constant data declaration
  501 |     typedef int Type_160;
      |                 ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:502:5: warning: KS10: Tag requires constant data declaration
  502 |     operator Z<160>();
      |     ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:503:5: warning: KS10: Tag requires constant data declaration
  503 |     operator Z<160>() const;
      |     ^
./sections.h:477:1: note: KS10: Tag is here
  477 | // PRIVATE CONSTANTS
      | ^
./sections.h:507:10: warning: KS04: Tag requires instance data field declaration
  507 |     void accessor_150() const;
      |          ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:508:10: warning: KS04: Tag requires instance data field declaration
  508 |     void manipulator_150();
      |          ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:509:10: warning: KS04: Tag requires instance data field declaration
  509 |     void aspect_150();
      |          ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:510:16: warning: KS04: Tag requires instance data field declaration
  510 |     static int s_class_data_150;
      |                ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:511:17: warning: KS04: Tag requires instance data field declaration
  511 |     static void s_class_method_150();
      |                 ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:512:22: warning: KS04: Tag requires instance data field declaration
  512 |     static const int s_CONSTANT_150 = 70;
      |                      ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:513:5: warning: KS09: Constructor or destructor requires CREATORS tag
  513 |     X(Z<150>);
      |     ^
./sections.h:505:1: note: KS09: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:514:8: warning: KS04: Tag requires instance data field declaration
  514 |     X& operator=(Z<150>);
      |        ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:516:17: warning: KS04: Tag requires instance data field declaration
  516 |     typedef int Type_150;
      |                 ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:517:5: warning: KS04: Tag requires instance data field declaration
  517 |     operator Z<150>();
      |     ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:518:5: warning: KS04: Tag requires instance data field declaration
  518 |     operator Z<150>() const;
      |     ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:520:10: warning: KS04: Tag requires instance data field declaration
  520 |     void accessor_140() const;
      |          ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:521:10: warning: KS04: Tag requires instance data field declaration
  521 |     void manipulator_140();
      |          ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:522:10: warning: KS04: Tag requires instance data field declaration
  522 |     void aspect_140();
      |          ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:523:16: warning: KS04: Tag requires instance data field declaration
  523 |     static int s_class_data_140;
      |                ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:524:17: warning: KS04: Tag requires instance data field declaration
  524 |     static void s_class_method_140();
      |                 ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:525:22: warning: KS04: Tag requires instance data field declaration
  525 |     static const int s_CONSTANT_140 = 70;
      |                      ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:526:5: warning: KS09: Constructor or destructor requires CREATORS tag
  526 |     X(Z<140>);
      |     ^
./sections.h:505:1: note: KS09: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:527:8: warning: KS04: Tag requires instance data field declaration
  527 |     X& operator=(Z<140>);
      |        ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:528:9: warning: KS02: Tag requires private declaration
  528 |     int d_data_140;
      |         ^
./sections.h:505:1: note: KS02: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:529:17: warning: KS04: Tag requires instance data field declaration
  529 |     typedef int Type_140;
      |                 ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:530:5: warning: KS04: Tag requires instance data field declaration
  530 |     operator Z<140>();
      |     ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:531:5: warning: KS04: Tag requires instance data field declaration
  531 |     operator Z<140>() const;
      |     ^
./sections.h:505:1: note: KS04: Tag is here
  505 | // PRIVATE DATA
      | ^
./sections.h:535:10: warning: KS04: Tag requires instance data field declaration
  535 |     void accessor_130() const;
      |          ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:536:10: warning: KS04: Tag requires instance data field declaration
  536 |     void manipulator_130();
      |          ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:537:10: warning: KS04: Tag requires instance data field declaration
  537 |     void aspect_130();
      |          ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:538:16: warning: KS04: Tag requires instance data field declaration
  538 |     static int s_class_data_130;
      |                ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:539:17: warning: KS04: Tag requires instance data field declaration
  539 |     static void s_class_method_130();
      |                 ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:540:22: warning: KS04: Tag requires instance data field declaration
  540 |     static const int s_CONSTANT_130 = 70;
      |                      ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:541:5: warning: KS09: Constructor or destructor requires CREATORS tag
  541 |     X(Z<130>);
      |     ^
./sections.h:533:1: note: KS09: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:542:8: warning: KS04: Tag requires instance data field declaration
  542 |     X& operator=(Z<130>);
      |        ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:544:17: warning: KS04: Tag requires instance data field declaration
  544 |     typedef int Type_130;
      |                 ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:545:5: warning: KS04: Tag requires instance data field declaration
  545 |     operator Z<130>();
      |     ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:546:5: warning: KS04: Tag requires instance data field declaration
  546 |     operator Z<130>() const;
      |     ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:548:10: warning: KS04: Tag requires instance data field declaration
  548 |     void accessor_120() const;
      |          ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:549:10: warning: KS04: Tag requires instance data field declaration
  549 |     void manipulator_120();
      |          ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:550:10: warning: KS04: Tag requires instance data field declaration
  550 |     void aspect_120();
      |          ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:551:16: warning: KS04: Tag requires instance data field declaration
  551 |     static int s_class_data_120;
      |                ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:552:17: warning: KS04: Tag requires instance data field declaration
  552 |     static void s_class_method_120();
      |                 ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:553:22: warning: KS04: Tag requires instance data field declaration
  553 |     static const int s_CONSTANT_120 = 70;
      |                      ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:554:5: warning: KS09: Constructor or destructor requires CREATORS tag
  554 |     X(Z<120>);
      |     ^
./sections.h:533:1: note: KS09: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:555:8: warning: KS04: Tag requires instance data field declaration
  555 |     X& operator=(Z<120>);
      |        ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:556:9: warning: KS02: Tag requires private declaration
  556 |     int d_data_120;
      |         ^
./sections.h:533:1: note: KS02: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:557:17: warning: KS04: Tag requires instance data field declaration
  557 |     typedef int Type_120;
      |                 ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:558:5: warning: KS04: Tag requires instance data field declaration
  558 |     operator Z<120>();
      |     ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:559:5: warning: KS04: Tag requires instance data field declaration
  559 |     operator Z<120>() const;
      |     ^
./sections.h:533:1: note: KS04: Tag is here
  533 | // PRIVATE DATA MEMBERS
      | ^
./sections.h:563:10: warning: KS08: Tag requires non-const method declaration
  563 |     void accessor_110() const;
      |          ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:566:16: warning: KS08: Tag requires non-const method declaration
  566 |     static int s_class_data_110;
      |                ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:568:22: warning: KS08: Tag requires non-const method declaration
  568 |     static const int s_CONSTANT_110 = 70;
      |                      ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:569:5: warning: KS09: Constructor or destructor requires CREATORS tag
  569 |     X(Z<110>);
      |     ^
./sections.h:561:1: note: KS09: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:571:9: warning: KS08: Tag requires non-const method declaration
  571 |     int d_data_110;
      |         ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:572:17: warning: KS08: Tag requires non-const method declaration
  572 |     typedef int Type_110;
      |                 ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:574:5: warning: KS08: Tag requires non-const method declaration
  574 |     operator Z<110>() const;
      |     ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:576:10: warning: KS08: Tag requires non-const method declaration
  576 |     void accessor_90() const;
      |          ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:577:10: warning: KS02: Tag requires private declaration
  577 |     void manipulator_90();
      |          ^
./sections.h:561:1: note: KS02: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:578:10: warning: KS02: Tag requires private declaration
  578 |     void aspect_90();
      |          ^
./sections.h:561:1: note: KS02: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:579:16: warning: KS08: Tag requires non-const method declaration
  579 |     static int s_class_data_90;
      |                ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:580:17: warning: KS02: Tag requires private declaration
  580 |     static void s_class_method_90();
      |                 ^
./sections.h:561:1: note: KS02: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:581:22: warning: KS08: Tag requires non-const method declaration
  581 |     static const int s_CONSTANT_90 = 70;
      |                      ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:582:5: warning: KS09: Constructor or destructor requires CREATORS tag
  582 |     X(Z<90>);
      |     ^
./sections.h:561:1: note: KS09: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:583:8: warning: KS02: Tag requires private declaration
  583 |     X& operator=(Z<90>);
      |        ^
./sections.h:561:1: note: KS02: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:584:9: warning: KS08: Tag requires non-const method declaration
  584 |     int d_data_90;
      |         ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:585:17: warning: KS08: Tag requires non-const method declaration
  585 |     typedef int Type_90;
      |                 ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:586:5: warning: KS02: Tag requires private declaration
  586 |     operator Z<90>();
      |     ^
./sections.h:561:1: note: KS02: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:587:5: warning: KS08: Tag requires non-const method declaration
  587 |     operator Z<90>() const;
      |     ^
./sections.h:561:1: note: KS08: Tag is here
  561 | // PRIVATE FUNCTIONS
      | ^
./sections.h:591:10: warning: KS08: Tag requires non-const method declaration
  591 |     void accessor_80() const;
      |          ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:594:16: warning: KS08: Tag requires non-const method declaration
  594 |     static int s_class_data_80;
      |                ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:596:22: warning: KS08: Tag requires non-const method declaration
  596 |     static const int s_CONSTANT_80 = 70;
      |                      ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:597:5: warning: KS09: Constructor or destructor requires CREATORS tag
  597 |     X(Z<80>);
      |     ^
./sections.h:589:1: note: KS09: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:599:9: warning: KS08: Tag requires non-const method declaration
  599 |     int d_data_80;
      |         ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:600:17: warning: KS08: Tag requires non-const method declaration
  600 |     typedef int Type_80;
      |                 ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:602:5: warning: KS08: Tag requires non-const method declaration
  602 |     operator Z<80>() const;
      |     ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:604:10: warning: KS08: Tag requires non-const method declaration
  604 |     void accessor_70() const;
      |          ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:605:10: warning: KS02: Tag requires private declaration
  605 |     void manipulator_70();
      |          ^
./sections.h:589:1: note: KS02: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:606:10: warning: KS02: Tag requires private declaration
  606 |     void aspect_70();
      |          ^
./sections.h:589:1: note: KS02: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:607:16: warning: KS08: Tag requires non-const method declaration
  607 |     static int s_class_data_70;
      |                ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:608:17: warning: KS02: Tag requires private declaration
  608 |     static void s_class_method_70();
      |                 ^
./sections.h:589:1: note: KS02: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:609:22: warning: KS08: Tag requires non-const method declaration
  609 |     static const int s_CONSTANT_70 = 70;
      |                      ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:610:5: warning: KS09: Constructor or destructor requires CREATORS tag
  610 |     X(Z<70>);
      |     ^
./sections.h:589:1: note: KS09: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:611:8: warning: KS02: Tag requires private declaration
  611 |     X& operator=(Z<70>);
      |        ^
./sections.h:589:1: note: KS02: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:612:9: warning: KS08: Tag requires non-const method declaration
  612 |     int d_data_70;
      |         ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:613:17: warning: KS08: Tag requires non-const method declaration
  613 |     typedef int Type_70;
      |                 ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:614:5: warning: KS02: Tag requires private declaration
  614 |     operator Z<70>();
      |     ^
./sections.h:589:1: note: KS02: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:615:5: warning: KS08: Tag requires non-const method declaration
  615 |     operator Z<70>() const;
      |     ^
./sections.h:589:1: note: KS08: Tag is here
  589 | // PRIVATE MANIPULATORS
      | ^
./sections.h:619:10: warning: KS14: Tag requires conversion operator declaration
  619 |     void accessor_40() const;
      |          ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:620:10: warning: KS14: Tag requires conversion operator declaration
  620 |     void manipulator_40();
      |          ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:621:10: warning: KS14: Tag requires conversion operator declaration
  621 |     void aspect_40();
      |          ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:622:16: warning: KS14: Tag requires conversion operator declaration
  622 |     static int s_class_data_40;
      |                ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:623:17: warning: KS14: Tag requires conversion operator declaration
  623 |     static void s_class_method_40();
      |                 ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:624:22: warning: KS14: Tag requires conversion operator declaration
  624 |     static const int s_CONSTANT_40 = 70;
      |                      ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:625:5: warning: KS09: Constructor or destructor requires CREATORS tag
  625 |     X(Z<40>);
      |     ^
./sections.h:617:1: note: KS09: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:626:8: warning: KS14: Tag requires conversion operator declaration
  626 |     X& operator=(Z<40>);
      |        ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:627:9: warning: KS14: Tag requires conversion operator declaration
  627 |     int d_data_40;
      |         ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:628:17: warning: KS14: Tag requires conversion operator declaration
  628 |     typedef int Type_40;
      |                 ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:632:10: warning: KS14: Tag requires conversion operator declaration
  632 |     void accessor_30() const;
      |          ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:633:10: warning: KS14: Tag requires conversion operator declaration
  633 |     void manipulator_30();
      |          ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:634:10: warning: KS14: Tag requires conversion operator declaration
  634 |     void aspect_30();
      |          ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:635:16: warning: KS14: Tag requires conversion operator declaration
  635 |     static int s_class_data_30;
      |                ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:636:17: warning: KS14: Tag requires conversion operator declaration
  636 |     static void s_class_method_30();
      |                 ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:637:22: warning: KS14: Tag requires conversion operator declaration
  637 |     static const int s_CONSTANT_30 = 70;
      |                      ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:638:5: warning: KS09: Constructor or destructor requires CREATORS tag
  638 |     X(Z<30>);
      |     ^
./sections.h:617:1: note: KS09: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:639:8: warning: KS14: Tag requires conversion operator declaration
  639 |     X& operator=(Z<30>);
      |        ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:640:9: warning: KS14: Tag requires conversion operator declaration
  640 |     int d_data_30;
      |         ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:641:17: warning: KS14: Tag requires conversion operator declaration
  641 |     typedef int Type_30;
      |                 ^
./sections.h:617:1: note: KS14: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:642:5: warning: KS02: Tag requires private declaration
  642 |     operator Z<30>();
      |     ^
./sections.h:617:1: note: KS02: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:643:5: warning: KS02: Tag requires private declaration
  643 |     operator Z<30>() const;
      |     ^
./sections.h:617:1: note: KS02: Tag is here
  617 | // PRIVATE TRAITS
      | ^
./sections.h:647:10: warning: KS06: Tag requires type declaration
  647 |     void accessor_20() const;
      |          ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:648:10: warning: KS06: Tag requires type declaration
  648 |     void manipulator_20();
      |          ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:649:10: warning: KS06: Tag requires type declaration
  649 |     void aspect_20();
      |          ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:650:16: warning: KS06: Tag requires type declaration
  650 |     static int s_class_data_20;
      |                ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:651:17: warning: KS06: Tag requires type declaration
  651 |     static void s_class_method_20();
      |                 ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:652:22: warning: KS06: Tag requires type declaration
  652 |     static const int s_CONSTANT_20 = 70;
      |                      ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:653:5: warning: KS09: Constructor or destructor requires CREATORS tag
  653 |     X(Z<20>);
      |     ^
./sections.h:645:1: note: KS09: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:654:8: warning: KS06: Tag requires type declaration
  654 |     X& operator=(Z<20>);
      |        ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:655:9: warning: KS06: Tag requires type declaration
  655 |     int d_data_20;
      |         ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:657:5: warning: KS06: Tag requires type declaration
  657 |     operator Z<20>();
      |     ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:658:5: warning: KS06: Tag requires type declaration
  658 |     operator Z<20>() const;
      |     ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:660:10: warning: KS06: Tag requires type declaration
  660 |     void accessor_10() const;
      |          ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:661:10: warning: KS06: Tag requires type declaration
  661 |     void manipulator_10();
      |          ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:662:10: warning: KS06: Tag requires type declaration
  662 |     void aspect_10();
      |          ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:663:16: warning: KS06: Tag requires type declaration
  663 |     static int s_class_data_10;
      |                ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:664:17: warning: KS06: Tag requires type declaration
  664 |     static void s_class_method_10();
      |                 ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:665:22: warning: KS06: Tag requires type declaration
  665 |     static const int s_CONSTANT_10 = 70;
      |                      ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:666:5: warning: KS09: Constructor or destructor requires CREATORS tag
  666 |     X(Z<10>);
      |     ^
./sections.h:645:1: note: KS09: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:667:8: warning: KS06: Tag requires type declaration
  667 |     X& operator=(Z<10>);
      |        ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:668:9: warning: KS06: Tag requires type declaration
  668 |     int d_data_10;
      |         ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:669:17: warning: KS02: Tag requires private declaration
  669 |     typedef int Type_10;
      |                 ^
./sections.h:645:1: note: KS02: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:670:5: warning: KS06: Tag requires type declaration
  670 |     operator Z<10>();
      |     ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:671:5: warning: KS06: Tag requires type declaration
  671 |     operator Z<10>() const;
      |     ^
./sections.h:645:1: note: KS06: Tag is here
  645 | // PRIVATE TYPES
      | ^
./sections.h:675:10: warning: KS01: Tag requires public declaration
  675 |     void accessor_2600() const;
      |          ^
./sections.h:673:1: note: KS01: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:676:10: warning: KS07: Tag requires const method declaration
  676 |     void manipulator_2600();
      |          ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:677:10: warning: KS07: Tag requires const method declaration
  677 |     void aspect_2600();
      |          ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:678:16: warning: KS07: Tag requires const method declaration
  678 |     static int s_class_data_2600;
      |                ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:679:17: warning: KS07: Tag requires const method declaration
  679 |     static void s_class_method_2600();
      |                 ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:680:22: warning: KS07: Tag requires const method declaration
  680 |     static const int s_CONSTANT_2600 = 7;
      |                      ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:681:5: warning: KS09: Constructor or destructor requires CREATORS tag
  681 |     X(Z<2600>);
      |     ^
./sections.h:673:1: note: KS09: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:682:8: warning: KS07: Tag requires const method declaration
  682 |     X& operator=(Z<2600>);
      |        ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:683:9: warning: KS07: Tag requires const method declaration
  683 |     int d_data_2600;
      |         ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:684:17: warning: KS07: Tag requires const method declaration
  684 |     typedef int Type_2600;
      |                 ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:685:5: warning: KS07: Tag requires const method declaration
  685 |     operator Z<2600>();
      |     ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:686:5: warning: KS01: Tag requires public declaration
  686 |     operator Z<2600>() const;
      |     ^
./sections.h:673:1: note: KS01: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:689:10: warning: KS07: Tag requires const method declaration
  689 |     void manipulator_2500();
      |          ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:690:10: warning: KS07: Tag requires const method declaration
  690 |     void aspect_2500();
      |          ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:691:16: warning: KS07: Tag requires const method declaration
  691 |     static int s_class_data_2500;
      |                ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:692:17: warning: KS07: Tag requires const method declaration
  692 |     static void s_class_method_2500();
      |                 ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:693:22: warning: KS07: Tag requires const method declaration
  693 |     static const int s_CONSTANT_2500 = 7;
      |                      ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:694:5: warning: KS09: Constructor or destructor requires CREATORS tag
  694 |     X(Z<2500>);
      |     ^
./sections.h:673:1: note: KS09: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:695:8: warning: KS07: Tag requires const method declaration
  695 |     X& operator=(Z<2500>);
      |        ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:696:9: warning: KS07: Tag requires const method declaration
  696 |     int d_data_2500;
      |         ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:697:17: warning: KS07: Tag requires const method declaration
  697 |     typedef int Type_2500;
      |                 ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:698:5: warning: KS07: Tag requires const method declaration
  698 |     operator Z<2500>();
      |     ^
./sections.h:673:1: note: KS07: Tag is here
  673 | // PUBLIC ACCESSORS
      | ^
./sections.h:703:10: warning: KS01: Tag requires public declaration
  703 |     void accessor_2400() const;
      |          ^
./sections.h:701:1: note: KS01: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:704:10: warning: KS01: Tag requires public declaration
  704 |     void manipulator_2400();
      |          ^
./sections.h:701:1: note: KS01: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:705:10: warning: KS01: Tag requires public declaration
  705 |     void aspect_2400();
      |          ^
./sections.h:701:1: note: KS01: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:706:16: warning: KS03: Tag requires function declaration
  706 |     static int s_class_data_2400;
      |                ^
./sections.h:701:1: note: KS03: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:707:17: warning: KS01: Tag requires public declaration
  707 |     static void s_class_method_2400();
      |                 ^
./sections.h:701:1: note: KS01: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:708:22: warning: KS03: Tag requires function declaration
  708 |     static const int s_CONSTANT_2400 = 7;
      |                      ^
./sections.h:701:1: note: KS03: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:709:5: warning: KS09: Constructor or destructor requires CREATORS tag
  709 |     X(Z<2400>);
      |     ^
./sections.h:701:1: note: KS09: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:710:8: warning: KS01: Tag requires public declaration
  710 |     X& operator=(Z<2400>);
      |        ^
./sections.h:701:1: note: KS01: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:711:9: warning: KS03: Tag requires function declaration
  711 |     int d_data_2400;
      |         ^
./sections.h:701:1: note: KS03: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:712:17: warning: KS03: Tag requires function declaration
  712 |     typedef int Type_2400;
      |                 ^
./sections.h:701:1: note: KS03: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:713:5: warning: KS01: Tag requires public declaration
  713 |     operator Z<2400>();
      |     ^
./sections.h:701:1: note: KS01: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:714:5: warning: KS01: Tag requires public declaration
  714 |     operator Z<2400>() const;
      |     ^
./sections.h:701:1: note: KS01: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:719:16: warning: KS03: Tag requires function declaration
  719 |     static int s_class_data_2300;
      |                ^
./sections.h:701:1: note: KS03: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:721:22: warning: KS03: Tag requires function declaration
  721 |     static const int s_CONSTANT_2300 = 7;
      |                      ^
./sections.h:701:1: note: KS03: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:722:5: warning: KS09: Constructor or destructor requires CREATORS tag
  722 |     X(Z<2300>);
      |     ^
./sections.h:701:1: note: KS09: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:724:9: warning: KS03: Tag requires function declaration
  724 |     int d_data_2300;
      |         ^
./sections.h:701:1: note: KS03: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:725:17: warning: KS03: Tag requires function declaration
  725 |     typedef int Type_2300;
      |                 ^
./sections.h:701:1: note: KS03: Tag is here
  701 | // PUBLIC ASPECTS
      | ^
./sections.h:731:10: warning: KS05: Tag requires static data field declaration
  731 |     void accessor_2200() const;
      |          ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:732:10: warning: KS05: Tag requires static data field declaration
  732 |     void manipulator_2200();
      |          ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:733:10: warning: KS05: Tag requires static data field declaration
  733 |     void aspect_2200();
      |          ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:734:16: warning: KS01: Tag requires public declaration
  734 |     static int s_class_data_2200;
      |                ^
./sections.h:729:1: note: KS01: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:735:17: warning: KS05: Tag requires static data field declaration
  735 |     static void s_class_method_2200();
      |                 ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:736:22: warning: KS01: Tag requires public declaration
  736 |     static const int s_CONSTANT_2200 = 7;
      |                      ^
./sections.h:729:1: note: KS01: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:737:5: warning: KS09: Constructor or destructor requires CREATORS tag
  737 |     X(Z<2200>);
      |     ^
./sections.h:729:1: note: KS09: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:738:8: warning: KS05: Tag requires static data field declaration
  738 |     X& operator=(Z<2200>);
      |        ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:739:9: warning: KS05: Tag requires static data field declaration
  739 |     int d_data_2200;
      |         ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:740:17: warning: KS05: Tag requires static data field declaration
  740 |     typedef int Type_2200;
      |                 ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:741:5: warning: KS05: Tag requires static data field declaration
  741 |     operator Z<2200>();
      |     ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:742:5: warning: KS05: Tag requires static data field declaration
  742 |     operator Z<2200>() const;
      |     ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:744:10: warning: KS05: Tag requires static data field declaration
  744 |     void accessor_2100() const;
      |          ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:745:10: warning: KS05: Tag requires static data field declaration
  745 |     void manipulator_2100();
      |          ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:746:10: warning: KS05: Tag requires static data field declaration
  746 |     void aspect_2100();
      |          ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:748:17: warning: KS05: Tag requires static data field declaration
  748 |     static void s_class_method_2100();
      |                 ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:750:5: warning: KS09: Constructor or destructor requires CREATORS tag
  750 |     X(Z<2100>);
      |     ^
./sections.h:729:1: note: KS09: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:751:8: warning: KS05: Tag requires static data field declaration
  751 |     X& operator=(Z<2100>);
      |        ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:752:9: warning: KS05: Tag requires static data field declaration
  752 |     int d_data_2100;
      |         ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:753:17: warning: KS05: Tag requires static data field declaration
  753 |     typedef int Type_2100;
      |                 ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:754:5: warning: KS05: Tag requires static data field declaration
  754 |     operator Z<2100>();
      |     ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:755:5: warning: KS05: Tag requires static data field declaration
  755 |     operator Z<2100>() const;
      |     ^
./sections.h:729:1: note: KS05: Tag is here
  729 | // PUBLIC CLASS DATA
      | ^
./sections.h:759:10: warning: KS11: Tag requires static method declaration
  759 |     void accessor_1900() const;
      |          ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:760:10: warning: KS11: Tag requires static method declaration
  760 |     void manipulator_1900();
      |          ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:761:10: warning: KS11: Tag requires static method declaration
  761 |     void aspect_1900();
      |          ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:762:16: warning: KS11: Tag requires static method declaration
  762 |     static int s_class_data_1900;
      |                ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:763:17: warning: KS01: Tag requires public declaration
  763 |     static void s_class_method_1900();
      |                 ^
./sections.h:757:1: note: KS01: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:764:22: warning: KS11: Tag requires static method declaration
  764 |     static const int s_CONSTANT_1900 = 7;
      |                      ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:765:5: warning: KS09: Constructor or destructor requires CREATORS tag
  765 |     X(Z<1900>);
      |     ^
./sections.h:757:1: note: KS09: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:766:8: warning: KS11: Tag requires static method declaration
  766 |     X& operator=(Z<1900>);
      |        ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:767:9: warning: KS11: Tag requires static method declaration
  767 |     int d_data_1900;
      |         ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:768:17: warning: KS11: Tag requires static method declaration
  768 |     typedef int Type_1900;
      |                 ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:769:5: warning: KS11: Tag requires static method declaration
  769 |     operator Z<1900>();
      |     ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:770:5: warning: KS11: Tag requires static method declaration
  770 |     operator Z<1900>() const;
      |     ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:772:10: warning: KS11: Tag requires static method declaration
  772 |     void accessor_1800() const;
      |          ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:773:10: warning: KS11: Tag requires static method declaration
  773 |     void manipulator_1800();
      |          ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:774:10: warning: KS11: Tag requires static method declaration
  774 |     void aspect_1800();
      |          ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:775:16: warning: KS11: Tag requires static method declaration
  775 |     static int s_class_data_1800;
      |                ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:777:22: warning: KS11: Tag requires static method declaration
  777 |     static const int s_CONSTANT_1800 = 7;
      |                      ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:778:5: warning: KS09: Constructor or destructor requires CREATORS tag
  778 |     X(Z<1800>);
      |     ^
./sections.h:757:1: note: KS09: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:779:8: warning: KS11: Tag requires static method declaration
  779 |     X& operator=(Z<1800>);
      |        ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:780:9: warning: KS11: Tag requires static method declaration
  780 |     int d_data_1800;
      |         ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:781:17: warning: KS11: Tag requires static method declaration
  781 |     typedef int Type_1800;
      |                 ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:782:5: warning: KS11: Tag requires static method declaration
  782 |     operator Z<1800>();
      |     ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:783:5: warning: KS11: Tag requires static method declaration
  783 |     operator Z<1800>() const;
      |     ^
./sections.h:757:1: note: KS11: Tag is here
  757 | // PUBLIC CLASS METHODS
      | ^
./sections.h:787:10: warning: KS10: Tag requires constant data declaration
  787 |     void accessor_1700() const;
      |          ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:788:10: warning: KS10: Tag requires constant data declaration
  788 |     void manipulator_1700();
      |          ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:789:10: warning: KS10: Tag requires constant data declaration
  789 |     void aspect_1700();
      |          ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:790:16: warning: KS10: Tag requires constant data declaration
  790 |     static int s_class_data_1700;
      |                ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:791:17: warning: KS10: Tag requires constant data declaration
  791 |     static void s_class_method_1700();
      |                 ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:792:22: warning: KS01: Tag requires public declaration
  792 |     static const int s_CONSTANT_1700 = 7;
      |                      ^
./sections.h:785:1: note: KS01: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:793:5: warning: KS09: Constructor or destructor requires CREATORS tag
  793 |     X(Z<1700>);
      |     ^
./sections.h:785:1: note: KS09: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:794:8: warning: KS10: Tag requires constant data declaration
  794 |     X& operator=(Z<1700>);
      |        ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:795:9: warning: KS10: Tag requires constant data declaration
  795 |     int d_data_1700;
      |         ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:796:17: warning: KS10: Tag requires constant data declaration
  796 |     typedef int Type_1700;
      |                 ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:797:5: warning: KS10: Tag requires constant data declaration
  797 |     operator Z<1700>();
      |     ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:798:5: warning: KS10: Tag requires constant data declaration
  798 |     operator Z<1700>() const;
      |     ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:800:10: warning: KS10: Tag requires constant data declaration
  800 |     void accessor_1600() const;
      |          ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:801:10: warning: KS10: Tag requires constant data declaration
  801 |     void manipulator_1600();
      |          ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:802:10: warning: KS10: Tag requires constant data declaration
  802 |     void aspect_1600();
      |          ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:803:16: warning: KS10: Tag requires constant data declaration
  803 |     static int s_class_data_1600;
      |                ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:804:17: warning: KS10: Tag requires constant data declaration
  804 |     static void s_class_method_1600();
      |                 ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:806:5: warning: KS09: Constructor or destructor requires CREATORS tag
  806 |     X(Z<1600>);
      |     ^
./sections.h:785:1: note: KS09: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:807:8: warning: KS10: Tag requires constant data declaration
  807 |     X& operator=(Z<1600>);
      |        ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:808:9: warning: KS10: Tag requires constant data declaration
  808 |     int d_data_1600;
      |         ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:809:17: warning: KS10: Tag requires constant data declaration
  809 |     typedef int Type_1600;
      |                 ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:810:5: warning: KS10: Tag requires constant data declaration
  810 |     operator Z<1600>();
      |     ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:811:5: warning: KS10: Tag requires constant data declaration
  811 |     operator Z<1600>() const;
      |     ^
./sections.h:785:1: note: KS10: Tag is here
  785 | // PUBLIC CONSTANTS
      | ^
./sections.h:815:10: warning: KS04: Tag requires instance data field declaration
  815 |     void accessor_1500() const;
      |          ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:816:10: warning: KS04: Tag requires instance data field declaration
  816 |     void manipulator_1500();
      |          ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:817:10: warning: KS04: Tag requires instance data field declaration
  817 |     void aspect_1500();
      |          ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:818:16: warning: KS04: Tag requires instance data field declaration
  818 |     static int s_class_data_1500;
      |                ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:819:17: warning: KS04: Tag requires instance data field declaration
  819 |     static void s_class_method_1500();
      |                 ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:820:22: warning: KS04: Tag requires instance data field declaration
  820 |     static const int s_CONSTANT_1500 = 7;
      |                      ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:821:5: warning: KS09: Constructor or destructor requires CREATORS tag
  821 |     X(Z<1500>);
      |     ^
./sections.h:813:1: note: KS09: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:822:8: warning: KS04: Tag requires instance data field declaration
  822 |     X& operator=(Z<1500>);
      |        ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:823:9: warning: KS01: Tag requires public declaration
  823 |     int d_data_1500;
      |         ^
./sections.h:813:1: note: KS01: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:824:17: warning: KS04: Tag requires instance data field declaration
  824 |     typedef int Type_1500;
      |                 ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:825:5: warning: KS04: Tag requires instance data field declaration
  825 |     operator Z<1500>();
      |     ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:826:5: warning: KS04: Tag requires instance data field declaration
  826 |     operator Z<1500>() const;
      |     ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:828:10: warning: KS04: Tag requires instance data field declaration
  828 |     void accessor_1400() const;
      |          ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:829:10: warning: KS04: Tag requires instance data field declaration
  829 |     void manipulator_1400();
      |          ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:830:10: warning: KS04: Tag requires instance data field declaration
  830 |     void aspect_1400();
      |          ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:831:16: warning: KS04: Tag requires instance data field declaration
  831 |     static int s_class_data_1400;
      |                ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:832:17: warning: KS04: Tag requires instance data field declaration
  832 |     static void s_class_method_1400();
      |                 ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:833:22: warning: KS04: Tag requires instance data field declaration
  833 |     static const int s_CONSTANT_1400 = 7;
      |                      ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:834:5: warning: KS09: Constructor or destructor requires CREATORS tag
  834 |     X(Z<1400>);
      |     ^
./sections.h:813:1: note: KS09: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:835:8: warning: KS04: Tag requires instance data field declaration
  835 |     X& operator=(Z<1400>);
      |        ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:837:17: warning: KS04: Tag requires instance data field declaration
  837 |     typedef int Type_1400;
      |                 ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:838:5: warning: KS04: Tag requires instance data field declaration
  838 |     operator Z<1400>();
      |     ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:839:5: warning: KS04: Tag requires instance data field declaration
  839 |     operator Z<1400>() const;
      |     ^
./sections.h:813:1: note: KS04: Tag is here
  813 | // PUBLIC DATA
      | ^
./sections.h:843:10: warning: KS04: Tag requires instance data field declaration
  843 |     void accessor_1300() const;
      |          ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:844:10: warning: KS04: Tag requires instance data field declaration
  844 |     void manipulator_1300();
      |          ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:845:10: warning: KS04: Tag requires instance data field declaration
  845 |     void aspect_1300();
      |          ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:846:16: warning: KS04: Tag requires instance data field declaration
  846 |     static int s_class_data_1300;
      |                ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:847:17: warning: KS04: Tag requires instance data field declaration
  847 |     static void s_class_method_1300();
      |                 ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:848:22: warning: KS04: Tag requires instance data field declaration
  848 |     static const int s_CONSTANT_1300 = 7;
      |                      ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:849:5: warning: KS09: Constructor or destructor requires CREATORS tag
  849 |     X(Z<1300>);
      |     ^
./sections.h:841:1: note: KS09: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:850:8: warning: KS04: Tag requires instance data field declaration
  850 |     X& operator=(Z<1300>);
      |        ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:851:9: warning: KS01: Tag requires public declaration
  851 |     int d_data_1300;
      |         ^
./sections.h:841:1: note: KS01: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:852:17: warning: KS04: Tag requires instance data field declaration
  852 |     typedef int Type_1300;
      |                 ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:853:5: warning: KS04: Tag requires instance data field declaration
  853 |     operator Z<1300>();
      |     ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:854:5: warning: KS04: Tag requires instance data field declaration
  854 |     operator Z<1300>() const;
      |     ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:856:10: warning: KS04: Tag requires instance data field declaration
  856 |     void accessor_1200() const;
      |          ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:857:10: warning: KS04: Tag requires instance data field declaration
  857 |     void manipulator_1200();
      |          ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:858:10: warning: KS04: Tag requires instance data field declaration
  858 |     void aspect_1200();
      |          ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:859:16: warning: KS04: Tag requires instance data field declaration
  859 |     static int s_class_data_1200;
      |                ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:860:17: warning: KS04: Tag requires instance data field declaration
  860 |     static void s_class_method_1200();
      |                 ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:861:22: warning: KS04: Tag requires instance data field declaration
  861 |     static const int s_CONSTANT_1200 = 7;
      |                      ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:862:5: warning: KS09: Constructor or destructor requires CREATORS tag
  862 |     X(Z<1200>);
      |     ^
./sections.h:841:1: note: KS09: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:863:8: warning: KS04: Tag requires instance data field declaration
  863 |     X& operator=(Z<1200>);
      |        ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:865:17: warning: KS04: Tag requires instance data field declaration
  865 |     typedef int Type_1200;
      |                 ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:866:5: warning: KS04: Tag requires instance data field declaration
  866 |     operator Z<1200>();
      |     ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:867:5: warning: KS04: Tag requires instance data field declaration
  867 |     operator Z<1200>() const;
      |     ^
./sections.h:841:1: note: KS04: Tag is here
  841 | // PUBLIC DATA MEMBERS
      | ^
./sections.h:871:10: warning: KS08: Tag requires non-const method declaration
  871 |     void accessor_1100() const;
      |          ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:872:10: warning: KS01: Tag requires public declaration
  872 |     void manipulator_1100();
      |          ^
./sections.h:869:1: note: KS01: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:873:10: warning: KS01: Tag requires public declaration
  873 |     void aspect_1100();
      |          ^
./sections.h:869:1: note: KS01: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:874:16: warning: KS08: Tag requires non-const method declaration
  874 |     static int s_class_data_1100;
      |                ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:875:17: warning: KS01: Tag requires public declaration
  875 |     static void s_class_method_1100();
      |                 ^
./sections.h:869:1: note: KS01: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:876:22: warning: KS08: Tag requires non-const method declaration
  876 |     static const int s_CONSTANT_1100 = 7;
      |                      ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:877:5: warning: KS09: Constructor or destructor requires CREATORS tag
  877 |     X(Z<1100>);
      |     ^
./sections.h:869:1: note: KS09: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:878:8: warning: KS01: Tag requires public declaration
  878 |     X& operator=(Z<1100>);
      |        ^
./sections.h:869:1: note: KS01: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:879:9: warning: KS08: Tag requires non-const method declaration
  879 |     int d_data_1100;
      |         ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:880:17: warning: KS08: Tag requires non-const method declaration
  880 |     typedef int Type_1100;
      |                 ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:881:5: warning: KS01: Tag requires public declaration
  881 |     operator Z<1100>();
      |     ^
./sections.h:869:1: note: KS01: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:882:5: warning: KS08: Tag requires non-const method declaration
  882 |     operator Z<1100>() const;
      |     ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:884:10: warning: KS08: Tag requires non-const method declaration
  884 |     void accessor_900() const;
      |          ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:887:16: warning: KS08: Tag requires non-const method declaration
  887 |     static int s_class_data_900;
      |                ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:889:22: warning: KS08: Tag requires non-const method declaration
  889 |     static const int s_CONSTANT_900 = 7;
      |                      ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:890:5: warning: KS09: Constructor or destructor requires CREATORS tag
  890 |     X(Z<900>);
      |     ^
./sections.h:869:1: note: KS09: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:892:9: warning: KS08: Tag requires non-const method declaration
  892 |     int d_data_900;
      |         ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:893:17: warning: KS08: Tag requires non-const method declaration
  893 |     typedef int Type_900;
      |                 ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:895:5: warning: KS08: Tag requires non-const method declaration
  895 |     operator Z<900>() const;
      |     ^
./sections.h:869:1: note: KS08: Tag is here
  869 | // PUBLIC FUNCTIONS
      | ^
./sections.h:899:10: warning: KS08: Tag requires non-const method declaration
  899 |     void accessor_800() const;
      |          ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:900:10: warning: KS01: Tag requires public declaration
  900 |     void manipulator_800();
      |          ^
./sections.h:897:1: note: KS01: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:901:10: warning: KS01: Tag requires public declaration
  901 |     void aspect_800();
      |          ^
./sections.h:897:1: note: KS01: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:902:16: warning: KS08: Tag requires non-const method declaration
  902 |     static int s_class_data_800;
      |                ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:903:17: warning: KS01: Tag requires public declaration
  903 |     static void s_class_method_800();
      |                 ^
./sections.h:897:1: note: KS01: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:904:22: warning: KS08: Tag requires non-const method declaration
  904 |     static const int s_CONSTANT_800 = 7;
      |                      ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:905:5: warning: KS09: Constructor or destructor requires CREATORS tag
  905 |     X(Z<800>);
      |     ^
./sections.h:897:1: note: KS09: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:906:8: warning: KS01: Tag requires public declaration
  906 |     X& operator=(Z<800>);
      |        ^
./sections.h:897:1: note: KS01: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:907:9: warning: KS08: Tag requires non-const method declaration
  907 |     int d_data_800;
      |         ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:908:17: warning: KS08: Tag requires non-const method declaration
  908 |     typedef int Type_800;
      |                 ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:909:5: warning: KS01: Tag requires public declaration
  909 |     operator Z<800>();
      |     ^
./sections.h:897:1: note: KS01: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:910:5: warning: KS08: Tag requires non-const method declaration
  910 |     operator Z<800>() const;
      |     ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:912:10: warning: KS08: Tag requires non-const method declaration
  912 |     void accessor_700() const;
      |          ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:915:16: warning: KS08: Tag requires non-const method declaration
  915 |     static int s_class_data_700;
      |                ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:917:22: warning: KS08: Tag requires non-const method declaration
  917 |     static const int s_CONSTANT_700 = 7;
      |                      ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:918:5: warning: KS09: Constructor or destructor requires CREATORS tag
  918 |     X(Z<700>);
      |     ^
./sections.h:897:1: note: KS09: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:920:9: warning: KS08: Tag requires non-const method declaration
  920 |     int d_data_700;
      |         ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:921:17: warning: KS08: Tag requires non-const method declaration
  921 |     typedef int Type_700;
      |                 ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:923:5: warning: KS08: Tag requires non-const method declaration
  923 |     operator Z<700>() const;
      |     ^
./sections.h:897:1: note: KS08: Tag is here
  897 | // PUBLIC MANIPULATORS
      | ^
./sections.h:927:10: warning: KS14: Tag requires conversion operator declaration
  927 |     void accessor_400() const;
      |          ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:928:10: warning: KS14: Tag requires conversion operator declaration
  928 |     void manipulator_400();
      |          ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:929:10: warning: KS14: Tag requires conversion operator declaration
  929 |     void aspect_400();
      |          ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:930:16: warning: KS14: Tag requires conversion operator declaration
  930 |     static int s_class_data_400;
      |                ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:931:17: warning: KS14: Tag requires conversion operator declaration
  931 |     static void s_class_method_400();
      |                 ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:932:22: warning: KS14: Tag requires conversion operator declaration
  932 |     static const int s_CONSTANT_400 = 7;
      |                      ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:933:5: warning: KS09: Constructor or destructor requires CREATORS tag
  933 |     X(Z<400>);
      |     ^
./sections.h:925:1: note: KS09: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:934:8: warning: KS14: Tag requires conversion operator declaration
  934 |     X& operator=(Z<400>);
      |        ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:935:9: warning: KS14: Tag requires conversion operator declaration
  935 |     int d_data_400;
      |         ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:936:17: warning: KS14: Tag requires conversion operator declaration
  936 |     typedef int Type_400;
      |                 ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:937:5: warning: KS01: Tag requires public declaration
  937 |     operator Z<400>();
      |     ^
./sections.h:925:1: note: KS01: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:938:5: warning: KS01: Tag requires public declaration
  938 |     operator Z<400>() const;
      |     ^
./sections.h:925:1: note: KS01: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:940:10: warning: KS14: Tag requires conversion operator declaration
  940 |     void accessor_300() const;
      |          ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:941:10: warning: KS14: Tag requires conversion operator declaration
  941 |     void manipulator_300();
      |          ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:942:10: warning: KS14: Tag requires conversion operator declaration
  942 |     void aspect_300();
      |          ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:943:16: warning: KS14: Tag requires conversion operator declaration
  943 |     static int s_class_data_300;
      |                ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:944:17: warning: KS14: Tag requires conversion operator declaration
  944 |     static void s_class_method_300();
      |                 ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:945:22: warning: KS14: Tag requires conversion operator declaration
  945 |     static const int s_CONSTANT_300 = 7;
      |                      ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:946:5: warning: KS09: Constructor or destructor requires CREATORS tag
  946 |     X(Z<300>);
      |     ^
./sections.h:925:1: note: KS09: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:947:8: warning: KS14: Tag requires conversion operator declaration
  947 |     X& operator=(Z<300>);
      |        ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:948:9: warning: KS14: Tag requires conversion operator declaration
  948 |     int d_data_300;
      |         ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:949:17: warning: KS14: Tag requires conversion operator declaration
  949 |     typedef int Type_300;
      |                 ^
./sections.h:925:1: note: KS14: Tag is here
  925 | // PUBLIC TRAITS
      | ^
./sections.h:955:10: warning: KS06: Tag requires type declaration
  955 |     void accessor_200() const;
      |          ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:956:10: warning: KS06: Tag requires type declaration
  956 |     void manipulator_200();
      |          ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:957:10: warning: KS06: Tag requires type declaration
  957 |     void aspect_200();
      |          ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:958:16: warning: KS06: Tag requires type declaration
  958 |     static int s_class_data_200;
      |                ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:959:17: warning: KS06: Tag requires type declaration
  959 |     static void s_class_method_200();
      |                 ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:960:22: warning: KS06: Tag requires type declaration
  960 |     static const int s_CONSTANT_200 = 7;
      |                      ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:961:5: warning: KS09: Constructor or destructor requires CREATORS tag
  961 |     X(Z<200>);
      |     ^
./sections.h:953:1: note: KS09: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:962:8: warning: KS06: Tag requires type declaration
  962 |     X& operator=(Z<200>);
      |        ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:963:9: warning: KS06: Tag requires type declaration
  963 |     int d_data_200;
      |         ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:964:17: warning: KS01: Tag requires public declaration
  964 |     typedef int Type_200;
      |                 ^
./sections.h:953:1: note: KS01: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:965:5: warning: KS06: Tag requires type declaration
  965 |     operator Z<200>();
      |     ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:966:5: warning: KS06: Tag requires type declaration
  966 |     operator Z<200>() const;
      |     ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:968:10: warning: KS06: Tag requires type declaration
  968 |     void accessor_100() const;
      |          ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:969:10: warning: KS06: Tag requires type declaration
  969 |     void manipulator_100();
      |          ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:970:10: warning: KS06: Tag requires type declaration
  970 |     void aspect_100();
      |          ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:971:16: warning: KS06: Tag requires type declaration
  971 |     static int s_class_data_100;
      |                ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:972:17: warning: KS06: Tag requires type declaration
  972 |     static void s_class_method_100();
      |                 ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:973:22: warning: KS06: Tag requires type declaration
  973 |     static const int s_CONSTANT_100 = 7;
      |                      ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:974:5: warning: KS09: Constructor or destructor requires CREATORS tag
  974 |     X(Z<100>);
      |     ^
./sections.h:953:1: note: KS09: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:975:8: warning: KS06: Tag requires type declaration
  975 |     X& operator=(Z<100>);
      |        ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:976:9: warning: KS06: Tag requires type declaration
  976 |     int d_data_100;
      |         ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:978:5: warning: KS06: Tag requires type declaration
  978 |     operator Z<100>();
      |     ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
./sections.h:979:5: warning: KS06: Tag requires type declaration
  979 |     operator Z<100>() const;
      |     ^
./sections.h:953:1: note: KS06: Tag is here
  953 | // PUBLIC TYPES
      | ^
738 warnings generated.
