bdebuildtarget.cpp:3:8: warning: AQK02: Use of BDE_BUILD_TARGET_EXC macro requires inclusion of <bsls_buildtarget.h>
    3 | #ifdef BDE_BUILD_TARGET_EXC
      |        ^
bdebuildtarget.cpp:5:8: warning: AQK02: Use of BDE_BUILD_TARGET_NO_EXC macro requires inclusion of <bsls_buildtarget.h>
    5 | #ifdef BDE_BUILD_TARGET_NO_EXC
      |        ^
bdebuildtarget.cpp:7:8: warning: AQK02: Use of BDE_BUILD_TARGET_MT macro requires inclusion of <bsls_buildtarget.h>
    7 | #ifdef BDE_BUILD_TARGET_MT
      |        ^
bdebuildtarget.cpp:9:8: warning: AQK02: Use of BDE_BUILD_TARGET_NO_MT macro requires inclusion of <bsls_buildtarget.h>
    9 | #ifdef BDE_BUILD_TARGET_NO_MT
      |        ^
bdebuildtarget.cpp:12:9: warning: AQK02: Use of BDE_BUILD_TARGET_EXC macro requires inclusion of <bsls_buildtarget.h>
   12 | #ifndef BDE_BUILD_TARGET_EXC
      |         ^
bdebuildtarget.cpp:14:9: warning: AQK02: Use of BDE_BUILD_TARGET_NO_EXC macro requires inclusion of <bsls_buildtarget.h>
   14 | #ifndef BDE_BUILD_TARGET_NO_EXC
      |         ^
bdebuildtarget.cpp:16:9: warning: AQK02: Use of BDE_BUILD_TARGET_MT macro requires inclusion of <bsls_buildtarget.h>
   16 | #ifndef BDE_BUILD_TARGET_MT
      |         ^
bdebuildtarget.cpp:18:9: warning: AQK02: Use of BDE_BUILD_TARGET_NO_MT macro requires inclusion of <bsls_buildtarget.h>
   18 | #ifndef BDE_BUILD_TARGET_NO_MT
      |         ^
bdebuildtarget.cpp:21:13: warning: AQK02: Use of BDE_BUILD_TARGET_EXC macro requires inclusion of <bsls_buildtarget.h>
   21 | #if defined(BDE_BUILD_TARGET_EXC) || defined(BDE_BUILD_TARGET_NO_EXC) || \
      |             ^
bdebuildtarget.cpp:21:46: warning: AQK02: Use of BDE_BUILD_TARGET_NO_EXC macro requires inclusion of <bsls_buildtarget.h>
   21 | #if defined(BDE_BUILD_TARGET_EXC) || defined(BDE_BUILD_TARGET_NO_EXC) || \
      |                                              ^
bdebuildtarget.cpp:22:13: warning: AQK02: Use of BDE_BUILD_TARGET_MT macro requires inclusion of <bsls_buildtarget.h>
   22 |     defined(BDE_BUILD_TARGET_MT)  || defined(BDE_BUILD_TARGET_NO_MT)
      |             ^
bdebuildtarget.cpp:22:46: warning: AQK02: Use of BDE_BUILD_TARGET_NO_MT macro requires inclusion of <bsls_buildtarget.h>
   22 |     defined(BDE_BUILD_TARGET_MT)  || defined(BDE_BUILD_TARGET_NO_MT)
      |                                              ^
12 warnings generated.
