init.cpp:7:5: warning: AQa01: Global variable 'extern_should_be_runtime_call' of type 'int' with runtime initialization in translation unit without main()
    7 | int extern_should_be_runtime_call = function();
      |     ^
init.cpp:8:3: warning: AQa01: Global variable 'extern_should_be_runtime_constructed' of type 'C' with runtime initialization in translation unit without main()
    8 | C extern_should_be_runtime_constructed;
      |   ^
init.cpp:9:5: warning: AQa01: Global variable 'extern_should_be_runtime_expression' of type 'int' with runtime initialization in translation unit without main()
    9 | int extern_should_be_runtime_expression = *pointer;
      |     ^
init.cpp:15:5: warning: AQa01: Global variable 'extern_should_be_runtime_call' of type 'int' with runtime initialization in translation unit without main()
   15 | int extern_should_be_runtime_call = function();
      |     ^
init.cpp:16:3: warning: AQa01: Global variable 'extern_should_be_runtime_constructed' of type 'C' with runtime initialization in translation unit without main()
   16 | C extern_should_be_runtime_constructed;
      |   ^
init.cpp:17:5: warning: AQa01: Global variable 'extern_should_be_runtime_expression' of type 'int' with runtime initialization in translation unit without main()
   17 | int extern_should_be_runtime_expression = *pointer;
      |     ^
init.cpp:24:5: warning: AQa01: Global variable 'extern_should_be_runtime_call' of type 'int' with runtime initialization in translation unit without main()
   24 | int extern_should_be_runtime_call = function();
      |     ^
init.cpp:25:3: warning: AQa01: Global variable 'extern_should_be_runtime_constructed' of type 'C' with runtime initialization in translation unit without main()
   25 | C extern_should_be_runtime_constructed;
      |   ^
init.cpp:26:5: warning: AQa01: Global variable 'extern_should_be_runtime_expression' of type 'int' with runtime initialization in translation unit without main()
   26 | int extern_should_be_runtime_expression = *pointer;
      |     ^
init.cpp:32:12: warning: AQa01: Global variable 'static_should_be_runtime_call' of type 'int' with runtime initialization in translation unit without main()
   32 | static int static_should_be_runtime_call = function();
      |            ^
init.cpp:33:10: warning: AQa01: Global variable 'static_should_be_runtime_constructed' of type 'C' with runtime initialization in translation unit without main()
   33 | static C static_should_be_runtime_constructed;
      |          ^
init.cpp:34:12: warning: AQa01: Global variable 'static_should_be_runtime_expression' of type 'int' with runtime initialization in translation unit without main()
   34 | static int static_should_be_runtime_expression = *pointer;
      |            ^
init.cpp:59:8: warning: AQa01: Global variable 'should_be_runtime_call' of type 'int' with runtime initialization in translation unit without main()
   59 | int D::should_be_runtime_call = function();
      |        ^
init.cpp:60:6: warning: AQa01: Global variable 'should_be_runtime_constructed' of type 'C' with runtime initialization in translation unit without main()
   60 | C D::should_be_runtime_constructed;
      |      ^
init.cpp:61:8: warning: AQa01: Global variable 'should_be_runtime_expression' of type 'int' with runtime initialization in translation unit without main()
   61 | int D::should_be_runtime_expression = *pointer;
      |        ^
init.cpp:77:30: warning: AQa01: Global variable 'should_be_runtime_call' of type 'int' with runtime initialization in translation unit without main()
   77 | template <class T> int E<T>::should_be_runtime_call = function();
      |                              ^
init.cpp:78:28: warning: AQa01: Global variable 'should_be_runtime_constructed' of type 'C' with runtime initialization in translation unit without main()
   78 | template <class T> C E<T>::should_be_runtime_constructed;
      |                            ^
init.cpp:79:30: warning: AQa01: Global variable 'should_be_runtime_expression' of type 'int' with runtime initialization in translation unit without main()
   79 | template <class T> int E<T>::should_be_runtime_expression = *pointer;
      |                              ^
18 warnings generated.
