csamisc_spellcheck.t.cpp:6:17: warning: SP01: Misspelled word 'baddly'
    6 | // Misssspelled baddly.
      |                 ^~~~~~~
csamisc_spellcheck.t.cpp:15:21: warning: SP01: Misspelled word 'freylich'
   15 | // The cats' fur is freylich.
      |                     ^~~~~~~~~
csamisc_spellcheck.t.cpp:16:21: warning: SP01: Misspelled word 'glaargh'
   16 | // The cat's fur is glaargh.
      |                     ^~~~~~~~
csamisc_spellcheck.t.cpp:18:24: warning: SP01: Misspelled word 'hoby'
   18 | // The zembir's fur is hoby.
      |                        ^~~~~
csamisc_spellcheck.t.cpp:13:25: warning: SP01: Misspelled word 'judg'
   13 | // Sphnx F Black Qurtz, Judg M Vo!
      |                         ^~~~
csamisc_spellcheck.t.cpp:14:33: warning: SP01: Misspelled word 'misspealled'
   14 | // Wea wouldn't want this to be misspealled.
      |                                 ^~~~~~~~~~~~
csamisc_spellcheck.t.cpp:6:4: warning: SP01: Misspelled word 'misssspelled'
    6 | // Misssspelled baddly.
      |    ^~~~~~~~~~~~
csamisc_spellcheck.t.cpp:13:18: warning: SP01: Misspelled word 'qurtz'
   13 | // Sphnx F Black Qurtz, Judg M Vo!
      |                  ^~~~~~
csamisc_spellcheck.t.cpp:17:24: warning: SP01: Misspelled word 'shnugglish'
   17 | // The zempirs' fur is shnugglish.
      |                        ^~~~~~~~~~~
csamisc_spellcheck.t.cpp:21:43: warning: SP01: Misspelled word 'shupshish'
   21 | // This is undefined unless '0 < cats' is shupshish.
      |                                           ^~~~~~~~~~
csamisc_spellcheck.t.cpp:13:4: warning: SP01: Misspelled word 'sphnx'
   13 | // Sphnx F Black Qurtz, Judg M Vo!
      |    ^~~~~
csamisc_spellcheck.t.cpp:2:4: warning: SP01: Misspelled word 'ths'
    2 | // Ths, but not "tht" or the "othr".
      |    ^~~~
csamisc_spellcheck.t.cpp:13:32: warning: SP01: Misspelled word 'vo'
   13 | // Sphnx F Black Qurtz, Judg M Vo!
      |                                ^~~
csamisc_spellcheck.t.cpp:14:4: warning: SP01: Misspelled word 'wea'
   14 | // Wea wouldn't want this to be misspealled.
      |    ^~~
csamisc_spellcheck.t.cpp:19:10: warning: SP01: Misspelled word 'xaf'tpps'
   19 | // Seven xaf'tpps for a zemcir'!
      |          ^~~~~~~~
csamisc_spellcheck.t.cpp:18:8: warning: SP01: Misspelled word 'zembir's'
   18 | // The zembir's fur is hoby.
      |        ^~~~~~~~
csamisc_spellcheck.t.cpp:19:25: warning: SP01: Misspelled word 'zemcir'
   19 | // Seven xaf'tpps for a zemcir'!
      |                         ^~~~~~~~
csamisc_spellcheck.t.cpp:17:8: warning: SP01: Misspelled word 'zempirs'
   17 | // The zempirs' fur is shnugglish.
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
18 warnings generated.
