In file included from csatr_nesteddeclarations.t.cpp:3:
./csatr_nesteddeclarations.t.hpp:20:8: warning: TR04: Declaration of 'nesteddeclarations_bad_global_struct' at global scope
   20 | struct nesteddeclarations_bad_global_struct
      | ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   21 | {
      | ~
   22 |     int member;
      |     ~~~~~~~~~~~
   23 |     void method();
      |     ~~~~~~~~~~~~~~
   24 |     struct nested {};
      |     ~~~~~~~~~~~~~~~~~
   25 | };
      | ~
./csatr_nesteddeclarations.t.hpp:26:6: warning: TR04: Declaration of 'nesteddeclarations_bad_global_function' at global scope
   26 | void nesteddeclarations_bad_global_function();
      | ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_nesteddeclarations.t.hpp:27:5: warning: TR04: Declaration of 'nesteddeclarations_bad_global_variable' at global scope
   27 | int nesteddeclarations_bad_global_variable;
      | ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_nesteddeclarations.t.hpp:32:12: warning: TR04: Declaration of 'nesteddeclarations_bad_bde_verify_struct' not within package namespace 'bde_verify::csatr'
   32 |     struct nesteddeclarations_bad_bde_verify_struct
      |     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   33 |     {
      |     ~
   34 |         int member;
      |         ~~~~~~~~~~~
   35 |         void method();
      |         ~~~~~~~~~~~~~~
   36 |         struct nested {};
      |         ~~~~~~~~~~~~~~~~~
   37 |     };
      |     ~
./csatr_nesteddeclarations.t.hpp:38:10: warning: TR04: Declaration of 'nesteddeclarations_bad_bde_verify_function' not within package namespace 'bde_verify::csatr'
   38 |     void nesteddeclarations_bad_bde_verify_function();
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_nesteddeclarations.t.hpp:39:9: warning: TR04: Declaration of 'nesteddeclarations_bad_bde_verify_variable' not within package namespace 'bde_verify::csatr'
   39 |     int nesteddeclarations_bad_bde_verify_variable;
      |     ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_nesteddeclarations.t.hpp:44:16: warning: TR04: Declaration of 'nesteddeclarations_bad_bde_verify_csamisc_struct' not within package namespace 'bde_verify::csatr'
   44 |         struct nesteddeclarations_bad_bde_verify_csamisc_struct
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   45 |         {
      |         ~
   46 |             int member;
      |             ~~~~~~~~~~~
   47 |             void method();
      |             ~~~~~~~~~~~~~~
   48 |             struct nested {};
      |             ~~~~~~~~~~~~~~~~~
   49 |         };
      |         ~
./csatr_nesteddeclarations.t.hpp:50:14: warning: TR04: Declaration of 'nesteddeclarations_bad_bde_verify_csamisc_function' not within package namespace 'bde_verify::csatr'
   50 |         void nesteddeclarations_bad_bde_verify_csamisc_function();
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./csatr_nesteddeclarations.t.hpp:51:13: warning: TR04: Declaration of 'nesteddeclarations_bad_bde_verify_csamisc_variable' not within package namespace 'bde_verify::csatr'
   51 |         int nesteddeclarations_bad_bde_verify_csamisc_variable;
      |         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:8:8: warning: TR04: Declaration of 'bad_global_struct1' at global scope
    8 | struct bad_global_struct1;
      | ~~~~~~~^~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:9:8: warning: TR04: Declaration of 'bad_global_struct2' at global scope
    9 | struct bad_global_struct2 {};
      | ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:10:5: warning: TR04: Declaration of 'bad_global' at global scope
   10 | int bad_global = 0;
      | ~~~~^~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:11:6: warning: TR04: Declaration of 'bad_global_function' at global scope
   11 | void bad_global_function() {}
      | ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:23:12: warning: TR04: Declaration of 'bad_csatr_struct1' not within package namespace 'bde_verify::csatr'
   23 |     struct bad_csatr_struct1;
      |     ~~~~~~~^~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:24:12: warning: TR04: Declaration of 'bad_csatr_struct2' not within package namespace 'bde_verify::csatr'
   24 |     struct bad_csatr_struct2 {};
      |     ~~~~~~~^~~~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:25:9: warning: TR04: Declaration of 'bad_csatr_variable' not within package namespace 'bde_verify::csatr'
   25 |     int bad_csatr_variable = 0;
      |     ~~~~^~~~~~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:26:10: warning: TR04: Declaration of 'bad_csatr_function' not within package namespace 'bde_verify::csatr'
   26 |     void bad_csatr_function() {}
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:41:16: warning: TR04: Declaration of 'bad_top_csatr_struct1' not within package namespace 'bde_verify::csatr'
   41 |         struct bad_top_csatr_struct1;
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:42:16: warning: TR04: Declaration of 'bad_top_csatr_struct2' not within package namespace 'bde_verify::csatr'
   42 |         struct bad_top_csatr_struct2 {};
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:43:13: warning: TR04: Declaration of 'bad_top_csatr_variable' not within package namespace 'bde_verify::csatr'
   43 |         int bad_top_csatr_variable = 0;
      |         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
csatr_nesteddeclarations.t.cpp:44:14: warning: TR04: Declaration of 'bad_top_csatr_function' not within package namespace 'bde_verify::csatr'
   44 |         void bad_top_csatr_function() {}
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
21 warnings generated.
