csastil_uppernames.v.cpp:9:5: warning: UC01: Name should not be all upper-case
    9 | int AA;
      |     ^
csastil_uppernames.v.cpp:11:6: warning: UC01: Name should not be all upper-case
   11 | void BB()
      |      ^
csastil_uppernames.v.cpp:13:9: warning: UC01: Name should not be all upper-case
   13 |     int BB_AA;
      |         ^
csastil_uppernames.v.cpp:14:12: warning: UC01: Name should not be all upper-case
   14 |     struct BB_CC
      |            ^
csastil_uppernames.v.cpp:19:8: warning: UC01: Name should not be all upper-case
   19 | struct CC
      |        ^
csastil_uppernames.v.cpp:21:9: warning: UC01: Name should not be all upper-case
   21 |     int CC_AA;
      |         ^
csastil_uppernames.v.cpp:22:35: warning: UC01: Name should not be all upper-case
   22 |     template <class CC_DD> struct CC_EE { };
      |                                   ^
csastil_uppernames.v.cpp:27:28: warning: UC01: Name should not be all upper-case
   27 | template <class DD> struct EE
      |                            ^
csastil_uppernames.v.cpp:29:9: warning: UC01: Name should not be all upper-case
   29 |     int EE_AA;
      |         ^
csastil_uppernames.v.cpp:30:12: warning: UC01: Name should not be all upper-case
   30 |     struct EE_CC  { };
      |            ^
csastil_uppernames.v.cpp:31:35: warning: UC01: Name should not be all upper-case
   31 |     template <class EE_DD> struct EE_EE { };
      |                                   ^
csastil_uppernames.v.cpp:32:35: warning: UC01: Name should not be all upper-case
   32 |     template <class EE_FF> struct EE_GG;
      |                                   ^
csastil_uppernames.v.cpp:40:40: warning: UC01: Name should not be all upper-case
   40 | struct bde_verify::csastil::EE<EE_HH>::EE_GG
      |                                        ^
csastil_uppernames.v.cpp:42:11: warning: UC01: Name should not be all upper-case
   42 |     EE_HH JJ;
      |           ^
csastil_uppernames.v.cpp:43:11: warning: UC01: Name should not be all upper-case
   43 |     EE_II KK;
      |           ^
15 warnings generated.
