h.cpp:81:3: warning: MA02: Allocator not passed to member d_last
   81 | : d_last()
      |   ^~~~~~~~
h.cpp:82:3: warning: MA02: Allocator not passed to member d_first
   82 | , d_first()
      |   ^~~~~~~~~
h.cpp:87:3: warning: MA02: Allocator not passed to member d_last
   87 | : d_last(other.d_last)
      |   ^~~~~~~~~~~~~~~~~~~~
h.cpp:88:3: warning: MA02: Allocator not passed to member d_first
   88 | , d_first(other.d_first)
      |   ^~~~~~~~~~~~~~~~~~~~~~
h.cpp:93:3: warning: MA02: Allocator not passed to member d_last
   93 | : d_last()
      |   ^~~~~~~~
h.cpp:94:3: warning: MA02: Allocator not passed to member d_first
   94 | , d_first()
      |   ^~~~~~~~~
h.cpp:99:3: warning: MA02: Allocator not passed to member d_last
   99 | : d_last(other.d_last)
      |   ^~~~~~~~~~~~~~~~~~~~
h.cpp:100:3: warning: MA02: Allocator not passed to member d_first
  100 | , d_first(other.d_first)
      |   ^~~~~~~~~~~~~~~~~~~~~~
8 warnings generated.
