parms.cpp:17:11: warning: IND05: Template parameters should be all on a single line or each on a separate line
   17 |           class C>
      |           ^
parms.cpp:20:15: warning: IND06: Template parameter names should align vertically
   20 | template <int A,
      |               ^
parms.cpp:21:20: note: IND06: Rightmost name is here
   21 |           unsigned B>
      |                    ^
parms.cpp:25:9: warning: IND06: Template parameter names should align vertically
   25 |     int A,
      |         ^
parms.cpp:26:14: note: IND06: Rightmost name is here
   26 |     unsigned B
      |              ^
parms.cpp:31:11: warning: IND02: Function parameters should be all on a single line or each on a separate line
   31 |           class C);
      |           ^
parms.cpp:33:12: warning: IND03: Function parameter names should align vertically
   33 | void f(int A,
      |            ^
parms.cpp:34:20: note: IND03: Rightmost name is here
   34 |           unsigned B);
      |                    ^
parms.cpp:37:9: warning: IND03: Function parameter names should align vertically
   37 |     int A,
      |         ^
parms.cpp:38:14: note: IND03: Rightmost name is here
   38 |     unsigned B
      |              ^
parms.cpp:41:12: warning: IND03: Function parameter names should align vertically
   41 | void f(int A,
      |            ^
parms.cpp:42:14: note: IND03: Rightmost name is here
   42 |     unsigned B
      |              ^
parms.cpp:31:11: warning: IND01: Possibly mis-indented line
   31 |           class C);
      |           ^
parms.cpp:31:11: note: IND01: Correct version may be
       class C);
parms.cpp:34:11: warning: IND01: Possibly mis-indented line
   34 |           unsigned B);
      |           ^
parms.cpp:34:11: note: IND01: Correct version may be
       unsigned B);
parms.cpp:37:5: warning: IND01: Possibly mis-indented line
   37 |     int A,
      |     ^
parms.cpp:37:5: note: IND01: Correct version may be
                                                                     int A,
parms.cpp:42:5: warning: IND01: Possibly mis-indented line
   42 |     unsigned B
      |     ^
parms.cpp:42:5: note: IND01: Correct version may be
       unsigned B
11 warnings generated.
