decls.cpp:5:9: warning: IND04: Declarators on consecutive lines must be aligned
    5 |     int bb;
      |         ^
decls.cpp:4:10: note: IND04: Rightmost declarator is here
    4 |     char aaaa;
      |          ^
decls.cpp:7:12: warning: IND04: Declarators on consecutive lines must be aligned
    7 |     double ddddd;
      |            ^
decls.cpp:9:14: note: IND04: Rightmost declarator is here
    9 |     unsigned gggggg;
      |              ^
decls.cpp:8:11: warning: IND04: Declarators on consecutive lines must be aligned
    8 |     float ee;
      |           ^
decls.cpp:9:14: note: IND04: Rightmost declarator is here
    9 |     unsigned gggggg;
      |              ^
decls.cpp:16:11: warning: IND04: Declarators on consecutive lines must be aligned
   16 |     char *mmmm;
      |           ^
decls.cpp:18:13: note: IND04: Rightmost declarator is here
   18 |     double& ooooooooo = ddddd;
      |             ^
decls.cpp:17:9: warning: IND04: Declarators on consecutive lines must be aligned
   17 |     int nnnnnn;
      |         ^
decls.cpp:18:13: note: IND04: Rightmost declarator is here
   18 |     double& ooooooooo = ddddd;
      |             ^
decls.cpp:28:9: warning: IND04: Declarators on consecutive lines must be aligned
   28 |     int bb;
      |         ^
decls.cpp:27:10: note: IND04: Rightmost declarator is here
   27 |     char aaaa;
      |          ^
decls.cpp:30:12: warning: IND04: Declarators on consecutive lines must be aligned
   30 |     double ddddd;
      |            ^
decls.cpp:32:14: note: IND04: Rightmost declarator is here
   32 |     unsigned gggggg;
      |              ^
decls.cpp:31:11: warning: IND04: Declarators on consecutive lines must be aligned
   31 |     float ee;
      |           ^
decls.cpp:32:14: note: IND04: Rightmost declarator is here
   32 |     unsigned gggggg;
      |              ^
decls.cpp:39:11: warning: IND04: Declarators on consecutive lines must be aligned
   39 |     char *mmmm;
      |           ^
decls.cpp:41:13: note: IND04: Rightmost declarator is here
   41 |     double& ooooooooo = ddddd;
      |             ^
decls.cpp:40:9: warning: IND04: Declarators on consecutive lines must be aligned
   40 |     int nnnnnn;
      |         ^
decls.cpp:41:13: note: IND04: Rightmost declarator is here
   41 |     double& ooooooooo = ddddd;
      |             ^
decls.cpp:49:5: warning: IND04: Declarators on consecutive lines must be aligned
   49 | int bb;
      |     ^
decls.cpp:48:6: note: IND04: Rightmost declarator is here
   48 | char aaaa;
      |      ^
decls.cpp:51:8: warning: IND04: Declarators on consecutive lines must be aligned
   51 | double ddddd;
      |        ^
decls.cpp:53:10: note: IND04: Rightmost declarator is here
   53 | unsigned gggggg;
      |          ^
decls.cpp:52:7: warning: IND04: Declarators on consecutive lines must be aligned
   52 | float ee;
      |       ^
decls.cpp:53:10: note: IND04: Rightmost declarator is here
   53 | unsigned gggggg;
      |          ^
decls.cpp:60:7: warning: IND04: Declarators on consecutive lines must be aligned
   60 | char *mmmm;
      |       ^
decls.cpp:62:9: note: IND04: Rightmost declarator is here
   62 | double& ooooooooo = ddddd;
      |         ^
decls.cpp:61:5: warning: IND04: Declarators on consecutive lines must be aligned
   61 | int nnnnnn;
      |     ^
decls.cpp:62:9: note: IND04: Rightmost declarator is here
   62 | double& ooooooooo = ddddd;
      |         ^
decls.cpp:75:12: warning: IND04: Declarators on consecutive lines must be aligned
   75 |     double d;
      |            ^
decls.cpp:76:17: note: IND04: Rightmost declarator is here
   76 |     class z { } a;
      |                 ^
decls.cpp:77:9: warning: IND04: Declarators on consecutive lines must be aligned
   77 |     int y;
      |         ^
decls.cpp:76:17: note: IND04: Rightmost declarator is here
   76 |     class z { } a;
      |                 ^
17 warnings generated.
