csabbg_bslstdstring.t.cpp:15:7: warning: ST01: Converting std::string to bsl::string
   15 |     f(s);
      |       ^
csabbg_bslstdstring.t.cpp:19:17: warning: ST01: Converting std::string to bsl::string
   19 |     bsl::string y(s);
      |                 ^
csabbg_bslstdstring.t.cpp:16:7: warning: ST02: Converting bsl::string to std::string
   16 |     g(b);
      |       ^
3 warnings generated.
