main.cpp:6:11: warning: IC01: 'Bloomberg' header included within C linkage specification
    6 | #include <cppfile.h>
      |           ^
main.cpp:4:8: note: IC01: C linkage specification here
    4 | extern "C" {
      |        ^
In file included from main.cpp:1:
./cppfile.h:7:23: note: IC01: 'Bloomberg' evidence here
    7 | // Copyright (C) 2014 Bloomberg Finance L.P.
      |                       ^
main.cpp:8:11: warning: IC01: 'Bloomberg' header included within C linkage specification
    8 | #include <cppfile.h>
      |           ^
main.cpp:4:8: note: IC01: C linkage specification here
    4 | extern "C" {
      |        ^
In file included from main.cpp:1:
./cppfile.h:7:23: note: IC01: 'Bloomberg' evidence here
    7 | // Copyright (C) 2014 Bloomberg Finance L.P.
      |                       ^
main.cpp:10:11: warning: IC01: 'Bloomberg' header included within C linkage specification
   10 | #include <deep.h>
      |           ^
main.cpp:4:8: note: IC01: C linkage specification here
    4 | extern "C" {
      |        ^
In file included from main.cpp:10:
In file included from ./deep.h:3:
In file included from ./deep.h:8:
In file included from ./deep.h:13:
In file included from ./deep.h:18:
In file included from ./deep.h:23:
In file included from ./deep.h:28:
In file included from ./deep.h:33:
In file included from ./deep.h:38:
In file included from ./deep.h:43:
./deep.h:54:23: note: IC01: 'Bloomberg' evidence here
   54 | // Copyright (C) 2014 Bloomberg Finance L.P.
      |                       ^
3 warnings generated.
