csamisc_contiguousswitch.t.cpp:30:5: warning: ES01: Empty switch statement
   30 |     switch (ac) {
      |     ^
csamisc_contiguousswitch.t.cpp:35:9: warning: CS01: Test code should be within compound (brace-enclosed) statement
   35 |         ++ac;
      |         ^
csamisc_contiguousswitch.t.cpp:34:5: warning: SD01: Switch starts with `default:` label
   34 |     default:
      |     ^
csamisc_contiguousswitch.t.cpp:37:5: warning: SZ01: Switch should start with `case 0:`
   37 |     case 1:
      |     ^
csamisc_contiguousswitch.t.cpp:46:5: warning: SZ01: Switch should start with `case 0:`
   46 |     case 1: {
      |     ^
csamisc_contiguousswitch.t.cpp:49:5: warning: SZ01: Switch should start with `case 0:`
   49 |     case 0: {
      |     ^
csamisc_contiguousswitch.t.cpp:49:5: warning: ZF02: `case 0:` should simply fall through to next case
csamisc_contiguousswitch.t.cpp:58:5: warning: MD01: `default:` label in the middle of labels
   58 |     default: break;
      |     ^
csamisc_contiguousswitch.t.cpp:65:5: warning: MD01: `default:` label in the middle of labels
   65 |     default: break;
      |     ^
csamisc_contiguousswitch.t.cpp:72:9: warning: CS01: Test code should be within compound (brace-enclosed) statement
   72 |         switch (ac + 1) {
      |         ^
csamisc_contiguousswitch.t.cpp:76:5: warning: MB01: Missing `break;` before this case
   76 |     case 5: break;
      |     ^
csamisc_contiguousswitch.t.cpp:69:5: warning: ED01: Switch doesn't end with `default:` label
   69 |     switch (ac) // missing default
      |     ^
csamisc_contiguousswitch.t.cpp:71:5: warning: ZF02: `case 0:` should simply fall through to next case
   71 |     case 0:
      |     ^
csamisc_contiguousswitch.t.cpp:87:5: warning: LO01: Case label out of order: previous=100 value=5
   87 |     case 5: break;
      |     ^
csamisc_contiguousswitch.t.cpp:101:9: warning: CS01: Test code should be within compound (brace-enclosed) statement
  101 |         ++ac;
      |         ^
csamisc_contiguousswitch.t.cpp:107:9: warning: CS02: Test code should be within single compound (brace-enclosed) statement
  107 |         ++ac;
      |         ^
csamisc_contiguousswitch.t.cpp:109:5: warning: MB01: Missing `break;` before this case
  109 |     case 10: {
      |     ^
csamisc_contiguousswitch.t.cpp:109:5: warning: SM01: Switch missing case values below 10
18 warnings generated.
