uncalled.t.cpp:85:9: warning: TP27: Method not called in test driver
   85 |         joe(int uncalled);
      |         ^
uncalled.t.cpp:87:14: warning: TP27: Method not called in test driver
   87 |         void f1(int uncalled);
      |              ^
uncalled.t.cpp:89:14: warning: TP27: Method not called in test driver
   89 |         void f2(int uncalled);
      |              ^
uncalled.t.cpp:91:14: warning: TP27: Method not called in test driver
   91 |         void f3(int uncalled);
      |              ^
uncalled.t.cpp:93:21: warning: TP27: Method not called in test driver
   93 |         static void f4(int uncalled);
      |                     ^
uncalled.t.cpp:95:21: warning: TP27: Method not called in test driver
   95 |         static void f5(int uncalled);
      |                     ^
uncalled.t.cpp:97:21: warning: TP27: Method not called in test driver
   97 |         static void f6(int uncalled);
      |                     ^
uncalled.t.cpp:99:21: warning: TP27: Method not called in test driver
   99 |         static void f7(int uncalled);
      |                     ^
uncalled.t.cpp:100:14: warning: TP27: Method not called in test driver
  100 |         void f8(int uncalled);
      |              ^
uncalled.t.cpp:101:21: warning: TP27: Method not called in test driver
  101 |         static void f9(int uncalled);
      |                     ^
10 warnings generated.
