is.cpp:5:55: warning: ISC03: Out-of-range value may cause unexpected behavior
    5 | struct Y {                   int f() { return isspace(1000); } };
      |                                                       ^
is.cpp:9:55: warning: ISC03: Out-of-range value may cause unexpected behavior
    9 | struct W {                   int f() { return isspace(1000); } };
      |                                                       ^
is.cpp:13:25: warning: ISC01: Sign extension may cause unexpected behavior
   13 |     return std::isspace(v[0][0]) +
      |                         ^
is.cpp:14:25: warning: ISC03: Out-of-range value may cause unexpected behavior
   14 |            std::isspace(1000000) +
      |                         ^
is.cpp:18:25: warning: ISC03: Out-of-range value may cause unexpected behavior
   18 |            std::isspace(256) +
      |                         ^
is.cpp:19:25: warning: ISC02: Sign extension may cause unexpected behavior
   19 |            std::isspace('\x80') +
      |                         ^
is.cpp:20:25: warning: ISC02: Sign extension may cause unexpected behavior
   20 |            std::isspace('\xFF') +
      |                         ^
is.cpp:22:25: warning: ISC03: Out-of-range value may cause unexpected behavior
   22 |            std::isspace(-2) +
      |                         ^
is.cpp:23:25: warning: ISC02: Sign extension may cause unexpected behavior
   23 |            std::isspace(char(-1)) +
      |                         ^
is.cpp:24:20: warning: ISC01: Sign extension may cause unexpected behavior
   24 |            isspace(v[0][0]) +
      |                    ^
is.cpp:25:20: warning: ISC03: Out-of-range value may cause unexpected behavior
   25 |            isspace(1000000) +
      |                    ^
is.cpp:29:20: warning: ISC03: Out-of-range value may cause unexpected behavior
   29 |            isspace(256) +
      |                    ^
is.cpp:30:20: warning: ISC02: Sign extension may cause unexpected behavior
   30 |            isspace('\x80') +
      |                    ^
is.cpp:31:20: warning: ISC02: Sign extension may cause unexpected behavior
   31 |            isspace('\xFF') +
      |                    ^
is.cpp:33:20: warning: ISC03: Out-of-range value may cause unexpected behavior
   33 |            isspace(-2) +
      |                    ^
is.cpp:34:20: warning: ISC02: Sign extension may cause unexpected behavior
   34 |            isspace(char(-1));
      |                    ^
16 warnings generated.
