In file included from csabase_diagnosticfilter.t.cpp:3:
./csabase_diagnosticfilter.t.hpp:28:13: warning: address of stack memory associated with parameter 'value' returned [-Wreturn-stack-address]
   28 |     return &value;
      |             ^~~~~
csabase_diagnosticfilter.t.cpp:11:13: warning: address of stack memory associated with parameter 'value' returned [-Wreturn-stack-address]
   11 |     return &value;
      |             ^~~~~
2 warnings generated.
