In file included from csastil_externalguards.t.cpp:3:
./csastil_externalguards.t.h:7:1: warning: SEG04: Include of 'bdes_ident.h' with external include guard 'INCLUDED_BDES_IDENT'
    7 | #  include <bdes_ident.h>
      | ^
./csastil_externalguards.t.h:11:1: warning: SEG04: Include of 'csascm_version.h' with external include guard 'INCLUDED_CSASCM_VERSION'
   11 | #  include <csascm_version.h>
      | ^
./csastil_externalguards.t.h:14:1: warning: SEG04: Include of 'csascm_version.h' with external include guard 'INCLUDED_CSASCMVERSION'
   14 | #  include <csascm_version.h>
      | ^
./csastil_externalguards.t.h:13:2: warning: SEG02: Include guard 'INCLUDED_CSASCMVERSION' mismatch for included file 'csascm_version.h' - use 'INCLUDED_CSASCM_VERSION'
   13 | #ifndef INCLUDED_CSASCMVERSION
      |  ^
./csastil_externalguards.t.h:23:2: warning: SEG02: Include guard 'INCLUDED_BDES_IDENT' mismatch for included file 'bdes_identi.h' - use 'INCLUDED_BDES_IDENTI'
   23 | #if !defined INCLUDED_BDES_IDENT
      |  ^
./csastil_externalguards.t.h:26:2: warning: SEG02: Include guard 'INCLUDED_BDES_IDENT' mismatch for included file 'bdes_identi.h' - use 'INCLUDED_BDES_IDENTI'
   26 | #if !defined(INCLUDED_BDES_IDENT)
      |  ^
./csastil_externalguards.t.h:29:2: warning: SEG02: Include guard 'INCLUDED_BDES_IDENT' mismatch for included file 'bdes_identi.h' - use 'INCLUDED_BDES_IDENTI'
   29 | #ifndef INCLUDED_BDES_IDENT
      |  ^
./csastil_externalguards.t.h:32:2: warning: SEG01: Include guard 'INCLUDED_BDES_IDENT' without include file
   32 | #ifndef INCLUDED_BDES_IDENT
      |  ^
./csastil_externalguards.t.h:35:2: warning: SEG01: Include guard 'INCLUDED_BDES_IDENT' without include file
   35 | #ifndef INCLUDED_BDES_IDENT
      |  ^
./csastil_externalguards.t.h:38:2: warning: SEG01: Include guard 'INCLUDED_BDES_IDENT' without include file
   38 | #ifndef INCLUDED_BDES_IDENT
      |  ^
./csastil_externalguards.t.h:40:1: warning: SEG03: Include of 'bdes_ident.h' without external include guard 'INCLUDED_BDES_IDENT'
   40 | #include <bdes_ident.h>
      | ^
./csastil_externalguards.t.h:42:1: warning: SEG03: Include of 'bdes_ident.h' without external include guard 'INCLUDED_BDES_IDENT'
   42 | #  include <bdes_ident.h>
      | ^
12 warnings generated.
