gggx_ggg.cpp:6:7: warning: TR11: Globally visible type 'BloombergLP::gggx::Aa' should be defined in header.
    6 | class Aa { };
      |       ^
gggx_ggg.cpp:7:7: warning: TR10: Globally visible type 'BloombergLP::gggx::Bb' is not declared in header.
    7 | class Bb;
      |       ^
gggx_ggg.cpp:8:7: warning: TR11: Globally visible type 'BloombergLP::gggx::Cc' should be defined in header.
    8 | class Cc { };
      |       ^
gggx_ggg.cpp:14:28: warning: TR10: Globally visible type 'BloombergLP::gggx::Uu' is not declared in header.
   14 | template <class PP> struct Uu;
      |                            ^
gggx_ggg.cpp:17:28: warning: TR11: Globally visible type 'BloombergLP::gggx::Vv' should be defined in header.
   17 | template <class PP> struct Vv { };
      |                            ^
5 warnings generated.
