bad_classes.t.cpp:2:12: warning: CLS01: '//@CLASSES:' line should contain no other text (classes go on subsequent lines, one per line)
    2 | //@CLASSES: a::b
      |            ^
bad_classes.t.cpp:2:17: warning: CLS02: Class name must be followed by ': description'
    2 | //@CLASSES: a::b
      |                 ^
bad_classes.t.cpp:3:1: warning: CLS03: Badly formatted class line; should be '//  class: description'
    3 | //    'd_e': f
      | ^
bad_classes.t.cpp:4:1: warning: CLS03: Badly formatted class line; should be '//  class: description'
    4 | //    'g::h': i
      | ^
bad_classes.t.cpp:5:11: warning: CLS02: Class name must be followed by ': description'
    5 | //    j::k
      |           ^
bad_classes.t.cpp:6:10: warning: CLS02: Class name must be followed by ': description'
    6 | //    l_m
      |          ^
bad_classes.t.cpp:7:17: warning: CLS02: Class name must be followed by ': description'
    7 | //    n::o::p::q
      |                 ^
7 warnings generated.
