csabbg_enumvalue.t.cpp:9:9: warning: EV01: Do not use 'Value' as enum name
    9 | enum    Value { Nb = -1, Zb = 0 };
      |         ^
csabbg_enumvalue.t.cpp:13:13: warning: EV01: Do not use 'Value' as enum name
   13 |     enum    Value { Nb = -1, Zb = 0 };
      |             ^
csabbg_enumvalue.t.cpp:19:13: warning: EV01: Do not use 'Value' as enum name
   19 |     enum    Value { Nb = -1, Zb = 0 };
      |             ^
csabbg_enumvalue.t.cpp:25:13: warning: EV01: Do not use 'Value' as enum name
   25 |     enum    Value { Nb = -1, Zb = 0 };
      |             ^
csabbg_enumvalue.t.cpp:29:17: warning: EV01: Do not use 'Value' as enum name
   29 |         enum    Value { Nb = -1, Zb = 0 };
      |                 ^
csabbg_enumvalue.t.cpp:35:17: warning: EV01: Do not use 'Value' as enum name
   35 |         enum    Value { Nb = -1, Zb = 0 };
      |                 ^
csabbg_enumvalue.t.cpp:41:17: warning: EV01: Do not use 'Value' as enum name
   41 |         enum    Value { Nb = -1, Zb = 0 };
      |                 ^
csabbg_enumvalue.t.cpp:45:21: warning: EV01: Do not use 'Value' as enum name
   45 |             enum    Value { Nb = -1, Zb = 0 };
      |                     ^
csabbg_enumvalue.t.cpp:51:21: warning: EV01: Do not use 'Value' as enum name
   51 |             enum    Value { Nb = -1, Zb = 0 };
      |                     ^
csabbg_enumvalue.t.cpp:57:21: warning: EV01: Do not use 'Value' as enum name
   57 |             enum    Value { Nb = -1, Zb = 0 };
      |                     ^
csabbg_enumvalue.t.cpp:61:25: warning: EV01: Do not use 'Value' as enum name
   61 |                 enum    Value { Nb = -1, Zb = 0 };
      |                         ^
csabbg_enumvalue.t.cpp:67:25: warning: EV01: Do not use 'Value' as enum name
   67 |                 enum    Value { Nb = -1, Zb = 0 };
      |                         ^
12 warnings generated.
