csabbg_midreturn.t.cpp:17:25: warning: MR01: Mid-function 'return' requires '// RETURN' comment
   17 |                         return false;
      |                         ^
csabbg_midreturn.t.cpp:17:25: note: MR01: Correct text is
                        return false;                                 // RETURN
csabbg_midreturn.t.cpp:23:17: warning: MR01: Mid-function 'return' requires '// RETURN' comment
   23 |                 return 1;
      |                 ^
csabbg_midreturn.t.cpp:23:17: note: MR01: Correct text is
                return 1;                                             // RETURN
csabbg_midreturn.t.cpp:26:70: warning: MR02: '// RETURN' comment must end in column 79, not 78
   26 |                 return 2;                                            // RETURN
      |                                                                      ^
csabbg_midreturn.t.cpp:26:70: note: MR02: Correct text is
                return 2;                                             // RETURN
csabbg_midreturn.t.cpp:29:17: warning: MR01: Mid-function 'return' requires '// RETURN' comment
   29 |                 return 3;
      |                 ^
csabbg_midreturn.t.cpp:29:17: note: MR01: Correct text is
                return 3;                                             // RETURN
csabbg_midreturn.t.cpp:44:25: warning: MR01: Mid-function 'return' requires '// RETURN' comment
   44 |                         return false;
      |                         ^
csabbg_midreturn.t.cpp:44:25: note: MR01: Correct text is
                        return false;                                 // RETURN
csabbg_midreturn.t.cpp:50:17: warning: MR01: Mid-function 'return' requires '// RETURN' comment
   50 |                 return 1;
      |                 ^
csabbg_midreturn.t.cpp:50:17: note: MR01: Correct text is
                return 1;                                             // RETURN
csabbg_midreturn.t.cpp:53:70: warning: MR02: '// RETURN' comment must end in column 79, not 78
   53 |                 return 2;                                            // RETURN
      |                                                                      ^
csabbg_midreturn.t.cpp:53:70: note: MR02: Correct text is
                return 2;                                             // RETURN
csabbg_midreturn.t.cpp:56:17: warning: MR01: Mid-function 'return' requires '// RETURN' comment
   56 |                 return 3;
      |                 ^
csabbg_midreturn.t.cpp:56:17: note: MR01: Correct text is
                return 3;                                             // RETURN
csabbg_midreturn.t.cpp:72:70: warning: MR02: '// RETURN' comment must end in column 79, not 78
   72 |                 return 5;          // Comment                        // RETURN
      |                                                                      ^
csabbg_midreturn.t.cpp:72:70: note: MR02: Correct text is
                return 5;          // Comment                         // RETURN
csabbg_midreturn.t.cpp:78:72: warning: MR02: '// RETURN' comment must end in column 79, not 80
   78 |                 return 7;          // Comment                          // RETURN
      |                                                                        ^
csabbg_midreturn.t.cpp:78:72: note: MR02: Correct text is
                return 7;          // Comment                         // RETURN
csabbg_midreturn.t.cpp:87:21: warning: MR01: Mid-function 'return' requires '// RETURN' comment
   87 |                     return;
      |                     ^
csabbg_midreturn.t.cpp:87:21: note: MR01: Correct text is
                    return;                                           // RETURN
csabbg_midreturn.t.cpp:90:70: warning: MR02: '// RETURN' comment must end in column 79, not 78
   90 |                     return;                                          // RETURN
      |                                                                      ^
csabbg_midreturn.t.cpp:90:70: note: MR02: Correct text is
                    return;                                           // RETURN
csabbg_midreturn.t.cpp:93:21: warning: MR01: Mid-function 'return' requires '// RETURN' comment
   93 |                     return;
      |                     ^
csabbg_midreturn.t.cpp:93:21: note: MR01: Correct text is
                    return;                                           // RETURN
csabbg_midreturn.t.cpp:107:21: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  107 |                     return;
      |                     ^
csabbg_midreturn.t.cpp:107:21: note: MR01: Correct text is
                    return;                                           // RETURN
csabbg_midreturn.t.cpp:110:70: warning: MR02: '// RETURN' comment must end in column 79, not 78
  110 |                     return;                                          // RETURN
      |                                                                      ^
csabbg_midreturn.t.cpp:110:70: note: MR02: Correct text is
                    return;                                           // RETURN
csabbg_midreturn.t.cpp:113:21: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  113 |                     return;
      |                     ^
csabbg_midreturn.t.cpp:113:21: note: MR01: Correct text is
                    return;                                           // RETURN
csabbg_midreturn.t.cpp:130:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  130 |             if (f()) return                                                    1;
      |                      ^
csabbg_midreturn.t.cpp:130:22: note: MR01: Correct text is
            if (f()) return                                                    1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:131:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  131 |             if (f()) return                                                   1;
      |                      ^
csabbg_midreturn.t.cpp:131:22: note: MR01: Correct text is
            if (f()) return                                                   1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:132:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  132 |             if (f()) return                                                  1;
      |                      ^
csabbg_midreturn.t.cpp:132:22: note: MR01: Correct text is
            if (f()) return                                                  1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:133:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  133 |             if (f()) return                                                 1;
      |                      ^
csabbg_midreturn.t.cpp:133:22: note: MR01: Correct text is
            if (f()) return                                                 1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:134:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  134 |             if (f()) return                                                1;
      |                      ^
csabbg_midreturn.t.cpp:134:22: note: MR01: Correct text is
            if (f()) return                                                1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:135:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  135 |             if (f()) return                                               1;
      |                      ^
csabbg_midreturn.t.cpp:135:22: note: MR01: Correct text is
            if (f()) return                                               1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:136:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  136 |             if (f()) return                                              1;
      |                      ^
csabbg_midreturn.t.cpp:136:22: note: MR01: Correct text is
            if (f()) return                                              1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:137:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  137 |             if (f()) return                                             1;
      |                      ^
csabbg_midreturn.t.cpp:137:22: note: MR01: Correct text is
            if (f()) return                                             1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:138:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  138 |             if (f()) return                                            1;
      |                      ^
csabbg_midreturn.t.cpp:138:22: note: MR01: Correct text is
            if (f()) return                                            1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:139:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  139 |             if (f()) return                                           1;
      |                      ^
csabbg_midreturn.t.cpp:139:22: note: MR01: Correct text is
            if (f()) return                                           1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:140:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  140 |             if (f()) return                                          1;
      |                      ^
csabbg_midreturn.t.cpp:140:22: note: MR01: Correct text is
            if (f()) return                                          1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:141:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  141 |             if (f()) return                                         1;
      |                      ^
csabbg_midreturn.t.cpp:141:22: note: MR01: Correct text is
            if (f()) return                                         1;
                                                                      // RETURN
csabbg_midreturn.t.cpp:142:22: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  142 |             if (f()) return                                        1;
      |                      ^
csabbg_midreturn.t.cpp:142:22: note: MR01: Correct text is
            if (f()) return                                        1; // RETURN
csabbg_midreturn.t.cpp:187:17: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  187 |                 return NULL;
      |                 ^
csabbg_midreturn.t.cpp:187:17: note: MR01: Correct text is
                return NULL;                                          // RETURN
csabbg_midreturn.t.cpp:190:31: warning: MR02: '// RETURN' comment must end in column 79, not 39
  190 |                 return NULL;  // RETURN
      |                               ^
csabbg_midreturn.t.cpp:190:31: note: MR02: Correct text is
                return NULL;                                          // RETURN
csabbg_midreturn.t.cpp:205:17: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  205 |                 return n;
      |                 ^
csabbg_midreturn.t.cpp:205:17: note: MR01: Correct text is
                return n;                                             // RETURN
csabbg_midreturn.t.cpp:227:17: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  227 |                 return 7;
      |                 ^
csabbg_midreturn.t.cpp:227:17: note: MR01: Correct text is
                return 7;                                             // RETURN
csabbg_midreturn.t.cpp:230:17: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  230 |                 return n;
      |                 ^
csabbg_midreturn.t.cpp:230:17: note: MR01: Correct text is
                return n;                                             // RETURN
csabbg_midreturn.t.cpp:245:17: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  245 |                 return n;
      |                 ^
csabbg_midreturn.t.cpp:245:17: note: MR01: Correct text is
                return n;                                             // RETURN
csabbg_midreturn.t.cpp:252:21: warning: MR01: Mid-function 'return' requires '// RETURN' comment
  252 |                     return 1;
      |                     ^
csabbg_midreturn.t.cpp:252:21: note: MR01: Correct text is
                    return 1;                                         // RETURN
36 warnings generated.
