csamisc_constantreturn.t.cpp:8:12: warning: CR01: Function 'f' has only one statement which returns the constant '0'
    6 | int bde_verify::csamisc::constantreturn::f()
      |                                          ~
    7 | {
    8 |     return 0;
      |            ^
csamisc_constantreturn.t.cpp:6:42: note: CR01: Declaration of 'f' (which always returns the constant 0)
    6 | int bde_verify::csamisc::constantreturn::f()
      |                                          ^
In file included from csamisc_constantreturn.t.cpp:3:
./csamisc_constantreturn.t.hpp:22:24: note: CR01: Declaration of 'f' (which always returns the constant 0)
   22 |             static int f();
      |                        ^
csamisc_constantreturn.t.cpp:13:14: warning: CR01: Function 'g' has only one statement which returns the constant '13'
   11 | int bde_verify::csamisc::constantreturn::g()
      |                                          ~
   12 | {
   13 |     return 5 + 8;
      |              ^
csamisc_constantreturn.t.cpp:11:42: note: CR01: Declaration of 'g' (which always returns the constant 13)
   11 | int bde_verify::csamisc::constantreturn::g()
      |                                          ^
In file included from csamisc_constantreturn.t.cpp:3:
./csamisc_constantreturn.t.hpp:23:24: note: CR01: Declaration of 'g' (which always returns the constant 13)
   23 |             static int g();
      |                        ^
2 warnings generated.
