h.cpp:19:8: warning: AT02: Class 'YY' uses allocators but does not have an allocator trait
   19 | struct YY {
      |        ^
h.cpp:19:8: warning: AC02: Class 'YY' implicit copy constructor is not allocator-aware
h.cpp:28:8: warning: AT02: Class 'YY' uses allocators but does not have an allocator trait
   28 | struct YY {
      |        ^
h.cpp:28:8: warning: AC02: Class 'YY' implicit copy constructor is not allocator-aware
h.cpp:40:8: warning: AT02: Class 'YY' uses allocators but does not have an allocator trait
   40 | struct YY {
      |        ^
h.cpp:40:8: warning: AC02: Class 'YY' implicit copy constructor is not allocator-aware
h.cpp:52:8: warning: AT02: Class 'YY' uses allocators but does not have an allocator trait
   52 | struct YY {
      |        ^
h.cpp:52:8: warning: AC02: Class 'YY' implicit copy constructor is not allocator-aware
h.cpp:61:12: warning: AT02: Class 'YY' uses allocators but does not have an allocator trait
   61 |     struct YY {
      |            ^
h.cpp:77:8: warning: AT02: Class 'Y' uses allocators but does not have an allocator trait
   77 | struct Y {
      |        ^
h.cpp:87:8: warning: AT02: Class 'Y' uses allocators but does not have an allocator trait
   87 | struct Y {
      |        ^
h.cpp:100:8: warning: AT02: Class 'Y' uses allocators but does not have an allocator trait
  100 | struct Y {
      |        ^
h.cpp:113:8: warning: AT02: Class 'Y' uses allocators but does not have an allocator trait
  113 | struct Y {
      |        ^
h.cpp:121:27: warning: AT02: Class 'Y<T *>' uses allocators but does not have an allocator trait
  121 | template <class T> struct Y<T*> {
      |                           ^
h.cpp:124:20: warning: AT02: Class 'Y<int>' uses allocators but does not have an allocator trait
  124 | template <> struct Y<int> {
      |                    ^
h.cpp:124:20: warning: AC02: Class 'Y' implicit copy constructor is not allocator-aware
h.cpp:130:12: warning: AT02: Class 'Y' uses allocators but does not have an allocator trait
  130 |     struct Y {
      |            ^
h.cpp:130:12: warning: AC02: Class 'Y' implicit copy constructor is not allocator-aware
h.cpp:138:12: warning: AT02: Class 'Y' uses allocators but does not have an allocator trait
  138 |     struct Y {
      |            ^
h.cpp:149:11: warning: AT02: Class 'Y<Y<T>, 1, Y>' uses allocators but does not have an allocator trait
  149 | struct M::Y<Y<T>, 1, Y> {
      |           ^
h.cpp:154:11: warning: AT02: Class 'Y<T *, N, X>' uses allocators but does not have an allocator trait
  154 | struct M::Y<T*, N, X> {
      |           ^
21 warnings generated.
