csafmt_indent.t.cpp:26:8: warning: IND02: Function parameters should be all on a single line or each on a separate line
   26 |        int c)
      |        ^
csafmt_indent.t.cpp:31:15: warning: IND02: Function parameters should be all on a single line or each on a separate line
   31 |        int b, int c)
      |               ^
csafmt_indent.t.cpp:41:11: warning: IND03: Function parameter names should align vertically
   41 |       int c)
      |           ^
csafmt_indent.t.cpp:39:12: note: IND03: Rightmost name is here
   39 | void j(int a,
      |            ^
csafmt_indent.t.cpp:13:5: warning: IND01: Possibly mis-indented line
   13 |     {
      |     ^
csafmt_indent.t.cpp:13:5: note: IND01: Correct version may be
{
csafmt_indent.t.cpp:14:3: warning: IND01: Possibly mis-indented line
   14 |   F(); F();
      |   ^
csafmt_indent.t.cpp:14:3: note: IND01: Correct version may be
    F(); F();
csafmt_indent.t.cpp:22:9: warning: IND01: Possibly mis-indented line
   22 |         return 0;
      |         ^
csafmt_indent.t.cpp:22:9: note: IND01: Correct version may be
    return 0;
csafmt_indent.t.cpp:41:7: warning: IND01: Possibly mis-indented line
   41 |       int c)
      |       ^
csafmt_indent.t.cpp:41:7: note: IND01: Correct version may be
       int c)
7 warnings generated.
